### ISSUE TITLE
misconfiguration of the  `ALLOWED_HOSTS` for pythonanywhere

### ISSUE THREAD

**Issue by edouard-lopez** [DjangoGirls/tutorial#1002]
We found this issue during the latest [@DjangoGirlsBdx](https://djangogirls.org/bordeaux/).

### Explanation

Deploying on pythonanywhere.com could trigger some error due to the misconfiguration of the  `ALLOWED_HOSTS`. One solution is to edit `mysite/settings.py` to set 

     ALLOWED_HOSTS=['*']

## French

> @pamplemousse : Il se peut que vous rencontriez une erreur au moment du déploiement sur pythonanywhere.
Il faut modifier les `ALLOWED_HOSTS` dans `settings.py` avec votre url <nom d'utilisateur>.pythonanywhere.com.
Faisable directement sur leur interface web, à faire locallement et à commiter avant de déployer.

> @kardaj le problème avec ton fix c’est que le site ne marchera plus en local. On pourra aussi mettre ALLOWED_HOSTS=['*']

**Comment by gsimore** [comment]
I also had the problem with ALLOWED_HOSTS, and added '<my_username>.pythonanywhere.com', but not everyone encountered this error. Does anyone know the reason for that? 


J'ai également eu le problème avec ALLOWED_HOSTS, et j'ai ajouté '<my_username> .pythonanywhere.com', mais pas tout le monde a rencontré cette erreur. Est-ce que quelqu'un connaît la raison pour laquelle?

**Comment by rsip22** [comment]
Hi, @gsimore ! Could you confirm to us which Python and Django version are you using?

We've also had this problem sporadically around here, but we have fixed with the solution you've mentioned.

**Comment by ekohl** [comment]
The default was just changed and verified in the latest English version. I verified that worked for me so I'm going to close this. Please reopen this or a new issue if the problem persists.

**Comment by emexbazz** [comment]
i have this problem what do i do

**Comment by emexbazz** [comment]
someone answer me

**Comment by emexbazz** [comment]
i have he above solutins but it efused

**Comment by gsimore** [comment]
> i have he above solutins but it efused

What version of Django are you using? 

I've had success using `ALLOWED_HOSTS = ['*']` in Django 1.11 and later versions.

**Comment by subrahmanyam0326** [comment]
I am tired of this error

DisallowedHost at / Invalid HTTP_HOST header: 'subrahmanyam0326.pythonanywhere.com'. You may need to add 'subrahmanyam0326.pythonanywhere.com' to ALLOWED_HOSTS.

settings.py:

ALLOWED_HOSTS=['subrahmanyam0326.pythonanywhere.com']

**Comment by ekohl** [comment]
What is the value of your `ALLOWED_HOSTS`? It should include `.pythonanywhere.com` as instructed in https://tutorial.djangogirls.org/en/django_start_project/. Does that not work for you?
