### ISSUE TITLE
An error at url of link for adding new posts (section django_forms)

### ISSUE THREAD

**Issue by LaHesis** [DjangoGirls/tutorial#1010]
It seems that there is some error on line <a href="{% url 'blog.views.post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> at https://tutorial.djangogirls.org/ru/django_forms
I will see such error
"NoReverseMatch at /
Reverse for 'blog.views.post_new' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []",
if I write "url 'blog.views.post_new'", but if I write "url 'post_new'" there will be no such error.

**Comment by helenst** [comment]
Hi @LaHesis Thank you for reporting this! We'd be very happy to receive a pull request to fix it, would you like to submit one? :sparkles:

**Comment by LaHesis** [comment]
@helenst I've never done pull requests yet, but I can try.

**Comment by helenst** [comment]
Fixed by #1011
