### ISSUE TITLE
Hi, trouble with adding commenting feature to my django blog.  thank you

### ISSUE THREAD

**Issue by kinganu** [DjangoGirls/tutorial#1018]
https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/homework_create_more_models/

Hi I tried following this and had some trouble.  I have a simple blog in django with a Post class, and would like to add a simple Comment system for visitors (form with Name, Email, text area, timestamp (maybe a recaptcha field to prevent spam) submit)

I dont need moderated comments, I can just moderate them in django admin.  Dont need authentication either.  Would like a reply to comment button as well, perhaps edit / delete comment option maybe (enter email if needed to edit - rather than user login).  I realize this gets just a tad bit complex, but would like the simplest solution, if you have any methods would be appreciated.  Thank you.

Heres my basic setup so far:

https://dpaste.de/hOvU

EDIT:  maybe instead of trying to engineer/ reinvent the wheel I hear you can integrate disqus with django, should be simpler and easier to deal with.  TRIED IT.  IT WORKS beautifully!  

For anyone curious here is what I did.  Create an account at disqus, select 'I want to use it in my site', add your sites shortname and domain (in my case Im devving locally on ubuntu VM and used my dev domain I created 'djang0.me' for my test django blog).  Go to installation instructions, select 'universal code' at bottom and copy the code.  I decided to use an include disqus block in my django blogs Post template, which is very nice:

```
# blog/includes/disqus.html

{% block disqus %}

<div class="container">
	<div class="row">

<a class="btn btn-default arches" role="button" data-toggle="collapse" href="#dcomments" aria-expanded="true" style="width: 120px; display: block; margin: 0 auto; margin-top: 20vh;"> <h4 class="text-success"> Comments &raquo; </h4> </a>

		<div class="col-md-6 col-md-offset-3">
						
			<div class="panel collapse stucco" id="dcomments" style="margin-top: 10vh;">

<div id="disqus_thread"></div>

			</div>
			
		</div>
	</div>
</div>

<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = djang0.me;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = ; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://YOURSHORTHANDNAME.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

<script id="dsq-count-scr" src="//YOURSHORTHANDNAME.disqus.com/count.js" async></script>

{% endblock %}


# blog/post.html

						{% extends "blog/blogbase.html" %}	

					                    {% block body %}		
													
<div class="container">
		<div class="col-md-12 text-center">
			<h6 class="pull-right"> on {{ post.date }} </h6> <br>
			<h3> {{ post.title }} </h3> <br>
		<img src="{% if post.image %} {{ post.image.url }} {% endif %}" class="img-responsive center-block" align="left" alt=""> 
		 		<p> {{ post.body|safe|linebreaks }} </p>
		</div>
</div>														

{% include 'blog/includes/disqus.html' %}
{% block disqus %}{% endblock %}

								{% endblock %}

**Comment by aniav** [comment]
Hey @kinganu I am sorry for not replying earlier! I am just going through the issues in the tutorial and cleaning up a bit :)

Thank you for your comment. It's great you managed to handle the comments section on your blog. We are introducing Comments in our tutorial as a means of teaching people new things about programming so we would like to keep it that way. It introduces the concept of connecting multiple elements in a database and how they relate, it helps to understand how it works around the internet. It is not a means of introducing the only proper way of handling comments so it's awesome you found a better solution 🎉 

I will close this issue for now as it's not really about an issue in the tutorial 💃
