### ISSUE TITLE
Virtualenv stored in different places between local and pythonanywhere

### ISSUE THREAD

**Issue by T4m** [DjangoGirls/tutorial#1026]
On the local computer we create a virtual environment in the git project's **parent folder**. This way, we don't have to git-ignore the myvenv folder, and we avoid to version it.

Then on pythonanywhere, we create a virtualenv **inside the project folder**. Why don't we create it in the parent folder too (like /home/username/myvenv, aside of /home/username/mysite) ?

It works in the both way. I don't know if there are reason to put it in a specific place. I think it would be less confusing to put it always in the parent folder, or always in the project folder (and gitignore it). What do you think ?

**Comment by hjwp** [comment]
Hi there, there is now a new deploy procedure (#1190) which means the user no longer actively creates the virtualenv themselves on pythonanywhere, it's created automatically. It's still not in the same place as locally, but at least it's not inside the project folder, so gitignore isn't an issue.

Take a look and re-open (or open another issue) if you think there are still improvements that could be made?
