### ISSUE TITLE
git add --all adds too much to the Django git repo

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1027]
https://tutorial.djangogirls.org/en/deploy/ has:

```
$ git add --all .
$ git commit -m "My Django Girls app, first commit"
...
$ git remote add origin https://github.com/<your-github-username>/my-first-blog.git
$ git push -u origin master
```

The current directory for that is `~/djangogirls`, which may already contain many files and directories which shouldn't be pushed. Even though `.gitignore` takes care of `myvenv`, there my be others, especially by those participants who love experimenting and creating `.py` files.

My recommended solution: Create the Django project in the `~/djangogirls/my-first-blog`subdirectory.

**Comment by ekohl** [comment]
Another issue is that many students place their virtualenv with a different name, leading to including the venv in git. It'll work, but leads to bigger git push/pull. A subdirectory might work but do realise that the concept of files and directories is already a difficult one (see #1042).

**Comment by pts** [comment]
> the concept of files and directories is already a difficult one

I think students have a good understanding of files. They also have some understanding of directories, e.g. they know that Documents and Downloads are different directories. I think creating a subdirectory here would be juts a minor complexity for them.

**Comment by ekohl** [comment]
That highly depends on your students. Some have no problems at all, but others needs some explanation.

**Comment by pts** [comment]
To clarify my recommended solution: Create the Django project in the `~/djangogirls/my-first-blog` subdirectory. modify the tutorial accordingly (probably at multiple locations), and add some explanation to the tutorial.

As a side effect, the `myvenv` can be removed from `.gitignore`.

**Comment by aniav** [comment]
@pts feel free to create a pull request with these changes :)

**Comment by fltfx** [comment]
current version  shows:
```
$ git add .
$ git commit -m "My Django Girls app, first commit"
```

closing this
