### ISSUE TITLE
storing and remembering passwords

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1029]
Pariticipants need to remember at least 4 passwords during the workshop: local computer password, e-mail password, GitHub password, PythonAnywhere password. (Maybe also the Slack password.)

It has happened to a participant that they forgot some of these passwords, and recovery was a nuisance and caused 30 minutes of delay for them. (Recovery e-mails were extremely slow to arrive.)

To fix this my recommendation is adding some steps near the beginning of https://tutorial.djangogirls.org/en/installation/, like this: If you already use a password manager or password vault, add your new passwords (including the GitHub and PythonAnywhere user password and PythonAnywhere password) there, because you'll need to type them several times during the workshop. If you aren't using a password manager yet, we recommend installing and trying X. Alternatively, you can have the usernames and passwords in on a post-it in your purse.

(Maybe the idea about the post-it in the purse isn't secure in general, feel free to improve it.)

**Comment by aniav** [comment]
I am a fan of making it clear that the passwords should be remembered and that they will be used multiple times during and after the workshops, I am not a fan of adding yet another new thing to learn for the participants. They are already flooded with new things to install and remember in the tutorial at the level of complexity it has.

**Comment by jhodgdon-drp** [comment]
It looks like the only two passwords that they would need to remember that are specific to this workshop are the GitHub and PythonAnywhere password. Maybe it would be enough to just add a note to both of those installation sections to remember the password? I'll make a proposed PR.

**Comment by ekohl** [comment]
I think #1330 resolves this now. Thanks!
