### ISSUE TITLE
error in tutorial

### ISSUE THREAD

**Issue by Dacastror** [DjangoGirls/tutorial#1044]
Hi, I found an error in the tutorial https://tutorial.djangogirls.org/es/extend_your_application/#
(Spanish version) in the "URL" section, says:

`url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail),`

But the correct form is:

`url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'), `

Also in the "Crea un enlace en la plantilla" section says:

`<h1><a href="{% url 'blog.views.post_detail' pk=post.pk %}">{{ post.title }}</a></h1>`

When should it be

`<h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>`

I hope to modify this, it was a headache for me, the English version is correct.
thanks for your attention.

**Comment by Dacastror** [comment]
Continuing with the tutorial in Spanish, I notice that the previously mentioned errors propagate to the pages that follow.
I found another error on https://tutorial.djangogirls.org/es/django_forms/
In the "Enlace a una página con el formulario" section appears

`<a href="{% url 'blog.views.post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>`

the correct is

`<a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>`

I hope it can be corrected.

**Comment by ekohl** [comment]
It's real easy to fix this yourself given you already know the correct solution. You can edit https://github.com/DjangoGirls/tutorial/blob/master/es/extend_your_application/README.md and https://github.com/DjangoGirls/tutorial/blob/master/es/django_forms/README.md. It's even possible to do this through the github UI. Then submit a pull request and then you wait for a review + merge.

**Comment by Dacastror** [comment]
I have done what you suggested, thank you very much for your response

**Comment by ekohl** [comment]
It looks like you did make the changes but still need to create a pull request. You can go to your [branches](https://github.com/Dacastror/tutorial/branches) and when open ```compare``` there's a big green ```Create pull request``` button. That will notify repository admins.

**Comment by aniav** [comment]
@Dacastror thank you, I have used changes from your branches to implement this fix 🎉
