### ISSUE TITLE
Css section

### ISSUE THREAD

**Issue by jonnyfrez81** [DjangoGirls/tutorial#1047]
Hi I'm learning Django and found your site. I'm loving it!
I'm wondering about the:

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

What does it really do?
I thougth that this line  tells Django where to start to search for files in this project? I was expecting this row 
to find the static/css/blog.css file. But in my case it didn't do it.

After reading about it in the web i found that this is the codeline that helped Django to find the Css file:

STATICFILES_DIRS = ( os.path.join('static'), )

So my question is. What does this line of code do?
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

**Comment by ekohl** [comment]
I tried this and I don't think it's correct. In the console you see ```django.core.exceptions.ImproperlyConfigured: The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting```.

It's supposed to work without it. My suspicion is that changing the config triggered a server restart and that Django had a cache that was then flushed.

```STATIC_ROOT``` is described in https://docs.djangoproject.com/en/1.10/howto/static-files/#deployment

**Comment by aniav** [comment]
Hey @jonnyfrez81,
the `STATIC_ROOT` setting tells Django where to collect static files from other directories. It's useful mostly when you use a different server for static files. `STATICFILES_DIRS` is a list of directories where Django will look for static files to copy them to `STATIC_ROOT`. 

I hope you managed to handle that by now as I am replying after a long time. I am sorry about that! 🙏 

I will close this issue for now as it's not really an issue in the tutorial. If you have any questions regarding Django when using the tutorial I highly recommend asking those in our [gitter channel](gitter.im/DjangoGirls/tutorial).

Hug fives and cupcakes! 🍰
