### ISSUE TITLE
Screen real estate instructions missing

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1054]
Many participants arrive to the Django Girls workshop with a laptop with very low screen resolution (e.g. 1280x768), and it's very inconvenient and frustrating for them to keep manually scrolling left-right and up-down for navigation.

One way to solve this problem is to reduce the amount of whitespace in the tutorial's CSS (or make it configurable). I'll file a separate issue for that.

My recommendation is extending the tutorial about using the screen efficiently, with recommendations like this:

1. Click on the gray `---` icon at the top left corner of the web page to hide the navigation menu.

2. Use the gray `A` icon and then the small `A` link at the top left corner of the page to make the font size smaller so that more text fits on your the screen.

3. Feel free to make your browser window showing the tutorial narrower, the tutorial will adjust to it.

**Comment by das-g** [comment]
For the English version, can you check whether #1495 (now live on https://tutorial.djangogirls.org/en/) resolved this?

**Comment by pts** [comment]
#1495 is a great improvement, but it doesn't directly address this issue: providing explicit hints on how to use small screens more efficiently.
