### ISSUE TITLE
Navigation within the tutorial is confusing

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1055]
It's quite confusing for many participants to reliably navigate to the next page of the tutorial. The `<` and `>` buttons are not prominent enough on screen, and they don't have a fixed location (they move around when the window width is changed).

My recommendation is adding explicit *Previous page* and *Next page* text links to the top and bottom of the page with a prominent color (e.g. blue).

My additional recommendation is adding this to the tutorial: Use the right arrow key to navigate to the next page of the tutorial, and the left arrow key for the previous page.

**Comment by das-g** [comment]
#1495 didn't add additional links, but labeled them with text and improved their placement on small screens. (The color remained unchanged, though, as far as I can tell.)

Can you check, whether that satisfactorily resolves this issue?

**Comment by pts** [comment]
Works like a charm, thanks!
