### ISSUE TITLE
Dropdown titles occupy too much space

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1058]
The vertical whitespace occupied by the system-specific dropdown (e.g. *Windows*) headers is too much. On a small screen (1280x768), sometimes the entire useful area of the web page is occupied by these dropdowns, taking up valuable space from the useful information above and below.

My recommendation: Remove most of the vertical whitespace, and make the (closed) drop-downs vertically much smaller: make them 20% of their current height, removing 80%.

**Comment by aniav** [comment]
This is now fixed :)
