### ISSUE TITLE
Typing ASCII symbols ~ and # on the Mac with German layout

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1059]
Many participants struggled with typing ASCII symbols `~` and `#` on their MacBook, which had a German keyboard layout. Some of the keys worked in the browser, others worked in Gedit, others worked in the pythonanywhere.com Bash console. For example, Alt-*3* worked for `#` in only one of these (I forgot which).

My recommendation: A Mac user with a German keyboard layout should take this issue, and extend the tutorial with specific recommendations on typing `~` and `#` in various environments on the Mac with a German keyboard layout.

I wasn't able to reproduce the problem on Linux (Ubuntu 14.04) with a German keyboard layout: all keys (including ASCII punctuation and accented letters) worked as indicated in Chrome, Gedit and pythonanywhere.com Bash console (in Chrome).

**Comment by aniav** [comment]
I hope this was resolved in the German translation. I will close that for now, but feel free to reopen if the German translation wouldn't help. Thanks! 👍

**Comment by aniav** [comment]
Ok, it seems it's a problem with PythonAnywhere maybe? Look at #859
