### ISSUE TITLE
[German] Translation of program names on Windows

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1061]
Many participants arrive to the workshop with a Windows localized to a non-English language (typically: German, French and Spanish). The tutorial contains only the English names of some of the Windows programs (such as *Accessories* and *Command Prompt*), and the participants struggle and get frustrated when they are not able to find the programs.

Please translate some of the localized names for these programs in the tutorial, or add a link to a web page containing the localized names.

Some directories (e.g. *Documents*) also have different names, it may be worth mentioning this in the tutorial.

**Comment by aniav** [comment]
I am closing that as now we have German translation and I hope this is resolved 🎉
