### ISSUE TITLE
Add @never_cache to all views

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1062]
A participant has reported that her Django app works on localhost, but not on pythonanywhere.com. The difference was that on djangogirls.com after deleting a post from the blog, the post still shows up on the main page until the main page is explicitly reloaded in the browser.

I was curious and tracked down the reason for this. There was a mandatory caching HTTP proxy (installed by the university where the Django Girls event took place) between the web browser and pythonanywhere.com. This proxy has cached the main page, and served its contents to the web browser from its cache, without consulting the Django app on pythonanywhere.com. When reloading the page the proxy has discarded its cached version and did consult the Django app, so the up-to-date post listing become visible.

To prevent this undesired caching behavior, the `@never_cache` decorator has to be added to all Django views. (I've verified that this indeed solved the problem for that particular proxy.) Like this: https://docs.djangoproject.com/en/1.11/topics/http/decorators/#django.views.decorators.cache.never_cache

My recommendation: Extend the tutorial with `@never_cache` lines above all view definitions, and possibly explain what they do.

**Comment by ekohl** [comment]
I understand that this can be a problem, but it sounds like a misconfigured proxy and this will lead to teaching web developers the wrong solution. IMHO the university should fix their misbehaving proxy and not assume something is cachable. I'd expect a lot of websites will misbehave with that proxy because nobody develops everything with ```@never_cache```.

**Comment by pts** [comment]
For me it doesn't sound like a wrong solution which makes the web page behave as expected even when there are misbehaving proxies beyond the web site developer's control. In the real world of web, there are many misbehaving components, and it's common practice to implement workarounds.

Teaching about the tradeoffs of getting someone else fix their broken stuff properly versus implementing a quick workaround can also be a useful topic of the tutorial.

FYI Looking at the HTTP RFC (https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.4), I don't think the proxy is misbehaving in this case, because the RFC says it *MAY* do what it does.

**Comment by ekohl** [comment]
You're correct that what it does is allowed so now it gets tricky. Mentioning all the potential problems is difficult and may confuse beginners. I wonder if there should be a mentors guide that mentions this.

**Comment by pts** [comment]
I stand by my original recommendation: Extend the tutorial with @never_cache lines above all view definitions, and possibly explain what they do.

**Comment by ekohl** [comment]
I'll leave it up to the repo members to make a decision since I can't make one as a contributor.

**Comment by aniav** [comment]
I am with @ekohl on this one. There are a few arguments behind not adding `@never_cache` to the tutorial.
1. This is additional knowledge we would have to pass to the students. We would have to tell them what is cache, what is a decorator, what is never_cache and it's alternatives, why is this required and where it is not required.
2. This is not a good pattern to use in regular apps, and I am highly against adding something that is normally not used. This would be passed by the students to regular apps not really understanding why. This will cause more problems comparing to the added value.
3. We already have signs the tutorial is too long, we don't want to add anything which would make it significantly longer, and this would.

I know you had to put a lot of effort to track this down but there are many different aspects of adding things to the tutorial we have to deal with. Hugs! 🙌
