### ISSUE TITLE
Chromebook - Code editor step could mention cloud9 as the editor

### ISSUE THREAD

**Issue by no1joel** [DjangoGirls/tutorial#1073]
It can be a bit confusing when the attendee gets to this part and it just tells them to skip it.
Maybe the tutorial could inform them that cloud9 has an editor?

**Comment by nathanielksmith** [comment]
I can update this.

**Comment by aniav** [comment]
Go ahead @vilmibm :)

**Comment by jhodgdon-drp** [comment]
The PR there is about using CodeAnywhere instead of Cloud9, and it doesn't actually fix this issue, which is that tutorial readers and workshop attendees using ChromeBooks are confused about how to open the code editor.

**Comment by jhodgdon-drp** [comment]
The PR for using CodeAnywhere has been closed (due to CodeAnywhere changing their policies for free accounts), so we need another PR here to fix this issue. I'll make an edit now...
