### ISSUE TITLE
Chromebook - cloud9 django admin step

### ISSUE THREAD

**Issue by no1joel** [DjangoGirls/tutorial#1075]
In the [Django admin](https://tutorial.djangogirls.org/en/django_admin/) section there's a bit about going to the /admin that tells the attendee to go to http://127.0.0.1:8000/admin/ , this should probably mention that if you're on a chromebook you should go to your cloud9 address + '/admin'.

**Comment by nathanielksmith** [comment]
I'm updating the Chromebook tutorial this week in advance of the Portland, OR workshop next weekend and can clarify this.

**Comment by aniav** [comment]
Go ahead @vilmibm :)

**Comment by thibaudcolas** [comment]
Just ran into this today as well. 

It's also in some other steps:

- https://tutorial.djangogirls.org/en/django_urls/#your-first-django-url ("Django will now redirect everything that comes into 'http://127.0.0.1:8000/' to blog.urls and look for further instructions there.")
- https://tutorial.djangogirls.org/en/django_views/#blogviewspy ("Save the file, go to http://127.0.0.1:8000/ and see what we've got.")
