### ISSUE TITLE
translator

### ISSUE THREAD

**Issue by Olive4701** [DjangoGirls/tutorial#1087]
this website needs an Igbo translator because a lot of people in Nigeria needs a someone who can help them with computer and Django would be a good thing to teach girls because girls in Nigeria are3 not expected to look for jobs in the computer science area.

**Comment by RachellCalhoun** [comment]
Hi! If you'd like to get the tutorial translated into Igbo, we would love for you to help! Please email translations@djangogirls.org to help start translating the tutorial.

**Comment by Olive4701** [comment]
Hi rachell i would like to know why this comment is closed

**Comment by RachellCalhoun** [comment]
It's because we use another service for translating. I'll send an email with more information.
