### ISSUE TITLE
translate django girl tut to Vietnamese

### ISSUE THREAD

**Issue by khanhnnvn** [DjangoGirls/tutorial#1090]
Hi you, 
I am Khanh from Python Viet nam. Python Viet Nam community have some chanel 
Facebook Page: https://www.facebook.com/pythonvietnam
Facebook Group: https://www.facebook.com/groups/pythonvn/
Forum: http://pycon.vn
We want translate tutorial django of django girl for my members in Viet Nam.
I hope you accept and help us take care this project of community
Thanks for reading.
Khanh Nguyen Ngoc
Email: khanhnn@pythonvietnam.info
Skype: khanhnnvn

**Comment by RachellCalhoun** [comment]
Hi Khanh, 

I will send you some more info via translations@djangogirls.org email about how to get started translating.
