### ISSUE TITLE
Hausa

### ISSUE THREAD

**Issue by mahmudonline** [DjangoGirls/tutorial#1095]
Wikipedia: Hausa (/ˈhaʊsə/)[3] (Yaren Hausa or Harshen Hausa) is the Chadic language (a branch of the Afroasiatic language family) with the largest number of speakers, spoken as a first language by at least 30 million people, and as a second language by another 20 million or more.[1] Originally the language of the Hausa people stretching across southern Niger and northern Nigeria, it has developed into a lingua franca across much of western Africa for purposes of trade. In the 20th and 21st centuries, it has become more commonly published in print and online.

**Comment by aniav** [comment]
I have added the Hausa language to Crowdin :)

**Comment by mahmudonline** [comment]
Thank you. Will work on it

Sent from my BlackBerry - the most secure mobile device
