### ISSUE TITLE
Error in spanish tutorial: "NoReverseMatch at /post/new/" - Error in translation.

### ISSUE THREAD

**Issue by jheredia** [DjangoGirls/tutorial#1099]
I was following every step in the spanish tutorial up [until](https://tutorial.djangogirls.org/es/django_forms/#guardar-el-formulario) when I had this issue.

It seems that this code:
```
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.post_list),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail),
    url(r'^post/new/$', views.post_new, name='post_new'),
] 
```

where the attribute `name='post_new'` is given only to the new URL causes this:

![Error caused](https://user-images.githubusercontent.com/3941955/29910618-fb1d2b94-8e00-11e7-9e4e-e819e12dc2d0.png)

changing the `urls.py` code to:

```
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_name'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
]
```
seems to fix the problem and redirect correctly to the newly created post.

I think that it is an error in the translation from english to spanish.
 
Here is the [english tutorial version](https://tutorial.djangogirls.org/en/django_forms/#url)
![english version](https://user-images.githubusercontent.com/3941955/29910850-f3aff160-8e01-11e7-901d-3edefb86c57a.png)

And here the [spanish one](https://tutorial.djangogirls.org/es/django_forms/#url):
![spanish version](https://user-images.githubusercontent.com/3941955/29910851-f3d21fec-8e01-11e7-9a32-61c21c145132.png)

Maybe I'm mistaken or it is not so much of an issue but I think that it is worth to look at.

**Comment by aniav** [comment]
This has been fixed. Closing the issue 🥇
