### ISSUE TITLE
Old Python version (3.4.3) for windows in French Version

### ISSUE THREAD

**Issue by cedricvanrompay** [DjangoGirls/tutorial#1107]
Location: https://github.com/DjangoGirls/tutorial/blob/master/fr/python_installation/instructions.md#windows

The english version has text and screenshot for version 3.6.

Need help updating? (I'm French)

**Comment by magul** [comment]
HI @cedricvanrompay, for now we track translations on Crowdin, and as You can see French is really behing our English/source version: https://crowdin.com/project/django-girls-tutorial/fr#

If You would like to help, the best way would be to translate it there.

**Comment by cedricvanrompay** [comment]
Thanks, started helping with the translation on crowdin !
