### ISSUE TITLE
Unable to install correct version combination for current plugin set

### ISSUE THREAD

**Issue by rix0rrr** [DjangoGirls/tutorial#1114]
### Issue description

I'm newly downloading this tutorial and trying to build it, and it's a pain trying to install the correct combinations of gitbook and the various plugins to get everything to build.

Nevermind that `gitbook install` will refuse to install the required versions of plugins without giving  useful error messages, after `npm install`ing the requirements manually and then trying to build, a seemingly impossible version conflict arises:

Example:

    $ cat book.json
    ...
        "ga@2.0.0",
    ... 
    
    $ gitbook -v 3.2.3 build
    ...
    info: loading plugin "ga"... ERROR
    Error: GitBook doesn't satisfy the requirements of this plugin: >=4.0.0-alpha.0

Okay, apparently we need a gitbook alpha release. Would be nice if that were mentioned somewhere. `4.0.0-alpha.0` does not exist, so let's try `4.0.0-alpha.1`.

    $ gitbook -v  4.0.0-alpha.1 build
    ...
    info: loading plugin "codeblock-label"... ERROR
    
    Error: GitBook doesn't satisfy the requirements of this plugin: 3.*

So, `ga` seems to require gitbook >= 4, but `codeblock-label` requires gitbook == 3.

What's the combination of versions I'm supposed to be using?

### Language

Not related to any language.

### Operating system

Tried on Mac OS X. Should be similar elsewhere.

**Comment by aniav** [comment]
@rix0rrr I will check it on a clean gitbook state, I have built this on my local machine and it didn't fail to build on the server so I assumed everything is fine. Thanks for letting us know!

**Comment by aniav** [comment]
@rix0rrr it should be ok now :)
