### ISSUE TITLE
Translation to Amharic Language 

### ISSUE THREAD

**Issue by habbyt** [DjangoGirls/tutorial#1129]
### Translation to Amharic Language
I check the tutorial language lists and noticed that Amharic is NOT there. 

### Amharic
I would like to know if there is any work in progress translating to Amharic . I'd be happy to help.

**Comment by aniav** [comment]
There is currently no work being done on `Amharic` language. I have activated it on [Crowdin](https://crowdin.com/project/django-girls-tutorial), feel free to work on it :)
