### ISSUE TITLE
each `git push` displays a harmless but long message

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1153]
### Issue description

On some systems each invocation `git push` displays the following harmless but long message:

```
$ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)
```

My suggestion: Extend the tutorial like this: If you see the message above, run `git config --global push.default simple`, and you will never see it again.

### Language

All languages.

### Operating system

All operating systems. Happened on macOS yesterday.

**Comment by animenon** [comment]
@pts This is not a DjangoGirls Issue, this happens when git is not configured on your system.

Read: [Git Configuration](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)

**Comment by pts** [comment]
It's a DjangoGirls issue, because a participant was following the DjangoGirls tutorial, installing Git etc., and got this unexpected and long message every time she made a `git push`.

**Comment by animenon** [comment]
This issue is because git `push.default` is not set. The user hasn't specified a branch to which changes are to be pushed, so git uses the `push.default` to push changes.
I shall go over the tutorial once.

**Comment by animenon** [comment]
@pts could you point me to the tutorial page where this issue is faced.

**Comment by ekohl** [comment]
@pts it happens on older git versions. As you can see you're still on a 1.x version while 2.0 was released in 2014. The tutorial advises users to download a version at the start so I'd expect students wouldn't see this that unless they already had an old version installed and skipped downloading a newer version.

**Comment by ekohl** [comment]
I'm leaning to closing this given it's only on old git versions.

**Comment by ekohl** [comment]
Per my previous message I'm closing this.
