### ISSUE TITLE
Deploy - virtualenv --python=python3.6 myvenv gives permission denied error

### ISSUE THREAD

**Issue by adityarao310** [DjangoGirls/tutorial#1156]
### Issue description

While creating a virtual env in pythonanywhere it gives an error if you type $ virtualenv --python=python3.6 myvenv
but works if I do $ virtualenv --python=python3.6 venv

The complete error is:
```
Running virtualenv with interpreter /home/adityarao310/.local/bin/python3
Using base prefix '/usr'
New python executable in /home/adityarao310/blogging-platform/myvenv/bin/python3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1231, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python3.6/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/adityarao310/blogging-platform/myvenv/bin/python3'
```

### Operating system

macosx

**Comment by ekohl** [comment]
Can you show the output of ```ls -l /home/adityarao310/blogging-platform/myvenv /home/adityarao310/blogging-platform/myvenv/bin```?

As a side note: you can use the insert code when pasting output from commands. It uses a monospace font and preserves whitespace.

**Comment by hjwp** [comment]
Hi there, we've made some changes to the deployment chapter that means the user no longer has to create a virtualenv manually.  Closing this for now, do re-open if you come across problems with the new procedure?
