### ISSUE TITLE
It's appears not obvious that this is not an instructor led tutorial (for in-person workshops)

### ISSUE THREAD

**Issue by nikbora** [DjangoGirls/tutorial#1158]
I had 3 attendees in my DjangoGirls group say that they thought this was a live workshop, where someone would be "going through the tutorial on the screen" and they follow. Does this ever happen? If not I may do a PR to make this a bit more obvious in the introduction.

**Comment by thibaudcolas** [comment]
I have seen this happen (especially when the organisation is low on coaches), but I don't think it's common / recommended.

As to making this more obvious – should this be addressed on the event's site, or on the tutorial?

**Comment by nikbora** [comment]
I guess event organisation manual should have something about highlighting this to attendees before they come. I will have a look at that instead.

**Comment by jhodgdon-drp** [comment]
It looks like we could probably close this issue, since it's more about event publicity than about the tutorial text?

**Comment by ekohl** [comment]
Sounds fair. Closing this but if other organizers run into this, please let us know here. We can see how to fix it from there on out.
