### ISSUE TITLE
Images don't load in English tutorial site

### ISSUE THREAD

**Issue by animenon** [DjangoGirls/tutorial#1160]
### Issue description
The images start loading but later get replaced by text.
![image](https://user-images.githubusercontent.com/6907950/32137532-5d2c6cd4-bc3f-11e7-91cf-5f1e89b9be09.png)

**After the above state the page hides the image, to look like:**
![image](https://user-images.githubusercontent.com/6907950/32137542-8ded4384-bc3f-11e7-892f-07dff10a381f.png)

### Language
Its related to [English site](https://tutorial.djangogirls.org/en/how_the_internet_works/), I don't see it in "https://tutorial.djangogirls.org/tr/how_the_internet_works/"

### Operating system

What operating system does this issue relate to?
Windows 10, using Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by ekohl** [comment]
I can't reproduce this. Could this have been a temporary network issue?

**Comment by animenon** [comment]
@ekohl Am also not able to reproduce it anymore, might have been something due to network/cookies ..

**Comment by ekohl** [comment]
Thanks for checking :)
