### ISSUE TITLE
Japanese Translation of the tutorial

### ISSUE THREAD

**Issue by souravsingh** [DjangoGirls/tutorial#1170]
The Japanese translation of the tutorial is available here-
 https://djangogirlsjapan.gitbooks.io/workshop_tutorialjp/

Should we ask the tutorial translator to add the translated tutorial here?

**Comment by magul** [comment]
Yes, that will be great, but the greatest thing, that she/he will do is to upload translation into Crowding here: https://crowdin.com/project/django-girls-tutorial/ja#

**Comment by souravsingh** [comment]
I am not sure if he/she would be willing to upload the translation to Crowdin, since it would be a duplicate effort.
