### ISSUE TITLE
post_list view code doesn't match up between view lessons in English translation

### ISSUE THREAD

**Issue by tothebeat** [DjangoGirls/tutorial#1179]
### Issue description

In the [first introduction of creating the post_list view](https://github.com/DjangoGirls/tutorial/blame/master/en/django_views/README.md#L28-L29), the code is as follows: 

```python
def post_list(request):
    return render(request, 'blog/post_list.html')
```

In the follow-up chapter on "Dynamic data in templates" that continues to develop this view, it incorrectly states the existing view code as being:

```python
def post_list(request):
    return render(request, 'blog/post_list.html', {})
```

The difference being that there's an empty dictionary supposedly passed as an argument here, which wasn't present in the first chapter. [Here's the location of that line](https://github.com/DjangoGirls/tutorial/blame/master/en/dynamic_data_in_templates/README.md#L16
).

### Language

This only affects the English translation. The original view code in [Spanish](https://github.com/DjangoGirls/tutorial/blame/master/es/django_views/README.md#L23), [Italian](https://github.com/DjangoGirls/tutorial/blame/master/it/django_views/README.md#L23), and [French](https://github.com/DjangoGirls/tutorial/blame/master/fr/django_views/README.md#L27) does have the dictionary. I checked other languages by cloning this repository and searching for `render(request, 'blog/post_list.html')` and finding it only in the English translation, while `render(request, 'blog/post_list.html', {})` is present in the same file for all other translations.

### Operating system

This is code related to all operating systems.

**Comment by ekohl** [comment]
With #1180 merged I think this has been fixed.
