### ISSUE TITLE
Translate DjangoGirls tutorial to Yoruba

### ISSUE THREAD

**Issue by shante66** [DjangoGirls/tutorial#1183]
### Issue description

Yoruba is one of the 3 major languages in Nigeria spoken majorly in the west. It is also spoken is some other WestAfrican countries. Can we add Yoruba as one of the available languages

**Comment by magul** [comment]
@shante66 Yoruba was added in Crowdin - https://crowdin.com/project/django-girls-tutorial/yo#

Do You want to work on it?

**Comment by magul** [comment]
Closing this one, as we can track progress on Crowdin.
