### ISSUE TITLE
Issue installing the latest version of git on OSX

### ISSUE THREAD

**Issue by thibaudcolas** [DjangoGirls/tutorial#1186]
### Issue description

We've had a few attendees (3/4, in different groups) having issues with the git install step on OSX. The issue seems to be https://github.com/timcharper/git_osx_installer/issues/100, or similar to it: when opening the DMG file, a cryptic "no mountable filesystem" error appears.

This is with the latest downloadable version (2.15.0). Installing the previous version (2.14.0) worked for us, available at https://www.kernel.org/pub/software/scm/git/ ("Older releases" link from the Git download page).

I'm not sure what can be done about this so I'm mainly opening this issue to see if other people have had this problem.

### Operating system

OSX – not sure which version(s), may be Mavericks or Yosemite.

**Comment by ekohl** [comment]
If anyone with a mac could see if this is still an issue that'd be great.

**Comment by ekohl** [comment]
Because there's been no update for almost a year I'm assuming it was just a bad release that has since been fixed.
