### ISSUE TITLE
CSS Changes between `css` tutorial and `extend_your_application`

### ISSUE THREAD

**Issue by MichaelClerx** [DjangoGirls/tutorial#1188]
At the end of https://tutorial.djangogirls.org/en/css/ there is an image showing the publication date aligned left

By https://tutorial.djangogirls.org/en/extend_your_application/ it has become right-aligned, and as far as I can see there's no bit in the tutorial telling you to make this change.
The next tutorial (https://tutorial.djangogirls.org/en/django_forms/) also has a right-aligned publication date (including the edit button)

**Comment by ekohl** [comment]
You're right. We could really use a round of fresh screenshots.

**Comment by realslimshanky** [comment]
I've raised a PR to fix this issue. Please review. cc: @MichaelClerx @ekohl
