### ISSUE TITLE
Security hardening on deployment (e.g. SECRET_KEY ends up on GitHub)

### ISSUE THREAD

**Issue by sbeaumont** [DjangoGirls/tutorial#1192]
### Issue description

I will soon be coaching the tutorial, and went through it myself to get to know it. I noticed that with the current steps there are some security issues like the SECRET_KEY ending up on GitHub.

Given the current importance of security it would be nice to have a section on these hardening steps. This can include:

- using SECRET_KEY = os.environ.get('SECRET_KEY') and set an environment variable on PythonAnywhere
- pointing at a production version of settings.py (settings-production.py?) which has the "hardened settings"
- explaining the importance of preventing passwords in code and on GitHub
- using python manage.py check --deploy to get a report on security issues
- setting DEBUG=FALSE on deployment in some fashion without having to do this locally
- turning on HTTPS by default (as asked for by check --deploy)

**Comment by ekohl** [comment]
IMHO it's already hard enough so we shouldn't requiring to do this manually. https://github.com/DjangoGirls/tutorial/pull/1190 would be a good starting place.

**Comment by sbeaumont** [comment]
Agree, and #1190 is indeed a better option. But if security would be a topic at some point these steps aren't that hard.

**Comment by sbeaumont** [comment]
I see this issue is a generalized copy of #802.

**Comment by hjwp** [comment]
closing in favour of https://github.com/DjangoGirls/tutorial-extensions/issues/101

**Comment by das-g** [comment]
Related: #1687
