### ISSUE TITLE
The tutorial does not explain the mysite.settings file that is needed on PythonAnywhere

### ISSUE THREAD

**Issue by sbeaumont** [DjangoGirls/tutorial#1195]
### Issue description

The tutorial refers to the line `os.environ['DJANGO_SETTINGS_MODULE'] = 'mysite.settings'` but does not explain that you need to create a file on PythonAnywhere called mysite.settings that has the `SECRET_KEY=<my unique secret key>` line in it.

Without this file you get this error:

`2018-01-21 14:39:10,456: Error running WSGI application
2018-01-21 14:39:10,457: django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2018-01-21 14:39:10,457:   File "/var/www/sbeaumont_pythonanywhere_com_wsgi.py", line 12, in <module>
2018-01-21 14:39:10,457:     application = StaticFilesHandler(get_wsgi_application())'

**Comment by hjwp** [comment]
Hi there, I can't reproduce this issue, can I ask you to check again?

(be aware the deploy chapter has changed as a result of #1190 )

If you share a link to your github repo for the tutorial, I can also check that it works against the new deploy procedure...

**Comment by hjwp** [comment]
(closing in the meantime, feel free to re-open if i've made a mistake)
