### ISSUE TITLE
Link official python documentation

### ISSUE THREAD

**Issue by lilithxxx** [DjangoGirls/tutorial#1196]
There is no mention of the official python documentation(-> https://docs.python.org/3/tutorial/ ) in this tutorial.
This is mainly required in https://tutorial.djangogirls.org/en/python_introduction/

**Comment by ekohl** [comment]
The source is at https://github.com/DjangoGirls/tutorial/blob/master/en/python_introduction/README.md and a PR would be highly appreciated :)
