### ISSUE TITLE
Translate Django Girls tutorial to Greek

### ISSUE THREAD

**Issue by Belonias** [DjangoGirls/tutorial#1204]
### Issue description

I would like to translate Django Girls tutorial to Greek

**Comment by magul** [comment]
Great! Actually we already have Greek translation in progres (28% translated). You can participate in it here: https://crowdin.com/project/django-girls-tutorial/el#

Just login there with Github account and join this project.

**Comment by Belonias** [comment]
Thank you @magul

**Comment by magul** [comment]
You’re welcome!
