### ISSUE TITLE
Missing in deployment part - pythonanywhere

### ISSUE THREAD

**Issue by pssukhwani** [DjangoGirls/tutorial#1209]
After "Setting the virtualenv" and done all the steps to clone the repo and create the appropriate database and migrations we still need to define the following things in order to avoid Internal server error issues:

### In Code:
- Source code, Working directory, WSGI configuration file and Python version
### In Static files:
- Static files URL for admin and actual content
- media URL
- if anyone is using images from a static directory then we need to define that also separately.

### Language
Python

Is this related to a specific language of the tutorial?
Yes

**Comment by magul** [comment]
Are You aware of #1190? Can You confirm, that it's resolved there?

**Comment by pssukhwani** [comment]
Interesting!! A few months back, I spent almost an hour on the configuration part while I was deploying the [website](https://pssukhwani.pythonanywhere.com/home) on pythonanywhere for the first time.

Thanks for the update and yes it's a good solution.
