### ISSUE TITLE
Python 3.6 unavailable for Ubuntu 16.04 LTS by default

### ISSUE THREAD

**Issue by ThomasWo** [DjangoGirls/tutorial#1222]
### Issue description
On https://tutorial.djangogirls.org/en/python_installation/ , it asks to install Python 3.6, but Python 3.6 isn't available in the default apt-get repos for Ubuntu 16.04 LTS without adding a PPA.

Instructions to add said PPA is here: https://www.rosehosting.com/blog/how-to-install-python-3-6-on-ubuntu-16-04/

Might I recommend add some language around detecting the version of Ubuntu and branching off accordingly?

Note: Python 3.6 _is_ available for installation in apt-get for Ubuntu 17.10, so if they're using the latest version, that will work out of the box.

### Language
Found in English, haven't looked elsewhere.

### Operating system
Ubuntu 16.04 LTS

**Comment by sevu** [comment]
I guess the tutorial works with python 3.5 as well. The command should mention `python3` instead `python3.6`.

**Comment by ekohl** [comment]
@sevu I think it's a good thing to use ```python3``` since we can pretty much assume it works in the various python minor versions.

**Comment by saschalalala** [comment]
The same issue exists for the latest Debian. Debian 9.4 ships Python 3.5.3. So when letting users install their system's python one has to be aware that e.g. f-strings where only introduced with Python 3.6 :/

**Comment by jhodgdon-drp** [comment]
That pull request should take care of this issue, plus #1259.

**Comment by jhodgdon-drp** [comment]
I closed the earlier pull request and substituted this new one, which should take care of 3 related issues.
