### ISSUE TITLE
Had to add 'blog' namespace in html and views.py in order for functions to be recognised

### ISSUE THREAD

**Issue by sesutton** [DjangoGirls/tutorial#1244]
### Issue description
Where ever function was used in 'url()' in .html and redirect within views I had to prefix with 'blog:' in or I would receive the error 'NoReverseMatch: Reverse for '{function}' not found. '{function}' is not a valid view function or pattern name.'

This may have been due to the existence of another app within the project or due the the fact I was using python 2.7 (unlikely)

### Language

Python 2.7
Django 1.11

### Operating system

What operating system does this issue relate to?
Linux Fedora 27

Also thank you for the awesome tutorial! Learnt a lot from going through it!

**Comment by magul** [comment]
Hi @sesutton, can You provide source code to recreate this situation?

**Comment by sesutton** [comment]
Hi @magul, I've attached the 'as per' the tutorial (up to https://tutorial.djangogirls.org/en/extend_your_application/).

At this point when I run the server I would get the follow error:
NoReverseMatch at /
Reverse for 'post_detail' not found. 'post_detail' is not a valid view function or pattern name.

I've also attached the 'fixed' code. 
The only difference at this stage being in 'blog/template/blog/post_detail.html' at line 9.

I changed:
<h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
To:
<h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
    
[fixed.zip](https://github.com/DjangoGirls/tutorial/files/1802237/fixed.zip)
[tutorial.zip](https://github.com/DjangoGirls/tutorial/files/1802238/tutorial.zip)

In order to run the code in the same environment:
Install anaconda
conda create -n django anaconda
source activate django
pip install django

In order to run server:
extract fixed or tutorial zips
change directory to extracted_dir/ellie-website/ellieblog
source activate django (if not already active)
python manage.py runserver

If you go further in the tutorial there are more occurrences of {% url ... %} that need to be changed in order to not have the issue repeat!

Django Version: 1.11.11
Python Version: 2.7.14

You shouldn't need to access the admin in order to recreate the problem but if you do wish to you can either add a new superuser or use the uname and pw combo 'sesutton' and 'password12345' respectively.

If you need anything else please don't hesitate to ask!

**Comment by ekohl** [comment]
@sesutton you also added ```app_name = 'blog'``` to your ```blog/urls.py``` which enables URL namespaces. Could you try and leave that out and match the tutorial?

On a side note I do like the namespacing and I didn't know Django could do it this easily nowadays, but the tutorial doesn't do it right now.

**Comment by sesutton** [comment]
That fixed it! I guess that's what happens when you don't strictly follow the instructions!
