### ISSUE TITLE
English instructions for installation on Chromebook need update

### ISSUE THREAD

**Issue by magul** [DjangoGirls/tutorial#1248]
### Issue description

I don't have a Chromebook, but I tried to follow along on the Cloud 9 experience.
Seems to me that after the original text was written, Cloud 9 was acquired by Amazon.
Signing up with AWS is not so funny, eh straightforward (unless maybe the Express procedure is followed using the ill-advised root user account).
So the creation of a workspace became creation of an environment.
'sudo apt' is now 'sudo yum'
The python3 interpreter is available, so no need to use the system package manager to install python3.6-venv?
'pip install --upgrade pip' is missing
'python3.6 -mvenv myvenv' (note the typo) can now become 'python3 -m venv myvenv'

(originally described on Crowdin: https://crowdin.com/project/django-girls-tutorial/discussions/96 by @rogererens)

### Language

all

### Operating system

Chromebook/Cloud9

**Comment by rogererens** [comment]
I only found out now about this issue tracker.
I guess this issue should be closes and link to
[issue 1081](https://github.com/DjangoGirls/tutorial/issues/1081)

**Comment by magul** [comment]
Closing that one as duplicate of #1081 per original author request.
