### ISSUE TITLE
post.publish() instead of Post.publish()

### ISSUE THREAD

**Issue by Raghav17** [DjangoGirls/tutorial#1253]
In the page: https://tutorial.djangogirls.org/en/django_orm/
A command line under the publish method it is mentioned post.publish() instead of Post.publish().

**Comment by magul** [comment]
@Raghav17 - I will close this one, as `publish` method need to be executed in `Post` instance context. In this particular chapter one code block above You have:
```
post = Post.objects.get(title="Sample title")
```
and then:
```
post.publish()
```
so `publish` is resposoble for publishing this post, that we got line above.
