### ISSUE TITLE
Mistake in Russian translation

### ISSUE THREAD

**Issue by vovoka** [DjangoGirls/tutorial#1260]
Mistake in translation:
[original:](https://tutorial.djangogirls.org/en/extend_your_application/)

> The `post_detail `part means that Django will be expecting a URL in `blog/urls.py` with `name=post_detail`

[translated as ](https://tutorial.djangogirls.org/ru/extend_your_application/#)
> Параметр `post_urls` означает, что Django будет искать URL с именем `post_detail` в файле `blog.urls.py.`

Should begin with
> Параметр `post_detail` означает...

**Comment by magul** [comment]
Hi @vovoka,

It would be great, if You could open pull request to resolve this issue (see: https://github.com/DjangoGirls/tutorial#making-a-pull-request) and add this fix to our Crowdin project here: https://crowdin.com/project/django-girls-tutorial/ru#

**Comment by magul** [comment]
Of course feel welcomed to jump also into other parts of Russian translation on Crowdin!
