### ISSUE TITLE
Tutorial incompatible with Python 3.7 because of Django 1.11

### ISSUE THREAD

**Issue by ekohl** [DjangoGirls/tutorial#1266]
### Issue description

Django 1.11 is incompatible with Python 3.7. The solution is to upgrade the tutorial to Django 2.0.

### Language

All languages that use 1.11 or older

### Operating system

All with Python 3.7. Since we advise users to download from python.org on multiple, they are affected.

**Comment by das-g** [comment]
There's now a PR that changes the tutorial to Django 2.0: #1282

**Comment by das-g** [comment]
Does #1282 also fix [SyntaxError: Generator expression must be parenthezised / python manage.py migrate](https://stackoverflow.com/q/48822571/674064) on Python 3.7?

**Comment by magul** [comment]
It should fix that one: https://github.com/django/django/commit/931c60c5216bd71bc11f489e00e063331cf21f40

and this change is on Django 2.0.x: https://github.com/django/django/blob/stable/2.0.x/django/contrib/admin/widgets.py#L166
