### ISSUE TITLE
urls.py example missing an import

### ISSUE THREAD

**Issue by cdw9** [DjangoGirls/tutorial#1305]
### Issue description

https://tutorial.djangogirls.org/en/extend_your_application/#create-a-url-to-a-posts-detail has code for blog/urls.py, but it is missing: `from django.urls import path`

### Language

Noticed on English and Spanish, did not check others

**Comment by kaizumaki** [comment]
I think the same way.
#1318 
I have created a pull request.

**Comment by magul** [comment]
Closed in #1318
