### ISSUE TITLE
Put requirements.txt under git control

### ISSUE THREAD

**Issue by kaizumaki** [DjangoGirls/tutorial#1308]
### Issue description

In the tutorial we will install Django using requirements.txt.
However, in the chapter of the "deploy", the requirements.txt is not included in the result of the `git status` command.
I think that it is better to include requirements.txt in the result of `git status` command.
https://github.com/DjangoGirls/tutorial/blob/master/en/deploy/README.md

**Comment by das-g** [comment]
```bash
git add --all .
```
in [section "Starting our Git repository"](https://tutorial.djangogirls.org/en/deploy/#starting-our-git-repository) will already put `requirements.txt` under Git control, too. But you're right that the output of `git status` before that should be updated.

Same probably for the file listing [after creating the Django project](https://tutorial.djangogirls.org/en/django_start_project/#your-first-django-project). ([here](https://github.com/DjangoGirls/tutorial/blame/4d94db13303de9a50e02cd3660fa12fc01bff4eb/en/django_start_project/README.md#L52))

> ```
> djangogirls
> ├───manage.py
> └───mysite
>         settings.py
>         urls.py
>         wsgi.py
>         __init__.py
> ```

**Comment by kaizumaki** [comment]
@das-g Thank you for your response.
Is this command line like the one shown below?

> $ git status
> On branch master
> 
> Initial commit
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         .gitignore
>         blog/
>         manage.py
>         mysite/
> 
> nothing added to commit but untracked files present (use "git add" to track)

> $ git status
> On branch master
> 
> Initial commit
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         .gitignore
>         blog/
>         manage.py
>         mysite/
>         requirements.txt
> 
> nothing added to commit but untracked files present (use "git add" to track)

**Comment by das-g** [comment]
Well, the command line (=what you have to enter) is just
```bash
git status
```

`$` is used in the tutorial to indicate the prompt.

The rest, i.e.
 ```
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitignore
        blog/
        manage.py
        mysite/

nothing added to commit but untracked files present (use "git add" to track)
```
or with the `requirements.txt` file present
 ```
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitignore
        blog/
        manage.py
        mysite/
        requirements.txt

nothing added to commit but untracked files present (use "git add" to track)
```
is the output of the command. It lists what untracked files are present and would also list what tracked files are changed, if there were any.

```bash
git add --all .
```
is another command line. It tells Git to track all files in the current directory (denoted by `.`), unless they match a pattern in `.gitignore`. That are the same files as `git status` has shown us, as that command also honors `.gitignore`.

Is that what you meant? (I'm not sure whether I understood your question correctly.)

**Comment by kaizumaki** [comment]
@das-g I am sorry, my question was not very accurate.
Are you planning to fix the tutorial for adding the `requirements.txt` file?

**Comment by das-g** [comment]
> I am sorry, my question was not very accurate.

No problem. Did you get your answer, though?

> Are you planning to fix the tutorial for adding the requirements.txt file?

If nobody does it before I do, yes. Feel free to file a pull request, if you want. (I probably won't get around to it today.)

**Comment by kaizumaki** [comment]
#1309
