### ISSUE TITLE
[chapter Deploy!] output of `ls` contains files that have not been created yet

### ISSUE THREAD

**Issue by ftnext** [DjangoGirls/tutorial#1314]
### Issue description

In the chapter [Deploy!](https://tutorial.djangogirls.org/en/deploy/), there are files not yet created in the `blog` folder.
I write this issue because this seems not to be reported so far.

In the tutorial up to the chapter Deploy!, 
I think that the following file has not been created yet: 
* forms.py
* static (folder)
* templates (folder)
* urls.py

>PythonAnywhere command-line ([Deploy!](https://tutorial.djangogirls.org/en/deploy/) chapter)

```
(ola.pythonanywhere.com) $ ls
blog  db.sqlite3  manage.py  mysite requirements.txt static
(ola.pythonanywhere.com) $ ls blog/
__init__.py  __pycache__  admin.py  forms.py  migrations  models.py  static
templates  tests.py  urls.py  views.py
```

In my PythonAnywhere

```
(ftnext.pythonanywhere.com) 03:50 ~/ftnext.pythonanywhere.com (master)$ ls
blog db.sqlite3 manage.py mysite requirements.txt static
(ftnext.pythonanywhere.com) 03:50 ~/ftnext.pythonanywhere.com (master)$ ls blog/
__init__.py __pycache__ admin.py apps.py migrations models.py tests.py views.py
```

Here is my code: https://github.com/ftnext/my-first-blog/tree/6c4de89a91ffb87f456b82ac749456848a40faef/blog

I’m going to file a pull request about this issue.
Thank you.

**Comment by funkybob** [comment]
I was about to open this same issue, as it stumped myself and one of our attendees at DjangoGirls Melbourne today.

**Comment by ekohl** [comment]
I don't think there's a PR open for this but I'd happily review & merge it.

**Comment by ftnext** [comment]
@ekohl Please review my PR: https://github.com/DjangoGirls/tutorial/pull/1435

@funkybob Thank you for your comment.
