### ISSUE TITLE
Installation : Python version confusion -- install 3.6 specifically, or latest (3.7)?

### ISSUE THREAD

**Issue by jhodgdon-drp** [DjangoGirls/tutorial#1322]
### Issue description

In the Windows installation instructions, it tells you to install Python version 3.6.x. But it also tells you to install the "latest version", which is currently 3.7.x. It is not clear which one should be used -- will Django work with 3.7.x? Is it better to get the latest version?

If the tutorial is updated to say to install 3.7.x, by the way, the instructions about the PATH setting are somewhat wrong, as the installation setup dialog now says something about "environment variables' and not "PATH" specifically.

### Operating system

This probably applies to all operating systems, actually.

**Comment by jhodgdon-drp** [comment]
I went through the entire tutorial over the past few days with 3.7 and it seems to work fine.  Still not sure whether the tutorial should recommend 3.6 specifically or the latest version?

**Comment by magul** [comment]
I believe it was recommending Python 3.6 as latest version, but it always looked a little bit too restrictive to me. Django 2 support Python 3.4 - 3.7 so we should recoment latest, but be ok with anything above or equal 3.4.

**Comment by jhodgdon-drp** [comment]
OK, that is good information that should get into the tutorial. See also #1259 and #1222

**Comment by jhodgdon-drp** [comment]
This pull request should fix all 3 related issues.
