### ISSUE TITLE
Python Anywhere API key instructions are incorrect and image is missing

### ISSUE THREAD

**Issue by jhodgdon-drp** [DjangoGirls/tutorial#1323]
### Issue description

On the Installation page, it says I need to create an account on Python Anywhere. That worked OK.

Then it says I need to create an API key. The instructions say:

When you've signed up for PythonAnywhere, you'll be taken to your dashboard. Find the link near the top right to your "Accounts" page, then select the tab named "API token", and hit the button that says "Create new API token".

The link says "Account", not "Accounts".

Also, there is an image file on the page with an Alt text that says "The API token tab on the Accounts page" goes to
https://tutorial.djangogirls.org/en/installation/images/pythonanywhere_create_api_token.png
but that image is missing.

(Sorry if I'm making too many issues. I've signed up to be a Coach at an upcoming workshop in Spokane and I'm working through the tutorial, making issues as I go if things are incorrect. Hope that is OK! I will probably start making pull requests to fix them once I get through the tutorial.)

**Comment by magul** [comment]
Well caught there!

Actually it [installation page](https://github.com/DjangoGirls/tutorial/blob/master/en/installation/README.md) is composed from few others (see these `{% include "..." %}` there?)

So image actually is missin inside [deploy/signup_pythonanywhere.md](https://github.com/DjangoGirls/tutorial/blame/master/en/deploy/signup_pythonanywhere.md#L13). Moreover it use raw html tag (`<img>`) and should use Markdown instead (as on [Python installation instruction](https://github.com/DjangoGirls/tutorial/blame/master/en/python_installation/instructions.md#L14)).

The missing image is [here](https://github.com/DjangoGirls/tutorial/blob/master/en/deploy/images/pythonanywhere_create_api_token.png) and it it can be accessed just adding `../deploy` at the beginning of current (wrong) path.

Do You want to work on that? @jhodgdon-drp

**Comment by jhodgdon-drp** [comment]
I'll probably work on one or more of the several issues I am reporting, once I get through the tutorial (which is my first priority for spare time with this project, so I'm ready to coach when our workshop happens). In the meantime, if someone else wants to make the PR, fine! :)
