### ISSUE TITLE
GitHub instructions inconsistent

### ISSUE THREAD

**Issue by jhodgdon-drp** [DjangoGirls/tutorial#1332]
### Issue description

This is kind of minor, but... On the Deploy page, there are instructions for how to create a GitHub repo for your project. They say to copy the clone URL and "we'll paste it into the terminal shortly".

But then just below the image that follows, it says "Type the following into your console", with instructions to replace your-github-username with your actual user name, instead of suggesting pasting the URL.

So, we should either probably remove the copy/paste reference, or use it below. Not sure which?

**Comment by goanpeca** [comment]
I would favor the "remove the copy/paste reference"

**Comment by jhodgdon-drp** [comment]
Yes, that would be my inclination too. It's too complicated to explain how to copy/paste into command windows.

**Comment by jhodgdon-drp** [comment]
Made a PR...
