### ISSUE TITLE
Getting wrong error in urls.py

### ISSUE THREAD

**Issue by jhodgdon-drp** [DjangoGirls/tutorial#1335]
### Issue description

I'm attempting to run the tutorial. At the end of the django_urls page, I'm supposed to get an error saying that the post_list view doesn't exist.

But instead I'm getting an error saying 
````
NameError: name 'include' is not defined.
````

When I did a web search on this error, I found that there is a missing line in urls.py:
https://stackoverflow.com/questions/34471102/python-nameerror-name-include-is-not-defined

So I added this line to the top of my urls.py file:
````
from django.conf.urls import include
````

Now I get an error saying 
````
ModuleNotFoundError: No module named 'blog.urls'
````
I have no idea how to proceed now. The tutorial is just not working for me...

### Operating system

I'm running on Windows 8.1 if that makes a difference.

**Comment by jhodgdon-drp** [comment]
Something had gone wrong for me in this run... I started over and things are working better this time.

**Comment by magul** [comment]
Actually there are few valid points there - for example tutorial says to open this file and see what it contains (not mention to add anything), but `include` is not originally imported when `python manage.py startapp` is executed.

**Comment by jhodgdon-drp** [comment]
I need to update that PR because we have similar instructions elsewhere for restarting. We should probably make a small .md file that gives the instructions for restarting the web server, and then include it in various places, rather than reinventing it every time it is needed. Anyway, I don't recommend merging just yet...
