### ISSUE TITLE
Treats should not only be unhealthy food

### ISSUE THREAD

**Issue by saheba** [DjangoGirls/tutorial#134]
"Grab yourself a cupcake and go to the next chapter :)"
"Works like a charm? We're proud! Treat yourself something sweet, you have earned it :)"

Puts a pretty cliche picture on women, don't you think? What about changing these two lines and pictures to:

"Well done so far! Celebrate by doing something good for you - taking a short walk, go have a little chat with someone, watch your favorite youtube video or do anything else you would like to do right now."

"Works like a charm? We're proud! Treat yourself with something special, you have earned it :)"

**Comment by olasitarska** [comment]
Fixed in #252
