### ISSUE TITLE
Add Esperanto as new translation target language

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#1345]
### Issue description

Please make it possible to contribute to an Esperanto translation of the tutorial on Crowdin.

### Language

> Is this related to a specific language of the tutorial?

[Esperanto](https://en.wikipedia.org/wiki/Esperanto), ISO 639-1(Alpha-2) code `eo`

**Comment by magul** [comment]
Here You go: https://crowdin.com/project/django-girls-tutorial/eo

Closing that one meanwhile waiting for Crowdin translation to be done.

**Comment by das-g** [comment]
Wow, that was quick.

Thanks! :smiley:
