### ISSUE TITLE
Screenshot doesn't match narrative documentation

### ISSUE THREAD

**Issue by iElectric** [DjangoGirls/tutorial#141]
In http://tutorial.djangogirls.org/django_forms/README.html#edit-form, screenshot http://tutorial.djangogirls.org/django_forms/images/edit_button2.png includes a button for editing a post in the header. It shouldn't be there.

PS I don't have an apple machine to match other screenshot design, but if you're OK having inconsistency between screenshots, I can contribute my own :)

**Comment by aniav** [comment]
Updated. Thank you! :)
