### ISSUE TITLE
[Portuguese] Typo on Python introduction

### ISSUE THREAD

**Issue by luanamartins** [DjangoGirls/tutorial#1436]
### Issue description

In python_introduction directory, more specifically in the README.md file, there is a grammatical error. 

### Language

It is specific on PT on section "Error". There is a term "aprendizamgem", it should be "aprendizagem".

### Operating system

Not applicable.

**Comment by magul** [comment]
Hi @luanamartins, first of all thank your contribution. Can You also add it to our Crowdin project here: https://crowdin.com/project/django-girls-tutorial/pt-BR# ?

**Comment by magul** [comment]
Hi there, are You able to apply this fix on our Crowdin project here: https://crowdin.com/project/django-girls-tutorial/pt-BR# ?

**Comment by oieusouamiguel** [comment]
Hey! I'd like to get this issue. Can i? 😸

**Comment by magul** [comment]
Go for it @oieusouamiguel. It would be also great to insert these improvements on our Crowdin project here: https://crowdin.com/project/django-girls-tutorial/pt-BR#
