### ISSUE TITLE
wrong css selector in chapter "CSS - make it pretty!"

### ISSUE THREAD

**Issue by eisc** [DjangoGirls/tutorial#1445]
### Issue description

In subsection [Your first CSS file!](https://tutorial.djangogirls.org/en/css/#your-first-css-file) you should paste 

```
.post h1 a, .post h1 a:visited {
    color: #000000;
}
```

to the blog.css. There seems to be a typo since post headlines are tagged as `h2`, so the code maybe should look like this:

```
.post h2 a, .post h2 a:visited {
    color: #000000;
}
```

### Language

This should be unrelated to a specific language.

### Operating system

This should be unrelated to a specific operating system.

**Comment by jhodgdon-drp** [comment]
The issue report is correct. I made a PR to fix it. #1457
