### ISSUE TITLE
Travis cache directory contains a typo

### ISSUE THREAD

**Issue by cauebs** [DjangoGirls/tutorial#1469]
Travis has been caching a directory incorrectly named `turorial` and I'm not sure if that is a problem. Is it failing to find it, then creating it and caching the same empty directory every time?

https://github.com/DjangoGirls/tutorial/blob/d586d31c451bb4752e704dbe196e127f4fc56113/.travis.yml#L8

**Comment by das-g** [comment]
Hu.

I'm not sure
- whether this path will ever exist (even without the typo)
  (Doesn't Travis check out the repo to the current working dir?)
- whether the repo dir should be cached at all
  (Don't we want to test the specific version that triggered the respective CI build? And doesn't Travis clone that version from GitHub, anyway?)

I think instead we should cache NPM dependencies. (There's a [documented shortcut](https://docs.travis-ci.com/user/caching/#npm-cache) for that.)

**Comment by das-g** [comment]
@aniav You've set up the Travis build config. Can you look into this?

**Comment by aniav** [comment]
Yup, seems a typo to me 😅

I wouldn't say my gonfig for travis was final, more like anything what would keep us sane so feel free to change it 👌

**Comment by das-g** [comment]
I'd rather not make changes I don't fully understand.

Thus:
- Is caching the repository directory intended?
- Is caching npm dependencies intended?

**Comment by das-g** [comment]
> But I am not sure if Travis works like that, when I think of it now.

Yeah, I think it doesn't. It probably has to clone the repo first, anyway, as it would have to look at `.travis.yml` which could have changed between revisions. Only then can it decide, which caches to restore, I guess.

> Caching npm dependencies is intended

Cool, I'll try to make a PR for that.
