### ISSUE TITLE
Windows runserver.

### ISSUE THREAD

**Issue by AlexandrWeb** [DjangoGirls/tutorial#1472]
### Issue description

django_start_project

If not work

> (myvenv) ~/djangogirls$ python manage.py runserver 0:8000

work

> (myvenv) ~/djangogirls$ python manage.py runserver 0.0.0.0:8000

### Operating system

Windows 7.

**Comment by magul** [comment]
Can You clarify what's exactly not working? What happens when You run one command, what happens when You run the second one? Do You get in the console or in the web browser?

What's going with `django_start_project`? Is that the command that does not work?

**Comment by magul** [comment]
Also if You have an issue going through this tutorial You can always ask a question on our dedicated Gitter channel here: https://gitter.im/DjangoGirls/tutorial

**Comment by AlexandrWeb** [comment]
> (myvenv) ~\djangogirls>python manage.py runserver 0:8000
> Performing system checks...
> 
> System check identified no issues (0 silenced).
> January [...]
> Django version [...], using settings 'mysite.settings'
> Starting development server at http://0:8000/
> Quit the server with CTRL-BREAK.
> Error: [Errno 11004] getaddrinfo failed 

> (myvenv) ~/djangogirls$ python manage.py runserver 0.0.0.0:8000

Is correct.

This code from [django_start_project](https://tutorial.djangogirls.org/ru/django_start_project/) .

**Comment by das-g** [comment]
The Russian translation is out of sync with the [English original](https://tutorial.djangogirls.org/en/django_start_project/) in that regard. Help with updating it on https://crowdin.com/project/django-girls-tutorial would be welcome.

**Comment by AlexandrWeb** [comment]
In the [English original](https://tutorial.djangogirls.org/en/django_start_project/)  .
Command-line 

> (myvenv) ~/djangogirls$ python manage.py runserver 0.0.0.0:8000

for Chromebook. For  Windows  do not this line.

For Windows is

> (myvenv) ~/djangogirls$ python manage.py runserver 0:8000

command-line.

DjangoGirls good site.
