### ISSUE TITLE
Use Brazil flag for Brazilian Portoguese

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#1480]
### Issue description

The language choice page features country flags. While languages cannot be unambiguously mapped to countries, using Portugal's flag (🇵🇹) for **Brazilian** Portuguese seems like an odd choice, when Brazil's flag (🇧🇷) is also available in Unicode.

### Language

🇵🇹 Português-brasileiro (pt)

(Though needs to be fixed in the global `LANGS.md` file.)

**Comment by das-g** [comment]
Despite #1481 haveing been merge 16h ago, https://tutorial.djangogirls.org/ still shows Portugal's flag for Brazilian Portuguese. Thus re-opening.

@magul Do you know how this works? Do we need to do something on https://legacy.gitbook.com/ ?

**Comment by magul** [comment]
I'm having a Brazilian one. Maybe there were some caching involved?
![screenshot from 2019-02-08 09-44-53](https://user-images.githubusercontent.com/1165138/52467582-4b45fa00-2b86-11e9-889e-8f5b595b5b00.png)

Every commit that lands on master should be automatically built on GitBook infrastructure, but I'm also our that these builds are not exactly reliable.

Please recheck and if it also works for You, close.

**Comment by das-g** [comment]
Thanks for replying!

Yes, now it shows Brazil's flag for me, too. (I'm sure I've force-refreshed the page already before, though. Not sure what was up.) Closing again.
