### ISSUE TITLE
Windows section of "Open the command-line interface" isn't collapsing

### ISSUE THREAD

**Issue by mulka** [DjangoGirls/tutorial#1494]
### Issue description

The Windows section underneath the title "Open the command-line interface" isn't collapsing. If you are using a Mac, you'd want to skip that section, but it is starting open and not collapsing.
https://tutorial.djangogirls.org/en/intro_to_command_line/#open-the-command-line-interface

### Language

I saw it in English, not sure if it is in other languages.

### Operating system

I'm reading the tutorial on a Mac, but it is the Windows content that isn't collapsing.

**Comment by das-g** [comment]
When I view it, the section itself is collapsed (and expands on click on the drop down button), but is empty, and its intended content is after that section.

**Comment by das-g** [comment]
https://tutorial.djangogirls.org/en/intro_to_command_line/#open-the-command-line-interface looks good now, so #1499 seems to have worked! :tada:

Thanks @mulka for reporting and @brondsem for the fix! :smile:

**Comment by mulka** [comment]
cool, thanks!
