### ISSUE TITLE
Tutorial in Nepali

### ISSUE THREAD

**Issue by Rhitabrat** [DjangoGirls/tutorial#1502]
Hi, I can translate the tutorials to Nepali. I am from Nepal.

What do I need to do for that? :)

**Comment by magul** [comment]
Hi @Rhitabrat I just created Nepali language on our Crowdin project here: https://crowdin.com/project/django-girls-tutorial/ne-NP#. Feel free to get involved there.

Closing this one and waiting for Nepali translation there. :)
