### ISSUE TITLE
Add "Dhivehi" Maldivain Language 

### ISSUE THREAD

**Issue by aieshamv** [DjangoGirls/tutorial#1505]
### Issue description

Dhivehi not listed in the language list of the Tutorial
Dhivehi is the Language spoken in Maldives

### Language
Dhivehi not listed in the language list of the Tutorial

### Operating system
NA

**Comment by magul** [comment]
Dhivehi language added to our Crowdin project: https://crowdin.com/project/django-girls-tutorial/dv#

Feel free to jump there and start adding translations.
