### ISSUE TITLE
Translation into Armenian (I would like to try if none available)

### ISSUE THREAD

**Issue by avaarm** [DjangoGirls/tutorial#1511]
### Issue description

DjangoGirls is not translated in Armenian.

### Language

Is this related to a specific language of the tutorial? Yes, it is related to the Django girls tutorial being translated to Armenian. I would like to help!  

### Operating system

N/A (all operating systems).

**Comment by das-g** [comment]
Hi @avaarm

Translations of the Django Girls tutorial are created and maintained [on Crowdin](https://crowdin.com/project/django-girls-tutorial).

It looks like a translation into Armenian has already been begun at https://crowdin.com/project/django-girls-tutorial/hy-AM. Feel free to participate there!

**Comment by avaarm** [comment]
Thank you! woohoo.
