### ISSUE TITLE
django installation error

### ISSUE THREAD

**Issue by shaochieh** [DjangoGirls/tutorial#1514]
### Issue description
https://tutorial.djangogirls.org/en/installation/#installing-packages-with-requirements
while installing django encountered error:
Collecting Django~=2.0.6 (from -r requirements.txt (line 1))
  ERROR: Could not find a version that satisfies the requirement Django~=2.0.6
Describe what's the problem here.
seems like pip doesn't support django >= 2.0.0
pip3 should be thru
and seems like some installation should be done with "sudo -H pip3 install..."?

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?
im using WSL (Ubuntu 16.04) on windows.

**Comment by jlgimeno** [comment]
It depends on what "pip" is pointing to.  If pip is coming from Python 2, Django >= 2.0.0 is not supported on Python 2 at all.
