### ISSUE TITLE
Rename GitHub team @DjangoGirls/cn-pr ?

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#1517]
This issue doesn't apply to the tutorial alone, but to the whole @DjangoGirls organization on GitHub. As there is no obvious place for such meta issues, I'm filing it here, as it came up in https://github.com/DjangoGirls/tutorial/pull/1515#issuecomment-489605808.

### Issue description

The pull-request review team for Chinese is currently called @DjangoGirls/cn-pr

However, `CN` isn't an ISO **language** code, it's an ISO **country** code.

The [ISO 639-1 (=two-letter) **language** code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for the group of languages known as "Chinese"  is `zh`, and that's also how we named [our Chinese-specific subfolder](https://github.com/DjangoGirls/tutorial/tree/master/zh). (Which currently has the simplified Chinese translation, I believe.)

Crowdin distinguishes between simplified and traditional Chinese and [uses `zh-CN`](https://crowdin.com/project/django-girls-tutorial/zh-CN#) [and `zh-TW`](https://crowdin.com/project/django-girls-tutorial/zh-TW) for them. The [W3C recommendation](https://www.w3.org/TR/i18n-html-tech-lang/#h2_langvalues) would be `zh-Hans` and `zh-Hant`, respectively.

### Language

`zh`

**Comment by aniav** [comment]
Done! 👍
