### ISSUE TITLE
"python manage.py migrate" didn't work but "python3 manage.py migrate" did

### ISSUE THREAD

**Issue by basiccreation** [DjangoGirls/tutorial#1520]
### Issue description
python manage.py migrate on page
"Your first Django Project" under
"Set up a database"

Describe what's the problem here.
`python manage.py migrate `didn't work but 
`python3 manage.py migrate` did

### Language
EN
Is this related to a specific language of the tutorial?
don't know

### Operating system
What operating system does this issue relate to?
OS

**Comment by das-g** [comment]
Hi @basiccreation

Thanks you for your report.

Did you make sure that you have your [virtual environment](https://tutorial.djangogirls.org/en/django_installation/#virtual-environment) [activated](https://tutorial.djangogirls.org/en/django_installation/#working-with-virtualenv)? Within the virtual environment, just `python` should work, too, and should invoke Python 3. We're using that command in our instructions, as the `python3` command may not be available on Windows.
