### ISSUE TITLE
python vs python3 in instructions

### ISSUE THREAD

**Issue by basiccreation** [DjangoGirls/tutorial#1521]
### Issue description

Describe what's the problem here.

Starting the web server

You need to be in the directory that contains the manage.py file (the djangogirls directory). In the console, we can start the web server by running `python manage.py runserver`

-> should be python3 manage.py run server

### Language
EN

### Operating system
OS

**Comment by das-g** [comment]
Hi @basiccreation

Thanks you for your report.

As in #1520: Did you make sure that you have your [virtual environment](https://tutorial.djangogirls.org/en/django_installation/#virtual-environment) [activated](https://tutorial.djangogirls.org/en/django_installation/#working-with-virtualenv)? Within the virtual environment, just `python` should work, too, and should invoke Python 3. We're using that command in our instructions, as the `python3` command may not be available on Windows.

**Comment by aniav** [comment]
I'll close this one as it's a returning report for something we can't really address, especially because of how operating systems differ in how they handle two versions of python and their namings.
