### ISSUE TITLE
[es] Spelling Errors in "Introducción"

### ISSUE THREAD

**Issue by khdc-me** [DjangoGirls/tutorial#1529]
### Issue description
1st paragraph under "Bienvenido/a" missing an accent:
Current: ¡Nos alegra que estes aquí!
Should be: ¡Nos alegra que estés aquí

2nd paragraph under "Bienvenido/a" read better as follows:
Current: te va a ir fenomenal
Should be: te irá de maravilla

2nd paragraph under "Introducción" missing a word:
Current: queremos demostrarte lo divertido puede llegar a ser
Should be: queremos demostrarte lo divertido que puede llegar a ser

1st paragraph under "Seguir el tutorial desde casas" missing a word:
Current: Para las que estáis casa,
Should be: Para las que estáis en casa,

### Language
Spanish / Español / es

### Operating system
N/A

**Comment by das-g** [comment]
Thank you for the report!

We maintain translations on Crowdin. The Spanish one can be found at https://crowdin.com/project/django-girls-tutorial/es. Please consider to suggest the corrections there, so that other Spanish-speaking contributors can proofread them.

**Comment by khdc-me** [comment]
Thanks @das-g .

Was actually hoping to leave this as low-picking fruit for someone new to git. Being that's not the case, went ahead and submitted above suggestions at crowdin.

FYI, there's A LOT of work to be done. Primarily, there are so many different variations of how to say something and it might make sense in one country, but not in another. Anyway, great job on this project.

**Comment by das-g** [comment]
> FYI, there's A LOT of work to be done.

Do you mean on the Spanish translation?

> Primarily, there are so many different variations of how to say something and it might make sense in one country, but not in another.

Do you mean phrasing differences between different Spanish-speaking countries? If those cannot be avoided, we could add different variations of Spanish as translation targets on Crowdin, but that would of course also mean more work for the translators.

If they can be avoided by finding phrasings that work in all countries, maybe this can be achieved by having people from different Spanish-speaking countries do the proofreading on Crowdin? In any case, help and more involved people would be appreciated!
