### ISSUE TITLE
Getting Page Not Found when trying to open tutorial.

### ISSUE THREAD

**Issue by arnavb** [DjangoGirls/tutorial#1531]
### Issue description

When I visit [the tutorial url](https://tutorial.djangogirls.org), I get the following page (it was working fine yesterday):

![image](https://user-images.githubusercontent.com/30810402/59800253-183e1080-92b4-11e9-89fb-3285b41dadf6.png)

There seem to be 20 errors in the console (I notice a 404 as well).

### Language

Is this related to a specific language of the tutorial?

Nope

### Operating system

What operating system does this issue relate to?

I'm on Windows, if it matters.

Also, thanks for a great tutorial, by the way! Great for beginners wanting to get into Django.

**Comment by das-g** [comment]
It seems to be an issue on GitBook's side: https://twitter.com/GitBookStatus/status/1141437901907144706

> We are encountering issues with our storage system on the legacy version at http://legacy.gitbook.com . We are doing our best to resolve the situation. In the meantime, most of the content might be unreachable. Our apologies for the inconvenience.

We'll leave this issue open until the problem is resolved, even though we (Django Girls) probably can't do anything about this for now.

**Comment by arnavb** [comment]
That makes sense then. Thanks for clarifying!

**Comment by arnavb** [comment]
Well the website seems to be back up. Thanks for all your help!
