### ISSUE TITLE
Can't see urls.py in blog directory.

### ISSUE THREAD

**Issue by love-adelar** [DjangoGirls/tutorial#1535]
### Issue description

Unlike mysite/ directory, in the blog/ directory urls.py is not installed.

### Language

Is this related to a specific language of the tutorial?
  * English.

### Operating system

What operating system does this issue relate to?
  * ~~Mac OS~~ all

**Comment by magul** [comment]
It needs to be created manually, but that's in the further part of the tutorial (https://tutorial.djangogirls.org/en/django_urls/#blogurls). Well spotted!

**Comment by magul** [comment]
So is that a problem or not? That's a minor issue, but still, should be addressed.

**Comment by love-adelar** [comment]
Oh Well, I felt confused at first, eventually I understood what you
purpose. Of course I'll be thank you if you modified it, but if you don't,
I don't mind it.

Thank you

2019년 7월 8일 (월) 오후 10:58, Tomasz Magulski <notifications@github.com>님이 작성:

**Comment by thibaudcolas** [comment]
I’ve opened a pull request to remove this line, #1599. As far as I can see this file isn’t supposed to be created by `startapp` (as opposed to `startproject`).
