### ISSUE TITLE
update the Django Girls tutorial to use Django 2.2 LTS

### ISSUE THREAD

**Issue by love-adelar** [DjangoGirls/tutorial#1536]
### Issue description

Django's documentation [here](https://tutorial.djangogirls.org/en/django_models/) is outdated.

https://docs.djangoproject.com/en/2.0/ref/models/fields/#field-types)
https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types

### Language

Is this related to a specific language of the tutorial?
  * English

### Operating system

What operating system does this issue relate to?

**Comment by magul** [comment]
Can You point to the exact statement, that's outdated?

**Comment by love-adelar** [comment]
Thank you for your reply. 
Here is the statement, and I feel sorry for lack of English, though. 
'You should take a look at Django's documentation if you want to know more about Model fields and how to define things other than those described above (https://docs.djangoproject.com/en/2.0/ref/models/fields/#field-types).'

**Comment by magul** [comment]
So You're reporting that banner? Or is there anything else, that's not working right now?
![Screenshot from 2019-07-08 16-02-16](https://user-images.githubusercontent.com/1165138/60816344-d3621700-a199-11e9-8cbf-8d80fe6c6697.png)

**Comment by love-adelar** [comment]
Yup! I reported the banner.

2019년 7월 8일 (월) 오후 11:03, Tomasz Magulski <notifications@github.com>님이 작성:

**Comment by kaizumaki** [comment]
I would like to test the tutorial with Django's current LTS version 2.2.
I will report the results here. 
Please wait for a moment.

@das-g , thank you for the advice!

**Comment by kaizumaki** [comment]
@das-g Thank you for changing the title of this issue.
Can you change "Python" in the title to "Django"?

**Comment by das-g** [comment]
>  Can you change "Python" in the title to "Django"?

oops, my mistake

changed!

**Comment by kaizumaki** [comment]
I made a pull request #1556 .
I verified the tutorial with the following combinations:
- OSX + Python3.6.9 + Django2.2.4
- Windows10 + Python3.6.8 + Django2.2.4
I commented on each commit.

Should I test with Python3.7?

**Comment by das-g** [comment]
> Should I test with Python3.7?

Feel free to do that, but I don't think it's necessary for PR #1556, as that is about the Django version. (And I'm confident that the parts of Django the tutorial uses work just as fine with Python 3.7 as they do with Python 3.7. [According to the documentation](https://docs.djangoproject.com/en/2.2/faq/install/#what-python-version-can-i-use-with-django) both combinations are supported.)

**Comment by kaizumaki** [comment]
@das-g Thanks. I think so, too. (I just installed Python3.7.4 on a Windows10 PC and ran Django commands. There was no problem.)
