### ISSUE TITLE
Typo in word  type: translations

### ISSUE THREAD

**Issue by whatmode** [DjangoGirls/tutorial#1544]
### Issue description
Mistake in word **Моб** in start_django_project must be _Щоб_
### Language
Ukrainian

**Comment by magul** [comment]
Hi @whatmode, thanks for your report here!

We tend to maintain translation on Crowdin (see: https://crowdin.com/project/django-girls-tutorial). The Ukrainian language is greatly out-of-date right now, but can I ask you also to provide this correction there?

Thanks in advance!

**Comment by fltfx** [comment]
Did a quick search for `Моб`,  not sure that word is used anymore . Closing  this.
