### ISSUE TITLE
Wrong Translation :: Farsi/Persian

### ISSUE THREAD

**Issue by afzoun** [DjangoGirls/tutorial#1546]
Hi
In [this chapter](https://tutorial.djangogirls.org/fa/django_start_project/) at section `Create Project` the sentence `جنگو را در همین پوشه جاری نصب کند` should be `پروژه را در همین پوشه جاری ایجاد کند`.

**Comment by magul** [comment]
Hi @afzoun, thanks for your report!

We tend to maintain translation on Crowdin. For example Persian translation is available here: https://crowdin.com/project/django-girls-tutorial/fa#. Can you, please, apply your improvement there?

Thanks in advance!

**Comment by afzoun** [comment]
I did that
Thanks
