### ISSUE TITLE
A error occurs in blog/urls.py

### ISSUE THREAD

**Issue by h5jam** [DjangoGirls/tutorial#1566]
### Issue description

When I add this code in my blog/urls.py, a error occurs.
I want to add the necessary module to the tutorial to make sure novices don't panic.
 

`url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),`

Thank you.

https://tutorial-extensions.djangogirls.org/ko/homework/#%EA%B2%8C%EC%8B%9C%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%80-%EB%B8%94%EB%A1%9C%EA%B7%B8-%EA%B8%80-%EB%AA%A9%EB%A1%9D-%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%A7%8C%EB%93%A4%EA%B8%B0

### Language

KO

### Operating system

Mac

**Comment by magul** [comment]
Issue moved to [DjangoGirls/tutorial-extensions #133](https://github.com/DjangoGirls/tutorial-extensions/issues/133) via [**ZenHub**](https://www.zenhub.com/)
