### ISSUE TITLE
"Initial commit" reads "No commits yet" in deploy (en)

### ISSUE THREAD

**Issue by noellethenerd** [DjangoGirls/tutorial#1570]
### Issue description

In the README.md of the deploy section (english version), Line 61 says "Initial commit" when in practice it has read "No commits yet" at that stage of the tutorial :) <3

### Language

English version

### Operating system

Spotted on MacOs

**Comment by magul** [comment]
Hi @noellethenerd, do you want to prepare a fix here?

**Comment by fernandasj** [comment]
I submitted a pull request about this problem :tada:
