### ISSUE TITLE
Codecademy CSS/HTML course link broken (no longer free)

### ISSUE THREAD

**Issue by noellethenerd** [DjangoGirls/tutorial#1572]
### Issue description

Unfortunately codecademy's css/html and web track course in general are no longer free (but the link is still in CSS part of tutorial, leading to a broken url). I can recommend [free code camp's](https://learn.freecodecamp.org/) Responsive Web Design Certification as a reference instead. It has 300 hours of free videos on html/CSS stuff and it's all really good :D 

### Language

English

### Operating system

All

**Comment by fernandasj** [comment]
I submitted a pull request about this problem :tada:
