### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by FelipeSBarros** [DjangoGirls/tutorial#1611]
### Issue description

on the end of CSS' chapter, the [link](https://www.codecademy.com/tracks/web) to codeacademy HTML and CSS is broken: 

### Language

Is this related to a specific language of the tutorial? No sure. But I am using the pt-br tutorial.

**Comment by magul** [comment]
That looks like it was fixed in #1577 in the English version of the tutorial. We can either fix that here or wait for translation from Crowdin.

**Comment by FelipeSBarros** [comment]
Great, @magul . Which work better for you.
If you want me to do something, just let me know.
Cheers

**Comment by magul** [comment]
I would be great to have Crowdin translation for Portuguese up-to-date. Be aware, that we have still problem that GtiBook (the platform that we use to host tutorial itself) is not refreshed for some reason, so your change will not be seen there immediately.

**Comment by magul** [comment]
Link to Crowdin translation is here: https://crowdin.com/project/django-girls-tutorial/pt-BR#
