### ISSUE TITLE
completed Japanese translation review, so please create Pull Request

### ISSUE THREAD

**Issue by ftnext** [DjangoGirls/tutorial#1615]
### Issue description

I completed review and updated Japanese translation from the version of https://github.com/DjangoGirls/tutorial/pull/1574
<img width="252" alt="スクリーンショット 2019-11-03 22 47 17" src="https://user-images.githubusercontent.com/21273221/68086364-86aff380-fe8e-11e9-8a67-d52adb321c17.png">

It seems that I cannot create Pull Request of updated Japanese translation from crowdin, so please create PR instead of me (and merge to master).
ref: https://support.crowdin.com/github-integration/

### Language

Japanese translation

### Operating system

This issue has nothing to do with operating system.

**Comment by magul** [comment]
Done in #1616

**Comment by kaizumaki** [comment]
@magul  I was finished translating where untranslated parts were generated by #1617 . The review by @ftnext has also been completed. Would you please create a PR for reflecting Japanese translation on GitBook?
