### ISSUE TITLE
Azerbaycan

### ISSUE THREAD

**Issue by cefer96** [DjangoGirls/tutorial#1626]
### Issue description

Describe what's the problem here.

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by magul** [comment]
You didn't really describer a problem, but, assuming on the title, you want to introduce the tutorial in Azerbaijani. We already have this language enabled on Crowdin, so feel free to jump there directly to help in translation. It's here: https://crowdin.com/project/django-girls-tutorial/az#

Closing this issue and waiting for the translation to be 100% covered in Crowdin.

Thanks for the report!
