### ISSUE TITLE
kazakh

### ISSUE THREAD

**Issue by Yeldana00** [DjangoGirls/tutorial#1637]
### Issue description

Describe what's the problem here.

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by magul** [comment]
Hi @Yeldana00 first of all thanks for this issue, I've just enabled Kazakh as a target language on our Crowdin project. Feel more than welcome to start providing translations there.

Link: https://crowdin.com/project/django-girls-tutorial/kk#
