### ISSUE TITLE
The GitBook Editor is no more

### ISSUE THREAD

**Issue by kjcole** [DjangoGirls/tutorial#1639]
### Issue description

The **New content and complex changes** in `README.md` suggests downloading the **GitBook Editor** from https://legacy.gitbook.com/editor but the link redirects to https://www.gitbook.com/

So, either the editor is no longer available, or has moved.

**Comment by ekohl** [comment]
We are indeed still using the legacy way and perhaps that has ceased to exist. Currently I'm not aware of a plan to update, but we should have one.

**Comment by ekohl** [comment]
https://github.com/DjangoGirls/tutorial/issues/1652 forces us to move. Closing this to centralize the discussion.
