### ISSUE TITLE
Suggestion: Word wrapping

### ISSUE THREAD

**Issue by kjcole** [DjangoGirls/tutorial#1641]
Since I'm "old-school" and still inclined to use editors that don't display unwrapped text as wrapped, and since PEP-8 has a thing or two to say about the format of Python code, and one of the points of Markdown is that it's readable without being "marked-up" I'd like to make a "modest proposal" though I doubt I'll get much buy-in:

Hard word-wrap .md files at less than 80 characters.

**Comment by ekohl** [comment]
I think this would break our translations though I'm not sure.

**Comment by das-g** [comment]
Alternative (which would also be good to make diffs and reviews more readable and accessible afterwards): adopt ["semantic linefeeds"](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

Its easiest variant is easy to write: one sentence per (Markdown source) line.

To keep within a reasonable line length (which [probably should be 90-ish](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length), not the rather limiting 80 or 78) long sentences can also be line-broken at semantically or grammatically appropriate places. That variant is a but more difficult, as it's not always easy to decide (or agree) what places within a sentence this should be.

I hope "semantic linefeeds" would actually improve the translation process, in that individual sentences could be translated without having to translate whole paragraphs at once. (Which often is too big a chunk to swallow.)

**Comment by kjcole** [comment]
I think I'll withdraw this issue. 

My understanding of the purpose of markdown went beyond "simpler to create, edit and maintain". I was under the impression that documents written in markdown format would be quite readable without any additional processing, and "prettier" with the additional processing. 

While semantic linefeeds and 88 characters may make git and other applications happy, they don't make humans reading raw source happy. (Well, they don't make _this_ human happy :wink: which was why I filed the issue in the first place.)

**Comment by das-g** [comment]
> My understanding of the purpose of markdown went beyond "simpler to create, edit and maintain". I was under the impression that documents written in markdown format were intended to be quite readable without any additional processing, and "prettier" with the additional processing.

That's my understanding of the _intention_ of Markdown, too. Whether the format can always live up to that (or whether documents in the format can always be _made_ to live up with that) is of course debatable.

> While semantic linefeeds and 88 characters may make git and other applications happy, they don't make humans reading raw source happy.

Uh, well, they're actually intended to make source-reading humans happy, too.
(And would make _me_, another sometimes-source-reading human, much happier than our current up-to-almost-900-character source lines. I've actually considered to file an improvement request of my own about that.)

Off course, the second variant of semantic linefeeds (with linebreaks also within sentences) could also be done with 80 (or 78) character as the maximal line length, which has advantages if one wants to view the files or diffs thereof (thus just 78) in a 80-character-wide terminal window, which is still the default width for newly opened terminal windows on many systems.
