### ISSUE TITLE
Add Hindi As language here

### ISSUE THREAD

**Issue by madhav06** [DjangoGirls/tutorial#1656]
### Issue description

Add hindi as language 
### Language
or I can help here contributing it. Hindi learners are vast in numbers, you should pay attention.

### Operating system

Mac OS, Ubuntu, Windows

**Comment by das-g** [comment]
Hi @madhav06

The Django Girls tutorial and all its translations are created and maintained by volunteers.

We create and maintain translations of the Django Girls tutorial [on Crowdin](https://crowdin.com/project/django-girls-tutorial). A hindi translation has been begun there. If you can, please contribute [there](https://crowdin.com/project/django-girls-tutorial/hi) to make it become a reality.

Once it is complete, we'll add it to the start page at https://crowdin.com/project/django-girls-tutorial

**Comment by magul** [comment]
Closing that one, as we track translation progress in Crowdin, as @das-g pointed out.
