### ISSUE TITLE
Punjabi Language (Indian Punjabi ) Translation

### ISSUE THREAD

**Issue by jaspreet1990** [DjangoGirls/tutorial#1658]
### Issue description

This tutorial is not translated into Punabi Language . 

### Language
(Indian Punjabi Language)

### Operating system
Window

**Comment by magul** [comment]
Hi, thanks @jaspreet1990 for that report. We tend to translate tutorial on Crowdin. I've just added Punjabi as one of the target languages there.  Feel free to jump directly there to start translating.

Direct link: https://crowdin.com/project/django-girls-tutorial/pa-IN#

I'm closing this issue, waiting for 100% coverage on Crowdin.
