### ISSUE TITLE
Site is off?

### ISSUE THREAD

**Issue by GCrispino** [DjangoGirls/tutorial#1664]
Hi!
Not sure if this is the right place, but I've had some problems when trying to open the [website](http://tutorial.djangogirls.org/). I've been getting ERR_NAME_NOT_RESOLVED error. Is the site suffering from infrastructure changes/problems?

**Comment by magul** [comment]
We're using GitBook (legacy) to server tutorial. I can see CNAME for `tutorial.djangogirls.org`
```
$ dig tutorial.djangogirls.org  CNAME

; <<>> DiG 9.16.1-Ubuntu <<>> tutorial.djangogirls.org CNAME
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29492
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;tutorial.djangogirls.org.	IN	CNAME

;; ANSWER SECTION:
tutorial.djangogirls.org. 226	IN	CNAME	www.gitbooks.io.

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: czw cze 04 15:15:18 CEST 2020
;; MSG SIZE  rcvd: 82

```
but `www.gitbooks.io` DNS record is empty:
```
$ dig www.gitbooks.io CNAME A
;; Warning, extra type option

; <<>> DiG 9.16.1-Ubuntu <<>> www.gitbooks.io CNAME A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56990
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.gitbooks.io.		IN	A

;; Query time: 12 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: czw cze 04 15:18:03 CEST 2020
;; MSG SIZE  rcvd: 44
```

There's also an issue that Legacy GitBook is deprecated. They claimed that only updating content will be disabled, but maybe the deprecation went further. See #1652 for reference.

**Comment by GCrispino** [comment]
> There's also an issue that Legacy GitBook is deprecated.

Maybe that's the problem then? The legacy [GitBook website](https://legacy.gitbook.com/book/djangogirls/djangogirls-tutorial) seems to be off, too.

**Comment by magul** [comment]
> Maybe that's the problem then? The legacy GitBook website seems to be off, too.

It looks that they have infrastructure problem: https://twitter.com/GitBookStatus/status/1268530219901693956

I would prefer not to rush to move the tutorial to a different provider, but  I believe, as Legacy is deprecated the discussion in #1652 will speed up here.

**Comment by magul** [comment]
It looks, that it works at the moment. Closing that one and will conduct moving from GitBook infrastructure in #1652.
