### ISSUE TITLE
Search looks in all languages instead of the selected one.

### ISSUE THREAD

**Issue by ekohl** [DjangoGirls/tutorial#1668]
### Issue description

If you search for something (like [int](https://tutorial.djangogirls.org/en/django_urls/?q=int)), it searches in all languages. This may be confusing for users. I think search was only introduced when we switched from Gitbooks Legacy to Honkit in f7df5004acfc3e478c67f9cc775ca7ac96c91ff9.

### Language

All

### Operating system

Unrelated

**Comment by das-g** [comment]
> I think search was only introduced when we switched from Gitbooks Legacy to Honkit in f7df500.

No, there was search on GitBook legacy, too. And there too, search had an issue with multiple languages: #1564

**Comment by ekohl** [comment]
Duplicates #1564
