### ISSUE TITLE
Contribute to the  new Igbo Language Translation on Crowdin

### ISSUE THREAD

**Issue by PluckyPrecious** [DjangoGirls/tutorial#1670]
### Issue description

I came across the Django Girls translation project on Crowdin and have
interest in contributing to the project which I already joined and
started. I’d love to know if I’ll be needing additional guide and if
there’s a community or group for Django Girls or Translators I’ll need
to join. Thanks.

### Language

Nil

### Operating system

Nil

**Comment by magul** [comment]
Hi @PluckyPrecious,

we have dedicated resource for the Igbo language on Crowdin: https://crowdin.com/project/django-girls-tutorial/ig#

besides that, we also have a general-purpose resource for translators here: https://github.com/DjangoGirls/translation-guide and (I've just seen that in GitHub organization) we have [wiki](https://github.com/DjangoGirls/wiki#django-girls-tutorial).

Do you have any further questions?

**Comment by das-g** [comment]
> we also have a general-purpose resource for translators here: https://github.com/DjangoGirls/translation-guide

The "Django Girls Translation Guide" is also available at https://translate.djangogirls.org/

Some of the [discussions](https://crowdin.com/project/django-girls-tutorial/discussions) on Crowdin might also be relevant, especially [Getting started with the DjangoGirls Tutorial](https://crowdin.com/project/django-girls-tutorial/discussions/16/0/my-languages).

**Comment by PluckyPrecious** [comment]
> Hi @PluckyPrecious,
> 
> we have dedicated resource for the Igbo language on Crowdin: https://crowdin.com/project/django-girls-tutorial/ig#
> 
> besides that, we also have a general-purpose resource for translators here: https://github.com/DjangoGirls/translation-guide and (I've just seen that in GitHub organization) we have [wiki](https://github.com/DjangoGirls/wiki#django-girls-tutorial).
> 
> Do you have any further questions?

Hi @magul , thanks for the response.

 I’ve sent series of mail in regards to the resource below 👇 , and got no response. @das-g I’ll check out the guide thanks.

>If you want to join an existing translation team or launch a new translation, send an email to the translation managers or contact us.

>To be published, a translation needs to be validated by a proofreader. If you don't know if a proofreader is on your team or if you want to be one, send an email to the translation managers or contact us.

**Comment by magul** [comment]
> If you want to join an existing translation team or launch a new translation, send an email to the translation managers or contact us.

> To be published, a translation needs to be validated by a proofreader. If you don't know if a proofreader is on your team or if you want to be one, send an email to the translation managers or contact us.

Where did you find these @PluckyPrecious ? AFAIK everybody on Crowdin can join our project as a translator. To become o proofreader your privileges need to be upgraded.

I don't believe we have that written down anywhere, but at least I follow the policy to prepare translation pull request from Crowdin even if they are not proofread (they are usually marked `(beta)` on languages list), when they become proofread I remove `(beta)` mark in following pull request.

Also, regarding reviewing pull requests on GitHub I follow a week-long waiting period for a reviewer to step up and demand some changes. If nobody steps up I merge it, if somebody expresses any requests we're trying to resolve them (we have 2 of such hanging pull request right now, one for the Russian and one for the Spanish language, they are taking long, but you should remember that we all are here volunteering our time).

**Comment by PluckyPrecious** [comment]
> > If you want to join an existing translation team or launch a new translation, send an email to the translation managers or contact us.
> 
> > To be published, a translation needs to be validated by a proofreader. If you don't know if a proofreader is on your team or if you want to be one, send an email to the translation managers or contact us.
> 
> Where did you find these @PluckyPrecious ? AFAIK everybody on Crowdin can join our project as a translator. To become o proofreader your privileges need to be upgraded.
> 
> I don't believe we have that written down anywhere, but at least I follow the policy to prepare translation pull request from Crowdin even if they are not proofread (they are usually marked `(beta)` on languages list), when they become proofread I remove `(beta)` mark in following pull request.
> 
> Also, regarding reviewing pull requests on GitHub I follow a week-long waiting period for a reviewer to step up and demand some changes. If nobody steps up I merge it, if somebody expresses any requests we're trying to resolve them (we have 2 of such hanging pull request right now, one for the Russian and one for the Spanish language, they are taking long, but you should remember that we all are here volunteering our time).

@magul kindly check the README 👉 https://github.com/DjangoGirls/translation-guide it’s there, I now know better & totally understand everyone is volunteering. I appreciate your time many thanks! 🙌

**Comment by magul** [comment]
@PluckyPrecious I actually wasn't aware of the shape of this README - we should probably update it (it's from 2016).

**Comment by magul** [comment]
I don't even know if somebody is checking that inbox. :/

**Comment by PluckyPrecious** [comment]
> @PluckyPrecious I actually wasn't aware of the shape of this README - we should probably update it (it's from 2016).

Oh! That’s okay. 😃

**Comment by magul** [comment]
So can we close this ticket? Or should we:
 * rename it
 * move that to translation-guide repo
 * prepare an update for README there?

**Comment by PluckyPrecious** [comment]
> So can we close this ticket? Or should we:
> 
> * rename it
> * move that to translation-guide repo
> * prepare an update for README there?

The latter is perfecto 💯 , it will help guide others. 😺

**Comment by magul** [comment]
I've created https://github.com/DjangoGirls/translation-guide/issues/8 moving translators onboarding there. If you want to work on this @PluckyPrecious, you're welcome to jump straight there!

Closing that ticket, as the Igbo language is enabled in Crowdin and waiting for translators.
