### ISSUE TITLE
Feature: Add Django Coursera Specialization to What's Next

### ISSUE THREAD

**Issue by RachellCalhoun** [DjangoGirls/tutorial#1671]
### Issue description
A new specialization opened on Coursera for django. this ticket https://github.com/DjangoGirls/djangogirls/issues/527 brought up the recommendation to add it to the tutorial. 
https://www.coursera.org/specializations/django

I would probably fit well under the [django section ](https://github.com/DjangoGirls/tutorial/tree/master/en/whats_next#django)

### Language

I imagine this could be useful to all language speakers but the course is probably only in English. Need to verify.

### Operating system

all

**Comment by Aayushadh** [comment]
Can I work on this issue ?

**Comment by ekohl** [comment]
@RachellCalhoun did add the label `help wanted` so I think you're very welcome to work on this.
