### ISSUE TITLE
To correct "/".

### ISSUE THREAD

**Issue by AlexandrWeb** [DjangoGirls/tutorial#1673]
Page
https://tutorial.djangogirls.org/ru/css/

Replase

`<link rel="stylesheet" href="{% static 'css/blog.css' %}">`

to

`<link rel="stylesheet" href="{% static '/css/blog.css' %}">`

.

**Comment by ekohl** [comment]
Why? AFAIK this isn't needed and can actually break things.

**Comment by nikhiljohn10** [comment]
`<link rel="stylesheet" href="{% static 'css/blog.css' %}">` is the correct format.

No change needed.

v2.2 - https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#std:templatetag-static
v3.1 - https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#std:templatetag-static

**Comment by das-g** [comment]
Thanks for the analysis, @ekohl and @nikhiljohn10.

Closing this issue, as the suggested change seems inadvisable.
