### ISSUE TITLE
Update Django Girls tutorial to Django 3.1

### ISSUE THREAD

**Issue by nikhiljohn10** [DjangoGirls/tutorial#1677]
Currently Django released 3.1.3 version. Due to this new people who follow it get in to lots of trouble. I found this from answering then in gitter channel of Djangogirls.

Is there any plans of publishing updated version of tutorial?

At least updating to version 3.0 can resolve most issues.

**Comment by das-g** [comment]
The Django Girls tutorial is maintained by volunteers like you and me. A pull request to update it to a newer version of Django would be welcome. If it's too much work for a single contributor, we could start a branch where we collect the necessary changes for the update, so we can merge them once they're complete.

We should try to not get the production version (the `master` branch that is getting automatically deployed to <https://tutorial.djangogirls.org>) into a half-updated state, as that would conceivably confuse readers and learners even more and get them into trouble that couldn't even be solved by: "Please begin the tutorial again from the ['Django installation' chapter](https://tutorial.djangogirls.org/en/django_installation/) and make sure you do specify the version in `djangogirls/requirements.txt` exactly as given in the tutorial."

**Comment by nikhiljohn10** [comment]
@das-g I totally agree. A development branch will be perfect. Maybe a 'v3.1' branch would work great. So with each new major and minor releases of Django, we can update tutorial. Once the branch is stable for release, we can merge with master branch and archive that branch.

Please let me know here once the dev branch is created. Thanks for the reply.

**Comment by das-g** [comment]
I've now created branch [`django-3.1`](https://github.com/DjangoGirls/tutorial/tree/django-3.1) for this. (I've put "django" in the name, so that it's clear the number is about the Django version, not the tutorial version.)

**Comment by nikhiljohn10** [comment]
#1678 Submitted

**Comment by nikhiljohn10** [comment]
@das-g Do you think, python needs to be upgraded to version 3.8 or 3.9?

As per instruction, the user who follows this tutorial is going to install v3.9 on both Windows 8.1+ and macOS 10+. (Linux come preinstalled, so no worries there.)

Also, need to note that Pythonanywhere has [Python 3.8](https://blog.pythonanywhere.com/184/) available. 

So my question is that shall we upgrade the current tutorial version of Python 3.6 to Python 3.8 or 3.9 and Python 3.8 inside Pythonanywhere.com?

I have submitted the following PRs for migration of Django to 3.1:

- #1679 **Migration to Django 3.1**
- #1680 **Git Updated**
- #1681 **Migration to html5 and bootstrap4**

**Comment by das-g** [comment]
Let's go for 3.9 (latest stable available on python.org) locally and 3.8 (latest available on PythonAnywhere) on PythonAnywhere. As long as we (and the participants) don't use any 3.9-specific Python features, the mismatch shouldn't be a problem.

**Comment by nikhiljohn10** [comment]
Issue Resolved: https://github.com/DjangoGirls/tutorial/pull/1679

**Comment by das-g** [comment]
Let's keep this open until these changes hit `master` and https://tutorial.djangogirls.org/

**Comment by nikhiljohn10** [comment]
> Let's go for 3.9 (latest stable available on python.org) locally and 3.8 (latest available on PythonAnywhere) on PythonAnywhere. As long as we (and the participants) don't use any 3.9-specific Python features, the mismatch shouldn't be a problem.

Python 3.9.5 is the latest stable version and it is availabe when starting a new pythonanywhere account or you can change os build in setting for accessing python3.9.

I think it is ok to keep **Stable version as 3.9.5** and **Minimum version as 3.6.8.**

**Comment by adamantike** [comment]
I can see the `django-3.1` branch hasn't been updated in more than a year. Is there a list of pending stuff to do? I can help on it. Now that 3.2 should be the new LTS, IMHO that should be the version to upgrade the tutorial to.

**Comment by das-g** [comment]
> Is there a list of pending stuff to do?

I don't think we have such a list. The `django-3.1` branch wasn't intended to be as long-lived as it now became.

Such a list could maybe be compiled by figuring out what of #1678 is required for the Django version change.
