### ISSUE TITLE
Pythonanywhere Bug Issue

### ISSUE THREAD

**Issue by nikhiljohn10** [DjangoGirls/tutorial#1684]
### Issue description

https://github.com/pythonanywhere/helper_scripts/issues/31

The above bug is directly affecting the tutorial. This happened when the user did not created a requirement file. So pythonanywhere by default used the latest Django verson 3.1.3 and used pathlib inside settings. But pythonanywhere script is not updated to check if django is using pathlib or not.

### Suggestion

A temporary fix can force the user to create the following setting if Django 3.0+ is used.
```
STATIC_ROOT
MEDIA_URL
MEDIA_ROOT
```

### Language

ALL

### Operating system

Pythonanywhere

**Comment by filiplajszczak** [comment]
PythonAnywhere dev here. Thanks for the catch. We will fix it.

**Comment by filiplajszczak** [comment]
fixed in https://github.com/pythonanywhere/helper_scripts/releases/tag/v0.9.5

**Comment by das-g** [comment]
Now that this is fixed in the PythonAnywhere helper scripts, are any changes still required to the Django Girls tutorial?

**Comment by nikhiljohn10** [comment]
I'll do testing tonight and verify and close this issue.

@filiplajszczak Thanks for your quick action on the issue. I appreciate it.

**Comment by nikhiljohn10** [comment]
## Bug fix worked

Source:
```
...

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
```

Result:

```
...

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(BASE_DIR / 'media')

```

@filiplajszczak Thank you.
