### ISSUE TITLE
Mistake in Persian tutorial code

### ISSUE THREAD

**Issue by Mahsssa** [DjangoGirls/tutorial#1698]
### Issue description

Hi!

There is a mistake in modules names in Persian tutorial code and this is the link: 
https://tutorial.djangogirls.org/fa/django_urls/

When we want to create our first URL, the original code is:

`from django.contrib import path, include`
`from django.urls import admin`

`urlpatterns = [`
    `path('admin/', admin.site.urls),`
    `path('', include('blog.urls')),`
`]`

But as you know, It should be:

`from django.contrib import admin`
`from django.urls import path, include`
### Language

Persian

### Operating system

What operating system does this issue relate to?

**Comment by M-b850** [comment]
#1703

**Comment by magul** [comment]
Done in #1703
