### ISSUE TITLE
Remove bootstrap javascript from code example

### ISSUE THREAD

**Issue by MarkusH** [DjangoGirls/tutorial#170]
Adding the `bootstrap.min.js` file in http://tutorial.djangogirls.org/css/README.html#install-boostrap leads to an error:

```
Uncaught Error: Bootstrap's JavaScript requires jQuery
```

In fact, this is explained and shown in the bootstrap starter template: http://getbootstrap.com/getting-started/#template

**Comment by aniav** [comment]
Removed. Thank you! :)
