### ISSUE TITLE
Publish French translation

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#1710]
@magul Can you create the required PR, as you did in the past?

### Issue description

For an online Django Girls event on 2021-04-24 at CERN, the French translation of the tutorial including the changes of (already merged) PR #1708 will be needed. The translation has already be done [on Crowdin](https://crowdin.com/project/django-girls-tutorial/fr#).

See
- https://github.com/DjangoGirls/tutorial/pull/1708#issuecomment-806494942
- https://crowdin.com/messages/518268
- https://crowdin.com/messages/519218

It would be good to have this available ASAP, as they still need to train their coaches.

### Language

French (`fr`)

**Comment by magul** [comment]
Hi @das-g (CC: @bcopy), sorry for late reponse, I'm going to create pull request ASAP.

**Comment by magul** [comment]
Delivered in #1712. Closing that one, we will track progress in pull request.

**Comment by magul** [comment]
I've also invited @bcopy to french reviewerers group.

**Comment by das-g** [comment]
The new translation is now live on https://tutorial.djangogirls.org/fr/ :tada:

@bcopy Can you check whether everything looks alright there?

**Comment by bcopy** [comment]
Re-reading it, I see a couple of typos :see_no_evil: just minor stuff though, so I'll update Crowdin but it can wait until the next update. We're good to go !
Thanks a lot to you both !
