### ISSUE TITLE
Update Italian translation from Crowdin

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#1717]
### Issue description

The [Italian translation](https://crowdin.com/project/django-girls-tutorial/it) hit 100% on 2021-05-21. Let's import the changes into a pull-request so that they can be reviewed by @DjangoGirls/it-pr.

### Language

Italian (`it`)

@magul Can you work your magic again? (And / or maybe give some instructions on how others can do that.)

**Comment by magul** [comment]
Done in #1718. BTW do we know what we're wating for in #1711 ?

**Comment by das-g** [comment]
> BTW do we know what we're wating for in #1711 ?

Probably I simply forgot about it. :see_no_evil: Let me have a look.
