### ISSUE TITLE
Regional Language Kannada is not available in Djangogirls

### ISSUE THREAD

**Issue by ShivarajHalageri** [DjangoGirls/tutorial#1723]
### Issue description

Describe what's the problem here.

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by das-g** [comment]
Hi @ShivarajHalageri

Would you like to translate the Django Girls tutorial into Kannada? We perform and manage translations through https://crowdin.com/project/django-girls-tutorial. We can add Kannada there as a translation target language, but the actual translation would have to be done by people who master that language (best native speakers).

**Comment by ShivarajHalageri** [comment]
Ya I can do it,but the part is that I am a beginner in Django so ,,,I am
learning now once I feel I am comfortable I will revert to you.



Regards
Shivaraj B Halageri

**Comment by magul** [comment]
Ok, @ShivarajHalageri I've just added Kannada as target language in our Crowdin project: https://crowdin.com/project/django-girls-tutorial/kn#

I'm closing this issue and when tutorial will be 100% translated to Kannada we will sync it back to GitHub.

Thanks in advance!
