### ISSUE TITLE
Tutorial language

### ISSUE THREAD

**Issue by baazizkhadidja** [DjangoGirls/tutorial#1738]
### Language

Is this related to a specific language of the tutorial?
Yes

### Operating system

I can contribute to translate Django tutoriel to arabic

**Comment by magul** [comment]
Graet @baazizkhadidja !

We in fact maintain our translations on Crowdin. Arabic laguage is 99% translated and available here: https://crowdin.com/project/django-girls-tutorial/ar

Can you help us reach 100% there?

Thanks!
