### ISSUE TITLE
PythonAnywhere has eu severs for Europe now with a different prefix - login fails

### ISSUE THREAD

**Issue by DataCerealz** [DjangoGirls/tutorial#1740]
### Issue description

The tutorial mentions www.pythonanywhere.com everywhere.
Which is correct.
However, on the website of PythonAnywhere there is NO indication that there are different servers available now!
There is no button to switch from "international" to "Europe".
However, there are two identical websites:
www.pythonanywhere.com
eu.pythonanywhere.com

An account that is created on the EU version can't login on the international version and vice versa.
However, when login fails there is only "Wrong username/password"-error displayed.
This caused a lot of confusion among coaches and participants for our event in the beginning.
We could resolve this quickly but it might drive people crazy that suddenly their account "isn't working" anymore for no apparent reason. Again: on the PythonAnywhere Website there is NO indication on which server your account is or on which of the two websites you actually are.

### Language

Any.

### Operating system

Any.

**Comment by das-g** [comment]
Huh, I wasn't aware of that either. Is that new? Does one ever get to eu.pythonanywhere.com from the tutorial, e.g. through a region-dependent redirect?

Maybe raise that issue also with PythonAnywhere, as this could confuse not just Django Girls participants, but also other users of their service(s).

**Comment by nikhiljohn10** [comment]
According to the [post](https://blog.pythonanywhere.com/176/) by pythonanywhere.com, it is clear that we should not use `eu.pythonanywhere.com` at all for tutorials. It is created for individuals/companies who have concerns with GDPR compliance. It is recommended that everyone else use `www.pythonanywhere.com`. So I guess this issue can be considered resolved.

**Comment by das-g** [comment]
Ah, so participants probably ended up there _not_ by automatic redirect from URLs linked in the Django Girls tutorial, but maybe by web search?

**Comment by das-g** [comment]
I'm closing this for now. @DataCerealz please re-open and/or if you think any improvements regarding this are needed (and if so, please specify which ones).
