### ISSUE TITLE
Adding KYRGYZ language to crowdin

### ISSUE THREAD

**Issue by saikalcom08** [DjangoGirls/tutorial#1748]
### Issue description

There is no Kyrgyz language in crowdin. Could you please add it and I would like to translate tutorials to my language. 
Thank you.

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by das-g** [comment]
I've added it now: https://crowdin.com/project/django-girls-tutorial/ky

Thank you for your interest in helping with the translation! :heart:

Closing this issue now, as the language has been added as translation target to our Crowdin project for the tutorial.
