### ISSUE TITLE
Querysets are too early in the tutorial

### ISSUE THREAD

**Issue by asendecka** [DjangoGirls/tutorial#176]
I spoke with @oinopion  about tutorial and we tried to identify moments when people in our groups started to feel frustrated (except Heroku chapter). 

We agreed that the moment was Querysets chapter. Most of our tutorial is written the way that we introduce something when it's needed. But querysets are currently out of place: you don't use them yet, but still - spend a lot of time playing with them in shell. Doing stuff in interpreter is painful for attendees and they don't know how to preserve what they are doing. And the moment between "It worked" page to something cool ("admin") is too long. 

I propose to move Querysets much, much later in the tutorial where we actually need them. So after introducing urls, views and templates. Before that point simple saying `Post.objects.all()` returns all posts should be enough.

**Comment by aniav** [comment]
:+1: :grey_exclamation: :boom:
