### ISSUE TITLE
Language not listed - Danish

### ISSUE THREAD

**Issue by qvisty** [DjangoGirls/tutorial#1760]
### Issue description

Danish language not listed

### Language

Is this related to a specific language of the tutorial?
Yes - Danish

### Operating system

What operating system does this issue relate to?
All of them, web page

**Comment by das-g** [comment]
We don't have a Danish translation of the Django Girls tutorial, yet. Would you like to help create one?

**Comment by magul** [comment]
I've just updated languages on Crowdin and they contains Danish right now.

Closing this ticket and we will wait for Danish translation to be completed on Crowdin (and imported from there here).

**Comment by magul** [comment]
Link to Crowding project: https://crowdin.com/project/django-girls-tutorial/da

**Comment by qvisty** [comment]
Thank you for that 👏

Get Outlook til Android<https://aka.ms/AAb9ysg>
________________________________
