### ISSUE TITLE
Need to import `os` module - Spanish tutorial

### ISSUE THREAD

**Issue by ijpulidos** [DjangoGirls/tutorial#1763]
### Issue description

In `django_start_project` we use the `os` module when editing the `STATIC_ROOT` variable in the `mysite/settings.py` file. But the module itself has never been imported in the file.

This results in a `NameError: name 'os' is not defined` when creating the database with the command `python manage.py migrate` in the subsequent steps.

### Language

Spanish

### Operating system
I tested this on Linux, but it should be failing in all of them.

**Comment by ijpulidos** [comment]
Of course the solution is to add instructions to import the `os` module (that is, `import os`) in the first few lines of the `settings.py` file.

**Comment by das-g** [comment]
Hi @ijpulidos

Thanks for notifying us about this problem.

We maintain the translations (i.e., all languages except for English) on Crowdin at https://crowdin.com/project/django-girls-tutorial. As the [Spanish translation](https://crowdin.com/project/django-girls-tutorial/es-ES) there is quite out of date (i.e., it only has a partial translation of the current English version), snapshotting it into the GitHub repo and thus publishing it to the live site would break the result even more, as it'd be a mix of translated and untranslated parts.

Help in completing and updating the translation would be highly appreciated.

Have you tested whether the `STATIC_ROOT = BASE_DIR / 'static'` solution works with the currently published version of the Spanish instructions? If so, as a work-around, let's use that approach and manually put it into the translated files in the GitHub repo, without copying all the rest from Crowdin.

**Comment by ijpulidos** [comment]
@das-g Yes, using `STATIC_ROOT = BASE_DIR / 'static'` works!

Are you saying that changing it directly in this repo and making a Pull Request could be enough? Let me know if that's what we want to do. Thanks for the answer!

**Comment by das-g** [comment]
> Are you saying that changing it directly in this repo and making a Pull Request could be enough?

As a quick-fix / workaround, **yes**. The content of this repo is automatically rendered and published on https://tutorial.djangogirls.org/ by GitHub Actions.

If you're willing to create that PR, please do.
