### ISSUE TITLE
Crowdin approver role & updating Slovak translation

### ISSUE THREAD

**Issue by jenxness** [DjangoGirls/tutorial#1767]
### Issue description

Hi all. We have a workshop in Bratislava coming up in a week (Sunday, September 11, see https://djangogirls.org/en/bratislava_sk/), so I've been going through the Slovak translations translating any missing parts and checking the existing translations.

I've now managed to get the Slovak translation to 100%, but there are some pre-approved translations in there that are not correct and I'm not allowed to change them since I don't have sufficient rights on Crowdin. I've been trying to reach several people via email and on Crowdin to get the role to (un-)approve Slovak translations, but no luck so far.

#### TL;DR:

1. Could someone please grant me (https://crowdin.com/profile/jenx) the Crowdin role necessary for (un-)approving currently approved Slovak translations?
2. As soon as I have it, I can quickly do a final sweep to get the translations ready.
3. After that is done, I'd again need someone's assistance to pull the translations from Crowdin into the project.

Thank you in advance.

_(I realize this is all rather last minute, for which I apologize. I think many of the participants could probably follow the English tutorial as well, but it'd be so much nicer to have it in their mother tongue. I just signed up as a mentor and I wasn't aware of the state of the Slovak translation until I randomly thought to check a couple of days ago.)_

### Language

Slovak

**Comment by das-g** [comment]
Hi @jenxness. Thanks for reaching out. I'll try to contact the relevant people.

Are you user [jenx](https://crowdin.com/profile/jenx) on Crowdin?

**Comment by jenxness** [comment]
> Hi @jenxness. Thanks for reaching out. I'll try to contact the relevant people.
> 
> Are you user [jenx](https://crowdin.com/profile/jenx) on Crowdin?

Thank you! :bow: Yes, that's me.

**Comment by das-g** [comment]
It looks like [Miroslav Bagljas (mbag)](https://crowdin.com/profile/mbag) has approved/unapproved quite some Slovak translations recently. Are more left that need approving / unapproving?

Nonetheless I've made you a "proofreader" for Slovak on the Django Girls project on Crowdin. (Leaving your overall role as "translator", though.) If I understand correctly, this should allow you to approve/unapprove Slovak translation, but not those of other languages. Can you test whether you can approve/unapprove Slovak translations now, please?

**Comment by das-g** [comment]
@magul Do you think you can help with step 3 above
> After that is done, I'd again need someone's assistance to pull the translations from Crowdin into the project.

at some time before Sunday 2022-09-11, but only after @jenxness finishes step 2
> As soon as I have it, I can quickly do a final sweep to get the translations ready.

?

**Comment by das-g** [comment]
@jenxness & @mbag do you want to be added to team @DjangoGirls/sk-pr for reviewing merge requests concerning the Slovak translations? (Some mistakes are easier spotted when seeing the difference to the previously released version than when proofreading on Crowdin, while other mistakes are more apparent on Crowdin, so we like to have some checks at both steps.)

**Comment by jenxness** [comment]
@das-g Confirming that I can now approve Slovak translations, thank you for the super fast help.
I'll finish the whole approving process tomorrow, so on Wednesday we should be ready for a PR. (cc @magul)
mbag has been kind enough to help out after I reached out to him, but there's still a lot of re-approving needed (and I really didn't want to take up too much of his time).

> @jenxness & @mbag do you want to be added to team @DjangoGirls/sk-pr for reviewing merge requests concerning the Slovak translations? (Some mistakes are easier spotted when seeing the difference to the previously released version than when proofreading on Crowdin, while other mistakes are more apparent on Crowdin, so we like to have some checks at both steps.)

Sure, sign me up! :)

**Comment by mbag** [comment]
@das-g  sure, you can add me as approver to serve as backup. @jenxness  has reached out to me, so I started proofreading translations on Crowdin to have it done by upcoming weekend, but it's always better to have 2 people, just in case. 

It's been a while since I last translated DJG tutorial, does translation via Crowdin need to be exported as MR on github, or does it get incorporated to translation automatically on regular basis?

**Comment by das-g** [comment]
> It's been a while since I last translated DJG tutorial, does translation via Crowdin need to be exported as MR on github, or does it get incorporated to translation automatically on regular basis?

We export it by language and make a pull request ("PR", GitHub's name for what roughly corresponds to a "merge request" / "MR" on GitLab). Usually @magul does that using some scripts that at least partially automate the process. (AFAIK we do it that way, because Crowdin's automatic synchronization would put all languages into the GitHub repo, whether ready or not.)

**Comment by das-g** [comment]
@mbag, @jenxness Can you keep some sentence permanently untranslated until your overhaul of the translation is _actually_ finished? I'm getting hundreds of notifications by Crowdin that "Translation of the Django Girls Tutorial into Slovak has been completed" again and yet again (probably each time 100% is re-reached).

(I'd like to not disable that kind of notification, so that I will know when a language reaches 100%, but for what's happening today it doesn't seem so useful.)

**Comment by das-g** [comment]
That being said: Thank you for the great effort you're putting into improving and updating the translation! :heart:

**Comment by jenxness** [comment]
> @mbag, @jenxness Can you keep some sentence permanently untranslated until your overhaul of the translation is _actually_ finished? I'm getting hundreds of notifications by Crowdin that "Translation of the Django Girls Tutorial into Slovak has been completed" again and yet again (probably each time 100% is re-reached).
> 
> (I'd like to not disable that kind of notification, so that I will know when a language reaches 100%, but for what's happening today it doesn't seem so useful.)

Oh no, I read this too late :see_no_evil: Didn't realize it was spamming you with notifications, sorry for that. I just finished it a couple of mins ago though so there should be no more spam.

So we're now ready for the PR anytime you lovely folks find some time to create one for the Slovak translation! :sparkles: (I really appreciate your help to try to make this happen until Sunday.)

**Comment by das-g** [comment]
Here's the PR: #1768

**Comment by magul** [comment]
@das-g , I was on vacations last week and still recovering from it, I saw your pull request and will try to deliver my input as soon as will fill well enough.

Sorry for not being so responsive I used to be :/
