### ISSUE TITLE
Ebook version

### ISSUE THREAD

**Issue by ololoe** [DjangoGirls/tutorial#1785]
I cannot find anywhere ebook version of this tutorial, but I have old version on my drive. Is it gone?

**Comment by das-g** [comment]
I'm not sure. I guess we might have lost that when switching from GitBook to Honkit.

Is there any interest in using e-book versions of the tutorial?

@ekohl Would it be feasible to generate e-book files again?

**Comment by ololoe** [comment]
If you talk about me - I'm interested. If possible, please make readable CSS names, I had to edit CSS in order to read ebook on e-paper device, non black text is displayed as grey there, and edit text size too.

Can you tell me how to generate ebook from markdown?

**Comment by das-g** [comment]
> Can you tell me how to generate ebook from markdown?

From general Markdown in common Markdown dialects, [Pandoc](https://pandoc.org/) would be an option. But for the GitBook-specific Markdown this tutorial is written in, [HonKit's ebook output formats](https://honkit.netlify.app/ebook.html) are probably our best bet.

**Comment by ekohl** [comment]
https://honkit.netlify.app/ebook.html suggests we can easily do that.

By now it's also possible to generate the website in GitHub Actions without storing it in the `gh-pages` branch, so that's something I'd do before storing large files. The repository is already rather large because of it now.

I may be able to take a look tomorrow.

**Comment by ololoe** [comment]
> > Can you tell me how to generate ebook from markdown?
> 
> From general Markdown in common Markdown dialects, [Pandoc](https://pandoc.org/) would be an option. But for the GitBook-specific Markdown this tutorial is written in, [HonKit's ebook output formats](https://honkit.netlify.app/ebook.html) are probably our best bet.

Can it generate index too?
If you've done it, can you share how you did it? I want to generate ebook from some other tutorials.

**Comment by ekohl** [comment]
> I may be able to take a look tomorrow.

It wasn't tomorrow, but https://github.com/DjangoGirls/tutorial/pull/1791 should at least convert it to using GitHub Actions.

After that's merged, solving means changing the build steps in the action to also generate the eBooks. That looks rather trivial, but it doesn't mention anything about linking to it. That's something we may need to look into.

**Comment by ololoe** [comment]
Any progress?

**Comment by lapwat** [comment]
Here you go:
[Introduction_·_HonKit.epub.zip](https://github.com/DjangoGirls/tutorial/files/11311013/Introduction_._HonKit.epub.zip)

Built with [papeer](https://github.com/lapwat/papeer)

Here is the command I used:

```
papeer get --format=epub https://tutorial.djangogirls.org/en/
```

**Comment by ololoe** [comment]
@lapwat Have you checked your epub? It's only 1 page!

**Comment by das-g** [comment]
Some progress at (draft) PR #1795.

**Comment by lapwat** [comment]
@ololoe

I apologize. I forgot to use the `depth` option.

```
papeer get --depth=1 --format=epub https://tutorial.djangogirls.org/en/
```

Here you go: 
[Introduction_·_HonKit.epub.zip](https://github.com/DjangoGirls/tutorial/files/11351925/Introduction_._HonKit.epub.zip)

**Comment by ololoe** [comment]
https://github.com/DjangoGirls/tutorial/issues/1785#issuecomment-1527243485
Unfortunately your book does not support CSS. Don't know if it's really needed.

https://github.com/DjangoGirls/tutorial/pull/1795
This uses calibre as the old ebook. Has the same problem - random CSS names, and all is dumped in the same directory. So nothing is perfect.

**Comment by das-g** [comment]
> https://github.com/DjangoGirls/tutorial/pull/1795
> This uses calibre as the old ebook. Has the same problem - random CSS names, and all is dumped in the same directory. So nothing is perfect.

It uses calibre, because that's what `honkit epub` uses. We don't have the capacity to develop our own, custom collection-of-(GitBook-style)-Markdown-files-to-EBook converter. I guess we're open to alternative suggestions (preferably as pull requests), as long as they don't put too great a burden on the maintainability of the tutorial.

Is calibre actually to blame for the random CSS names or are they also present in the HTML generated by HonKit?

**Comment by ololoe** [comment]
https://github.com/DjangoGirls/tutorial/issues/1785#issuecomment-1528740796
There is no CSS in papeer epub above. Does it use honkit too?
I don't use "pull requests" and I have no idea of how to make a ebook. I'm testing what is posted here.

**Comment by das-g** [comment]
> There is no CSS in papeer epub above. Does it use honkit too?

Looking at the command line in https://github.com/DjangoGirls/tutorial/issues/1785#issuecomment-1527243485,
```bash
papeer get --depth=1 --format=epub https://tutorial.djangogirls.org/en/
```
I'd assume that it scrapes the tutorial from its online HTML version, which _is_ generated by HonKit, called here:
https://github.com/DjangoGirls/tutorial/blob/39b7faaf54db8dc9a8c0f31d7799842afd41cede/.github/workflows/deploy.yml#L29

**Comment by ololoe** [comment]
> ```shell
> https://tutorial.djangogirls.org/en/
> ```

If it scrapes, how does it lose css?

How do you convert it to epub using calibre?
