### ISSUE TITLE
Request for availing the tutorial in Amharic.

### ISSUE THREAD

**Issue by haile32293** [DjangoGirls/tutorial#1799]
### Issue description

I am from Ethiopia, and the tutorial is not available in Amharic which is the official language of the country, if we can work on it I am happy to contribute and be part of it.

### Language

It is related to Amharic.

### Operating system

What operating system does this issue relate to?

**Comment by das-g** [comment]
Contributing to the Amharic translation of the Django Girls tutorial is possible at https://crowdin.com/project/django-girls-tutorial/am

Thank you for considering to contribute!
