### ISSUE TITLE
Albanian Language

### ISSUE THREAD

**Issue by Xhevairi** [DjangoGirls/tutorial#1800]
### Issue description

Albanian language is not included on crowdin. It is to inform you so you can add the Albanian language.

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by das-g** [comment]
Added the option to translate Django Girls tutorial to Albanian on Crowdin: https://crowdin.com/project/django-girls-tutorial/sq
