### ISSUE TITLE
Jupyter Lab workspace option is confusing in RunCode

### ISSUE THREAD

**Issue by thibaudcolas** [DjangoGirls/tutorial#1805]
### Issue description

For RunCode users, the tutorial suggests two alternative workspaces: "Blank" – which is VS Code Server on Ubuntu, and Jupyter Lab. I don’t understand why there is a need to present users with a choice here – why not recommend the "Blank" VS Code on Ubuntu for everyone?

### Operating system

RunCode

---

For people choosing Jupyter Lab, there are a few more points of friction:

> Altenatively, you can go to Workspaces → New Workspace → Jupyter Lab. This will open a Python prompt which is depicted by `>>>`, you can type `exit()` to get back to the Ubuntu terminal.

This doesn’t open a Python prompt, it opens to a Jupyter Lab dashboard view. There is a "Console - Python" option on there but it’s IPython within a bespoke interface, not a standard `>>>` Python prompt.

There is a "Terminal" option that starts a bash command line, from which you can use `python` or `python3`.

They also get affected by #1739, while people who chose the "Blank" workspace aren’t.

So I’m unclear why the tutorial suggests the two options?

**Comment by das-g** [comment]
> why not recommend the "Blank" VS Code on Ubuntu for everyone?

> So I’m unclear why the tutorial suggests the two options?

Is there a reason, @amakarudze? If not, let's simply remove the suggestions to use Jupyter Lab: #1809

(And even if there is a reason, let's consider whether it outweighs the burden of yet another choice and added complexity of the tutorial, or whether we should remove Jupyter Lab anyway.)
