### ISSUE TITLE
Tutoriel français 

### ISSUE THREAD

**Issue by Brainyb20** [DjangoGirls/tutorial#1836]
### Issue description

Describe what's the problem here.

### Language

Is this related to a specific language of the tutorial?

### Operating system

What operating system does this issue relate to?

**Comment by das-g** [comment]
The French translation of the Django Girls tutorial is available at <https://tutorial.djangogirls.org/fr/>. As the original English tutorial changes from time to time, the French translation might be considerably out of date. You can help to bring it up-to-date at <https://crowdin.com/project/django-girls-tutorial/fr>.

Is there anything specific you want to report about the French translation of the Django Girls tutorial?

**Comment by das-g** [comment]
(Feel free to reply in French if you prefer.)
