### ISSUE TITLE
Request Simplified Chinese

### ISSUE THREAD

**Issue by KITAI19019** [DjangoGirls/tutorial#1841]
Thanks for your project! I would like to request that you consider adding a Simplified Chinese version so that more Chinese users can use and contribute.

**Comment by das-g** [comment]
The Django Girls tutorial has been created as is being maintained by volunteers.

A translation of the Django Girls tutorial to Simplified Chinese is in the works at https://crowdin.com/project/django-girls-tutorial/zh-CN (see https://github.com/DjangoGirls/tutorial/issues/226#issuecomment-68633077). It needs to be more complete before we can deploy it. Feel free to join the effort of translating the tutorial to Simplified Chinese there at https://crowdin.com/project/django-girls-tutorial/zh-CN, if you are able to translate from English to Simplified Chinese.
