### ISSUE TITLE
Gitbook plugin for toggling between Mac OS X / Windows / Linux versions of code examples

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/tutorial#188]
It'd be awesome if we could make some kind of tabs to toggle between Mac OS X / Windows / Linux versions of code examples. Preferably it should also save it in cookies and defaults to chosen version.

**Comment by helenst** [comment]
I've started looking into this.

**Comment by helenst** [comment]
I stopped looking at this... it is probably best to address #314 first to minimise the need for this in the first place - and then possibly revisit.

**Comment by ryangallen** [comment]
@olasitarska @helenst Hi Ladies!

What about a simple, subtle color difference between Unix and Windows examples? It does a pretty good job differentiating the two and would be a much faster fix for now. By introducing this convention at the start of the tutorial, we could eliminate the many `<p>Windows:</p>` elements as well. 

We could implement a class on the `pre` elements such as `os-unix`/`os-windows` to set a background and border color:

    pre.os-unix {
        background-color: honeydew;
        border: 1px solid lightgreen;
    }
    pre.os-windows {
        background-color: aliceblue;
        border: 1px solid lightblue;
    }

resulting in:

<img width="787" alt="screen shot 2015-09-08 at 5 23 28 pm" src="https://cloud.githubusercontent.com/assets/1379681/9749037/fd9e7314-564e-11e5-9d0c-c6d3da926801.png">

**Comment by patjouk** [comment]
Hi evreyone!

Ola found [this](https://github.com/GitbookIO/plugin-codetabs#readme) the other day. Maybe we could give it a try?

**Comment by patjouk** [comment]
PR #874 introduced a cool plugin called `sectionx`.

To create a block per operating system, use:

```
<!--sec data-title="Windows" data-id="{NameOfSection}_windows" data-collapse=true ces-->
Instruction for windows
<!--endsec-->

<!--sec data-title="Linux" data-id="{NameOfSection}_linux" data-collapse=true ces-->
Instructions for Linux
<!--endsec-->

<!--sec data-title="OS X" data-id="{NameOfSection}_OSX" data-collapse=true ces-->
Instructions for Mac OS X
<!--endsec-->
````

More instructions for `sectionx` are [available here](https://github.com/ymcatar/gitbook-plugin-sectionx).

We could also use it on those two chapters:

- [Introduction to Command Line](https://github.com/DjangoGirls/tutorial/tree/master/en/intro_to_command_line)
- [Your first Django project!](https://github.com/DjangoGirls/tutorial/tree/master/en/django_start_project)

This could be your first PR to an open source project. Ask me if you need help :wink:

**Comment by ubracklow** [comment]
I am working on the Intro to the Command Line chapter

**Comment by patjouk** [comment]
Issue fixed! Thanks @ubracklow :)
