### ISSUE TITLE
pygments highlighting for terminal sessions

### ISSUE THREAD

**Issue by freakboy3742** [DjangoGirls/tutorial#191]
The blocks of terminal commands don't make it clear what is:
* prompt
* commands that the user has to type
* responses from the server.

This is all obvious stuff for anyone with a history of bash shells, but I had a lot of problems explaining that you don't have to type the "$", and you don't have to type the "(myvenv) username:~$", and everything after the first line is response of a command

Some syntax highlighting for shell commands would be helpful.

**Comment by aniav** [comment]
GitBook uses highlight.js and it has the ability to do syntax highlighting for python and for bash. Python code looks quite pretty with that!
![Syntax Highlighting](http://i.imgur.com/P7EujRs.png)
But syntax highlighting for bash doesn't do much for our small examples.

I am also not sure if syntax highlighting solves the problem that you are mentioning and I am not sure how would we actually solve the differentiation. Maybe you have some idea on how to do that or an example screenshot of something like this?

**Comment by aniav** [comment]
We could write a plugin for that: https://github.com/GitbookIO/gitbook#plugins

**Comment by helenst** [comment]
I am going to have a look at this today at the sprint.

**Comment by aniav** [comment]
:zap: :zap: :zap:

**Comment by helenst** [comment]
It seems the bash syntax highlighting for highlight.js is for bash scripts rather than console sessions. I think what we want to do is distinguish between prompt, command and output (rather than highlight bash keywords).

Pygments has a bash session mode that does both, although seems to struggle when there are spaces in the prompt (e.g. the python anywhere prompt)

**Comment by kerstin** [comment]
Linking to #272, which is about the same issue.

**Comment by helenst** [comment]
... putting this down for now, I don't think my brain can handle dealing with gitbook plugins for now :) - currently stalled on trying to get set up to develop a plugin locally but can't seem to get that working - perhaps more npm knowledge required :-)

An alternative route might be to get a 'bash shell' highlight mode added to highlight.js which could filter down to gitbook but that's upstream x 2 and might take a while to get through.

Also, whatever solution is used here should probably also apply to python sessions (which pygments also supports)

**Comment by aniav** [comment]
I know you wanted this to be easier, but when the girls go out of our workshops they will definitelly need to browse internet and the notation with `$` in front is commonly used, and I feel it should stay.

Additionally the same comment as in #272: I think this is basically fixed as all prompt lines are now prefixed with `$` and additionally I have added a description above all code blocks explaining where this should be put: command-line, a specific file or PythonAnywhere to avoid confusion. I am going to close that for now, reopen it if you feel it's not enough :)
