### ISSUE TITLE
Tutorial assumes you know what a database-backed website actually is

### ISSUE THREAD

**Issue by freakboy3742** [DjangoGirls/tutorial#195]
The tutorial does a great job of showing you how to build a database-backed website, but skips over the part of describing what a database backed website actually is. One of my students (who is already quite versed in using Jekyll to build a blog) was unclear about what you would even use Django for - what properties of a Blog make it a suitable beginners example.

Spending some introductory time exploring what a database-backed website is, and what sort of websites you can build with Django, would help clarify this problem, and provide a framework for the rest of the tutorial.

**Comment by patjouk** [comment]
Closing it for inactivity. Feel free to reopen it and/or submit a PR :heart:
