### ISSUE TITLE
Disillusionment from getting errors

### ISSUE THREAD

**Issue by freakboy3742** [DjangoGirls/tutorial#196]
One of my students got really disillusioned with the process of using errors as a teaching tool. "I typed everything right, but then I got an error, and I kept feeling stupid". It wasn't clear to her that getting an error was actually the point of the exercise, as part of the process of teaching what _can_ go wrong, how to recover. 

She suggested using icons/coloring to identify the "Even if you do this right, it won't work" steps in the tutorial, so that when you hit one of those steps, the student isn't left with the impression that the problem is them.

**Comment by vrutkovs** [comment]
I guess rephrasing some parts (e.g. incorrect function name in http://tutorial.djangogirls.org/en/python_introduction/README.html#your-own-functions) would help. 

People usually read the chapter line by line and get confused that things break (on such an early stage). The coach has to know this situation in beforehand and warn the student (I almost filed a bug about incorrect syntax in the example)

**Comment by jacebrowning** [comment]
Could I get some feedback on this proposal? https://github.com/DjangoGirls/tutorial/pull/1225

<a href="https://cl.ly/2y0L3O3l0F0b" target="_blank"><img src="https://s3.amazonaws.com/zapier-cloudapp/items/2x2T3x2G2x053e312040/Screen%20Shot%202018-02-19%20at%208.04.02%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

If we want to go down this route we might considering changing or modifying the `filename` plugin.

**Comment by jacebrowning** [comment]
This change is now live for English: https://tutorial.djangogirls.org/en/python_introduction/#errors

**Comment by ekohl** [comment]
Awesome. This looks like a big improvement! Thanks @jacebrowning for closing this very old issue.
