### ISSUE TITLE
Go back to using gunicorn

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#206]
We switched to `waitress` after having issues with `gunicorn` and `ssl` but it turned out later that those issues were most likely caused by `heroku-push` (19df8456fdee86c008e2ae5999ddcf22135936af).

Now that we've ditched `heroku-push`, I think we should go back to `gunicorn` as well:

* It has a better name (seriously, who though "waitress" was a good name!).
* It doesn't polute the logs with its man page when you make a typo in your `wsgi.py` file.

What do you think?

**Comment by olasitarska** [comment]
oh yeah! :+1: :joy:

**Comment by keimlink** [comment]
Good proposal! 👍
