### ISSUE TITLE
Create a simple view before showing off admin and models

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#208]
The main objective of this is to have a view mounted at the root so that when we deploy the site to heroku later, there's a page that appears instead of a blank page.

It might also help make the chapter 1 more concrete (showing the request/response cycle, how you map URLs to views, ...).

I would put it at the end of chapter 8, after the reader sees the default "It works" page that Django generates.

Something as simple as:

```
def say_hello(request):
    return HttpResponse('Hello!')
```

**Comment by williln** [comment]
+1 from me! (Is it creepy that while I wait to board my flight I'm looking through old issues?)

**Comment by patjouk** [comment]
Closing it for inactivity. Feel free to reopen it and/or submit a PR :heart:
