### ISSUE TITLE
Use single/double quotes consistently

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#211]
My personal guideline is:

* Single quotes for machine-readable strings (dictionary keys, field names,  ...)
* Double quotes for human-readable strings (messages displayed to the user, ...)

**Comment by chadmiller** [comment]
I suggest closing WontFix. There is no meaning to the different quoting characters and we must not pretend there is, or through inaction let the reader infer there is. We should mix early and often and only discuss it when we first use a ' or " inside a string, on the way to talking about """ and ''' .

**Comment by olasitarska** [comment]
I'd get on board with this idea (given the fact that also no one fixed it so far). 

Any objections?

**Comment by aniav** [comment]
:zap: :zap: :zap:
