### ISSUE TITLE
Switch to files earlier in the "Intro to Python" chapter

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#212]
As I mentionned in #207, I think switching to files earlier in the chapter would be beneficial:

* The usefulness of `print()` becomes more obvious (and we can remove the weird sentence that tries to explain `repr()` vs `print()` without talking about `repr`)
* We can format dictionaries with one key:value pair per line

**Comment by mostaszewski** [comment]
I have submitted a pull request for second part of it.

**Comment by olasitarska** [comment]
Is this now resolved @bmispelon?

**Comment by olasitarska** [comment]
Confirmed with bmispelon that this is resolved.
