### ISSUE TITLE
"Template extending" assumes Bootstrap step wasn't done

### ISSUE THREAD

**Issue by encukou** [DjangoGirls/tutorial#214]
The "Delete everything else other than what's inside the body and then also delete `<div class="page-header"></div>`" is wrong since we're using Bootstrab classes at this point

**Comment by aniav** [comment]
I'm reading it again and again and I don't see why. We are adding the `page-header` class in the CSS chapter, so the statement doesn't assume the bootstrap section wasnt' done. Am I missing something? :cactus:

**Comment by encukou** [comment]
Right; looks like things changed in the meantime :)

**Comment by aniav** [comment]
:sparkles:
