### ISSUE TITLE
Create a suggested schedule for small groups of learners

### ISSUE THREAD

**Issue by willingc** [DjangoGirls/tutorial#220]
The workshop tutorial is excellent. Thank you for all your good work. :bouquet: 

I am working with a Women in Engineering group at a local university to go through the tutorial. For situations where a full day workshop is not feasible, it would be great to have a rough timeline/outline of how to share the tutorial in a series of 2 hour meetings. I will share our experience as we work through the tutorial over the next month.

**Comment by aniav** [comment]
Hey @willingc do you have any update on this? Do you have any idea on how the tutorial should be split into a schedule?

**Comment by aniav** [comment]
I am closing this because there is no update on it for more then a few months. Feel free to comment and reopen if this becomes active again :)
