### ISSUE TITLE
virtualenv installation not covered

### ISSUE THREAD

**Issue by krother** [DjangoGirls/tutorial#221]
In Chapter 7 'Django Installation' it is assumed that 1.) you have Python 2.x installed. 2.) you have virtualenv installed. Both are not explicitly explained before.

Moreover, after I installed virtualenv on Ubuntu 14, I had to type

python -m virtualenv myvenv

instead of

python -m venv myvenv

**Comment by aniav** [comment]
It seems to be fixed in current version. Thank you :)
