### ISSUE TITLE
git commit -m "My Django Girls app"  will not work

### ISSUE THREAD

**Issue by Alex-G-89** [DjangoGirls/tutorial#224]
Hello, 

I have dfficulties with chapter 12. Deploy !
More precisely in Git subchapter. 

When I am to create a new git repository and save my changes it won't work. So I go to my console and run these commands:

$ git init
Initialized empty Git repository in ~/djangogirls/.git/
$ git add .

All good but when I run this command: 

$ git commit -m "My Django Girls app"

I get this message: 

**\* Please tell me who you are.

Run

   git config --global user.email "you@example.com"
   git config --global user.name "Your Name"

to set your account's default identity. 
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address(got 'Ana@Ursi,(none)')

(avevn) C:\Users\Ana\djangogirls>

Till this point I hope I followed your instructions in this chapter correctly. Do not know. I may have done some errors before and consequences appeared now ?

regards,
alex

**Comment by kerstin** [comment]
@Alex-G-89, I saw you closed the issue the same day you opened it - did you manage to resolve your git problems? Or was that an accidental close?

**Comment by Alex-G-89** [comment]
Hy,

I resolved the issue the same day and closed it.

Thanks for your concerns.
Alex
Dne 16. jan. 2015 15:55 je oseba "Kay" <notifications@github.com> napisala:
