### ISSUE TITLE
There is no translations of Chinese

### ISSUE THREAD

**Issue by defrur** [DjangoGirls/tutorial#226]
There is no translations of Chinese on crowdin.com. I want to translate it into Chinese

**Comment by olasitarska** [comment]
That's awesome @defrur! 

Here it is: https://crowdin.com/project/django-girls-tutorial/zh-TW

Let me know if you need help!

**Comment by defrur** [comment]
I 'm Sorry. I mean Chinese  Simplified exactly. 
@olasitarska

**Comment by olasitarska** [comment]
No worries, done! :)
