### ISSUE TITLE
Tutorial in french

### ISSUE THREAD

**Issue by nokomis** [DjangoGirls/tutorial#228]
I need to translate the tutorial in french DjangoGirls Paris.
Can you tell me how to do that?

Have a nice day!

**Comment by olasitarska** [comment]
Hi @nokomis!

That's awesome! :+1: I just added French to [Crowdin, our translation platform](https://crowdin.com/project/django-girls-tutorial/fr). You can simply create an account there and start translating!

Let us know if you need anything! :)
Ola
