### ISSUE TITLE
Links between chapters broken due to i18n

### ISSUE THREAD

**Issue by MarkusH** [DjangoGirls/tutorial#235]
I assume that, due to the recent i18n refactoring, the inline links between chapters don't work anymore. E.g. on http://tutorial.djangogirls.org/en/python_introduction/README.html#python-prompt "Intro to Command Line" returns a 404 same as "code editor" on http://tutorial.djangogirls.org/en/python_introduction/README.html#save-it

I haven't yet figured out if gitbook does some internal Markdown magic, but it looks like the images are properly shown.

**Comment by olasitarska** [comment]
Yeah.. I'm afraid we will need to go through the book and fix the links. Thanks for reporting!

**Comment by MarkusH** [comment]
Thanks :smile:

A :cookie: for you

**Comment by olasitarska** [comment]
There is a :cookie: emoji?! How could I not know it!

![](http://media.giphy.com/media/UUVqDm2xhyU36/giphy.gif)
