### ISSUE TITLE
Adding Farsi translation

### ISSUE THREAD

**Issue by gikfi** [DjangoGirls/tutorial#236]
Can we get started with the Farsi translation?

**Comment by olasitarska** [comment]
Hi @gikfi! 

That's awesome! :) I just added it here: https://crowdin.com/project/django-girls-tutorial/fa. Crowdin shows it as Persian, is that all right?

Good luck! Shout if you need help. :sparkles: 

Ola

**Comment by gikfi** [comment]
Yeah Farsi/Persian are the same thing. Thanks
Omid
