### ISSUE TITLE
translation of Django Girls Tutorial into Russian

### ISSUE THREAD

**Issue by aprilegirl** [DjangoGirls/tutorial#238]
Hello!
My name is Olga and I would like to contribute in translation of Django Girls Tutorial into Russian

**Comment by olasitarska** [comment]
Hi @aprilegirl!

That's awesome :) :sparkles: I just added this translation here: https://crowdin.com/project/django-girls-tutorial/ru

Let me know if you need any help! Here is a :penguin: for you :)

Good luck,
Ola
