### ISSUE TITLE
Delete/Disable old version of the tutorial

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#244]
At the workshop in Brno today, @kvbik ended up on an old version of the tutorial at https://www.gitbook.com/@asendecka.

We should try to delete/disable or at least add a warning there so people don't accidentally go through this old version.

**Comment by kvbik** [comment]
:+1: :D

**Comment by olasitarska** [comment]
@asendecka Ola, could you click the buttons? :)

**Comment by asendecka** [comment]
I deleted whatever I was able to do :). I cannot see any old versions of full tutorial, though. I see only a Django Girls main one. Not sure if GitBook is caching it somehow. Anyway, I'm closing it now and let's hope it's enough.

**Comment by olasitarska** [comment]
I see it's deleted now. Thanks!
