### ISSUE TITLE
Chapter 5: inequality operator is not described

### ISSUE THREAD

**Issue by vrutkovs** [DjangoGirls/tutorial#245]
In 'Compare things' section from Chapter 5 most operators are explained, except the inequality (!=), which later on used in 'Boolean' section and might confuse the newcomer

Credit goes to Natalya

**Comment by bmispelon** [comment]
Good ideas.

If there's time left at the end, would Natalya like to submit a pull request to fix this? I'm happy to help her go through the process. :penguin:

**Comment by bmispelon** [comment]
Fixed in 86ef9033bb44e282fbc1cd392275b878f145f3f0. Thanks all! :koala:
