### ISSUE TITLE
Code comments are not covered

### ISSUE THREAD

**Issue by vrutkovs** [DjangoGirls/tutorial#250]
Lines starting with # are not explained, which confuses some students

**Comment by bmispelon** [comment]
This is a good idea.

I think an ideal point to introduce this could be when we switch to files in the middle.

Thanks! :racehorse:

**Comment by williln** [comment]
I think this can be closed? http://tutorial.djangogirls.org/en/django_urls/index.html

**Comment by olasitarska** [comment]
@williln you're right, thanks :)
