### ISSUE TITLE
Language German

### ISSUE THREAD

**Issue by dralexxm** [DjangoGirls/tutorial#251]
Dear all,
I'am a DJango beginner and found your nice tutorial. During my studies learning Django I will find some time for German translations within your tutorial.Please get me prepared to do so.
Thanks
Alexander

**Comment by kerstin** [comment]
Hi @dralexxm, German was already added as supported language on Crowdin, which is used for translating the tutorial in other languages. See issue #234. I believe you simply have to sign-up there to start contributing.

**Comment by olasitarska** [comment]
Yes, what @kerstin said is correct. 

Thanks @dralexxm, you're great. We look forward to your contributions! :sparkles:

**Comment by dralexxm** [comment]
Dear Django Grils,
tried to sign on with my old user / pw to go on with German translation gut cant sign in. Please help.
Best regards
Alexander

**Comment by aniav** [comment]
@dralexxm have you tried resetting your password on crowdin? This nothing we can help you with as we don't manage crowdin accounts.
