### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by janfabry** [DjangoGirls/tutorial#258]
Can you start a Dutch translation on Crowdin? I'm thinking about using the tutorial for CoderDojo, where we teach kids to program. So it won't be all girls, but it will be all enthusiasm!

**Comment by olasitarska** [comment]
Hi Jan! 

That's amazing! Of course! I just added language here: https://crowdin.com/project/django-girls-tutorial/nl

Dankjewel! :sparkles: :tulip: 
Ola
