### ISSUE TITLE
Make Gitter more visible in the tutorial

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/tutorial#260]
I think it'd be really nice if Gitter would be more visible in the tutorial. I see way too many people looking for help on twitter, when they could just join us on gitter to get help :) This could possibly be implemented as a gitbook plugin instead of just adding it everywhere in the tutorial.

**Comment by patjouk** [comment]
Closing it for inactivity. Feel free to reopen it and/or submit a PR :heart:
