### ISSUE TITLE
Wrong chapter for deployment

### ISSUE THREAD

**Issue by andyosuna** [DjangoGirls/tutorial#262]
Chapters 20 and 21 ("Extend your application" and "Django Forms") point the reader towards the end of chapter 15 for deployment info, while it is located in chapter 11.

I'm too lazy to do a pull request so I'm just leaving this here :)

**Comment by aniav** [comment]
I think the idea of pointing the reader to that chapter is to remind her where the information is. Do you think this is not correct? How we can improve that?

**Comment by andyosuna** [comment]
yeah, but the deployment info is no longer in chapter 15, at least I didn't see it there....

**Comment by aniav** [comment]
Ah, you're right! Fixing that. Than you! :)
