### ISSUE TITLE
end of chapter 7 implies code editor isn't installed yet

### ISSUE THREAD

**Issue by andyosuna** [DjangoGirls/tutorial#263]
The end of chapter 7 ends with "you need a nice program to write your code in...", while the code editor was already installed in chapter 4.

**Comment by andyosuna** [comment]
I believe you have moved the chapters around since the last time I did the tutorial, so I'll just keep reporting little things like these when I see them, if that's okay with you guys...

**Comment by bmispelon** [comment]
You're right, that's a leftover from when the chapters were arranged in a different order.

Thanks for pointing it out (and keep'em coming)! :rocket: :smile_cat:
