### ISSUE TITLE
Design feedback: Make button to collapse side menu more obvious

### ISSUE THREAD

**Issue by mattaustin** [DjangoGirls/tutorial#271]
I received some feedback from the Perth Django Girls event regarding the side navigation menu, and that it would be nice to collapse it - as typically the tutorial is open in a window whilst working on code alongside. I realised later that the '4 lines' button did exactly this, but maybe the icon could make the action more obvious, or even be part of the nav divider, rather than floating at the top of the page.

**Comment by olasitarska** [comment]
As this is a gitbook's design and we've got no way to influence this, I think we can close this.
