### ISSUE TITLE
Design feedback: Style command prompt input/output differently

### ISSUE THREAD

**Issue by mattaustin** [DjangoGirls/tutorial#272]
Some feedback from the Django Girls Perth event, we had a few people who didn't realise the difference between the console/command prompt input and expected output (they continued to type in the 'output' text written in the docs).

Maybe we should style or separate the input/output text across the documentation?

**Comment by danielquinn** [comment]
A lot of this can be fixed by enforcing the convention of prefixing "input" lines with `$`:

```bash
    $ python myscript.py
    This is the output of my script
```

It's pretty standard in forums and other documentation styles, so this would have the added benefit of making things less confusing when they're not in the tutorial.

**Comment by aniav** [comment]
I think this is basically fixed as all prompt lines are now prefixed with `$` and additionally I have added a description above all code blocks explaining where this should be put: command-line, a specific file or PythonAnywhere to avoid confusion. I am going to close that for now, reopen it if you feel it's not enough :)
