### ISSUE TITLE
i would like to add korean

### ISSUE THREAD

**Issue by sjyun** [DjangoGirls/tutorial#275]
Dear DjangoGirls

first of all, thank you for making good tutorial

when i read this tutorial(english version) that got me thinking 

i want to get korea version

Here volunteer

![2015-03-11_10-47-21](https://cloud.githubusercontent.com/assets/1390605/6588928/0a282c9e-c7dc-11e4-9be6-e5f5457ae539.png)

**Comment by bmispelon** [comment]
Hi @sjyun,

I just added the Korean language to our crowdin page: https://crowdin.com/project/django-girls-tutorial

Thanks for your support and good luck! :hamster: :rocket:
