### ISSUE TITLE
Give the language selection a friendly mood

### ISSUE THREAD

**Issue by GloverDonovan** [DjangoGirls/tutorial#276]
I was surprised that the homepage ( http://tutorial.djangogirls.org/ ) was so simple.

I suggest that some sort of styling be added to this page to drive the overall mood for a user's initial impression.

Example: Bigger font, custom background, flat button styles, etc.

**Comment by bmispelon** [comment]
Hi,

I like the idea, I agree that we can definitely improve on this.
The tricky bit will probably be to figure out how to do this with gibook (the platform we use for the tutorial).

Thanks! :elephant:

**Comment by GloverDonovan** [comment]
There is a class on the homepage called `.book-langs-index`. Would it be possible to write classes specifically targeting the elements inside of this class?

**Comment by bmispelon** [comment]
I don't know if Gitbook lets us inject a custom CSS anywhere.

If we could do that, then that selector looks like a good place to start indeed.

**Comment by aniav** [comment]
https://github.com/GitbookIO/gitbook/issues/788

Bam!
