### ISSUE TITLE
Check if we could use cmder for Windows users

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/tutorial#277]
http://bliker.github.io/cmder/

**Comment by patjouk** [comment]
The project moved [here](https://github.com/cmderdev/cmder). Is it something we still want to do or should we close this issue?

**Comment by aniav** [comment]
I think it would be a huge improvement to the learning process but it needs some time to complete. I would love to work on some bigger task while sprinting on DUTH but it's a question if I will be able to... :)

**Comment by twwilliams** [comment]
I'm going to go through the tutorial and see how well it works using PowerShell on Windows 10 instead of Git Bash. I'll make notes of any problems and workarounds, if available, and then report back to you here.

**Comment by ekohl** [comment]
I'm leaning to closing this given its age. I'm also in favor of using as little extra tools as possible since we already see students struggle to install applications.

**Comment by aniav** [comment]
True. Also power shell probably is a better solution now if anything else✌️
