### ISSUE TITLE
At the point where we are asked to get all posts, we would probably have existing posts

### ISSUE THREAD

**Issue by aychedee** [DjangoGirls/tutorial#282]
>>> Post.objects.all()
    [  ]

Would probably be populated with the posts that the user created at an earlier step... Same with the user objects a little later. They've already created a superuser

**Comment by phalt** [comment]
@aychedee :+1: Spotted that literally seconds after you, made a PR for it!

**Comment by bmispelon** [comment]
PR merged.

Thanks everyone! :bee:
