### ISSUE TITLE
Tutorial versioning.

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/tutorial#296]
I think we should version the tutorial for example for each workshop that is happening we tag the changes with a specific version/date. For now the translators won't know from what point they should check for changes and so I believe staying up to date with them is currently impossible even if someone would want to. What do you think?

**Comment by olasitarska** [comment]
I thought today exactly about that. Soo yes, :+1: from me!

**Comment by phalt** [comment]
:+1: great idea

**Comment by aniav** [comment]
Done that now!
https://github.com/DjangoGirls/tutorial/tree/v1.0.0%2B20150329

**Comment by keimlink** [comment]
Great idea. Maybe you could also maintain a changelog?

**Comment by aniav** [comment]
Yes. I believe that we will introduce it when pushing next release :)
