### ISSUE TITLE
Add gitbook-plugin-edit-link

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/tutorial#299]
More information: http://plugins.gitbook.com/plugin/edit-link

Could be easier for readers to fix the bugs they see in the tutorial.

**Comment by aniav** [comment]
This plugin currently doesn't work with multilanguage books. I have created a pull request to add it:
https://github.com/rtCamp/gitbook-plugin-edit-link/pull/2

We will have to wait for it :)
