### ISSUE TITLE
Add gitbook-plugin-codeblocks-filename

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/tutorial#300]
It's sometimes confusing which file you should edit, so gitbook plugin like [gitbook-plugin-codeblock-filename](http://plugins.gitbook.com/plugin/codeblock-filename) could be very helpful. However, that's gonna be very time consuming to implement in various translations :( 

It looks like that on gitbook: 

![](http://cl.ly/image/0f3D071E3i1H/Screen%20Shot%202015-03-28%20at%2017.33.17.png)

**Comment by aniav** [comment]
https://github.com/litmon/gitbook-plugin-codeblock-filename/pull/1 bam!
