### ISSUE TITLE
How to start Python 3 from the command-line on Windows.

### ISSUE THREAD

**Issue by hjwp** [DjangoGirls/tutorial#317]
One of the many annoying thing about Windows is that, when you install different versions of Python, they all still have their main binary named "python.exe".   There is no "python3" command.

In my book, I solve this by telling people to use a symlink, but that only works if you use git-bash (cf #314) 

    ln -s /c/Python34/python.exe /bin/python3.exe 

http://chimera.labs.oreilly.com/books/1234000000754/pr02.html#_required_software_installations

If we're not recommending git-bash, we either need to tell people to run python with 

    c:\Python34\python.exe

which is annoying, or figure out some windowsey version of an alias or symlink?  I suppose one option is

    cp c:\Python34\python.exe c:\Python34\python3.exe

ugh, windows.

**Comment by hjwp** [comment]
Incidentally, this was all prompted by this line in the python chapter:

http://tutorial.djangogirls.org/en/python_introduction/README.html

>To start playing with Python, we need to open up a command line on your computer. You should already know how to do that -- you learned it in the Intro to Command Line chapter.

I'm not sure either the command line intro chapter, or the installing python chapter, actually explicitly cover how to start python in a command line.

**Comment by aniav** [comment]
This has been resolved in 1802d83. Thank you! :sparkles:

**Comment by robbie70** [comment]
@aniav 
I am not sure how this has been resolved - I am still having this issue. I am using running v3.6.4 and following a Python tutorial and trying to call "python3" from the windows (cygwin) command line but I get the message "command not found". I dont see a python3.exe in the installation directory either only a "python3.dll".
If I am missing something can you please add some  comments here.

**Comment by robbie70** [comment]
I think I found a solution on Stackoverflow, see this link,

[(https://stackoverflow.com/questions/8841110/how-to-enable-python-interactive-mode-in-cygwin)]

**Comment by hjwp** [comment]
I think the current status is that the tutorial assumes that Python 3 is the only version of Python you have on your computer, or at least the most recently installed one, so that, on Windows, `python` will just run Python 3.

anyone who's doing anything more complicated (eg running cygwin) is assumed to be more competent than a total beginner, so they are trusted to debug their own issues!

but, if you need, the Windows Python installer does offer a shortcut called `py`, so (from a normal, non-cygwin, windows command prompt) you can run:

```
py -3.6  # will launch python 3.6
py -2  # will launch python 2, if it's installed 
```
