### ISSUE TITLE
suggestion: Replace Heroku with Openshift

### ISSUE THREAD

**Issue by comzeradd** [DjangoGirls/tutorial#322]
The part of the tutorial about deploy inevitably promote/advertise a certain commercial provider. I think its closer to Django Girls spirit to promote at least an Open Source solution.

So my suggestion would be to switch to [OpenShift](https://en.wikipedia.org/wiki/OpenShift), a fully Open Source PaaS. It works pretty much the same as Heroku, so it's not much of work to amend the tutorial. I'm willing to help on that.

**Comment by olasitarska** [comment]
That's indeed interesting. I've never used OpenShift, however, this seems to be more complicated than Heroku: http://appsembler.com/blog/django-deployment-using-openshift/

@bmispelon @aniav @asendecka, would love to hear your input here.

**Comment by keimlink** [comment]
I agree it would be great not to use one of the most popular and well advertised PaaS like Heroku. OTOH this makes it easier for the users of the tutorial to find help.

About OpenShift: Installing a Ruby gem is a whole new can of worms that introduces a lot of new questions and problems. Some users may not have Ruby installed. That's the first thing that needs to be taken care of. Of course there are different Ruby versions. So you have to check if the right Ruby version is installed. Next thing is that you usually want to use a tool like Bundler to install gems. So the Heroku toolbelt looks like an easier way of installing the required software.

**Comment by comzeradd** [comment]
All of the commands on the tutorial above that use the `rhc` tool can be processed through OpenShift's web interface. There is no need for installing ruby. You can setup your application using a browser and then use git to deploy.

**Comment by Matt-Deacalion** [comment]
Probably good timing for this. As it looks like they could [start charging](http://readwrite.com/2015/04/01/heroku-price-hike-rumor). Nothing concrete yet, but doesn't hurt to be ready.

**Comment by bmispelon** [comment]
The deploy chapter has been rewritten using PythonAnywhere and we moved the Heroku version to an [extension](https://github.com/DjangoGirls/tutorial-extensions/).

I think a similar OpenShift extension could work too if you'd like to contribute it.

Thanks! :penguin:
