### ISSUE TITLE
About contributing

### ISSUE THREAD

**Issue by ahmadina** [DjangoGirls/tutorial#323]
hi, can i use https://crowdin.com/project/django-girls-tutorial for translation and after push in fork of DjangoGirls/tutorial repository in my github account and make pull request?

**Comment by olasitarska** [comment]
Yes! :) :+1: 

I'll publish a guide of what's needed to be done after you download translations from Crowdin (I'm not sure you can do that, but if you can't, I can download and send it to you via email). You can also see what's need to be fixed here if you look at commits: https://github.com/DjangoGirls/tutorial/pull/312

**Comment by ahmadina** [comment]
yes i can download translation file in Crowdin [image](https://www.dropbox.com/s/sduj8drib5431fb/Screen%20Shot%202015-04-06%20at%2019.36.33.png?dl=0). at first i'll completed translation in Crowdin then i'll download it and push in fork  and make pull request. 
thank you :+1:

**Comment by ahmadina** [comment]
Can anyone answer my question? ;)
