### ISSUE TITLE
The Django template "One more thing" section is not refering to the correct chapter about Heroku deployment

### ISSUE THREAD

**Issue by charettes** [DjangoGirls/tutorial#327]
The [One more thing](https://github.com/DjangoGirls/tutorial/blob/34d60058ff9aeddc1f87b583e721e4f3ba88fe51/en/django_templates/README.md#user-content-one-more-thing) section suggest to look at the end of chapter 15 if the reader forgot how to deploy.

This should point to the end of the chapter 14 instead. Maybe we could add an hyperlink to appropriate chapter at the same time?

**Comment by aniav** [comment]
This has been fixed with the introduction of Python Anywhere. Thank you! :)
