### ISSUE TITLE
We should add a mention about queryset chaining.

### ISSUE THREAD

**Issue by charettes** [DjangoGirls/tutorial#328]
The ["Queryset" section of the "Dynamic data in templates chapter"](https://github.com/DjangoGirls/tutorial/blob/34d60058ff9aeddc1f87b583e721e4f3ba88fe51/en/dynamic_data_in_templates/README.md#user-content-queryset) state that a the reader already created a list of filtered **and** ordered blog posts in the previous chapter which is not the case.

Would it make sense to either alter the wording of the sentence or add a section to the previous chapter explaining queryset chaining?

**Comment by donaldharvey** [comment]
Working on this... I think adding another section makes the most sense :)

**Comment by donaldharvey** [comment]
see #441
