### ISSUE TITLE
Translation into Japanese

### ISSUE THREAD

**Issue by mamix1116** [DjangoGirls/tutorial#331]
Hi, My name is Mami.  I'd like to translate the tutorial into Japanese and start DjangoGirls events in Tokyo.  Can you add Japanese to Crowdin?

**Comment by aniav** [comment]
Hi Mami,
I have created a Japanese translation on Crowdin. It is available here:
https://crowdin.com/project/django-girls-tutorial/ja

Hugs! :sparkles:

**Comment by mamix1116** [comment]
Cool!  Thank you very much!!
