### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/tutorial#341]
We should probably create an additional chapter with upgrade instructions for people who get back to our tutorial after a few months gap.

**Comment by souravsingh** [comment]
I would like to work on this

**Comment by das-g** [comment]
It might not be possible to come up with generic upgrade instructions that also account for changes in the tutorial itself.

The best bet if the tutorial has changed significantly (as it e.g. has with #1190) is probably to re-start from the beginning in a new directory / pushing to a fresh GitHub repository. (One can re-use the pythonanywhere account, overriding previous deployments there.)

**Comment by ekohl** [comment]
I agree with @das-g that it's hard. Usually redoing the steps is also a good refresher for students. That's what I've seen my repeat students do. That's why I'm closing this.
