### ISSUE TITLE
Farsi Translation

### ISSUE THREAD

**Issue by ShadiTaghian** [DjangoGirls/tutorial#349]

**Comment by asendecka** [comment]
I'm not language expert, so sorry if I am wrong - we have Persian language in Crowdin. Is Farsi different from Persian? If so, we will try to make it happen :).

**Comment by ShadiTaghian** [comment]
I don’t know about Persian language in Crowdin, but Farsi and Persian are the same in Iran. There was an old tribe in Iran named “Pars”, because of them the country was named Pars and the people were called “Parsian” (means from Pars). During the years the word Parsian changed to Persian. That’s why Iranian call themselves and their language Persian.
The word Farsi is actually Parsi, but after Arabian attacked Iran it changed to Farsi. (Arabs don’t have “p” sound in their alphabet). So in fact both words Persian and Farsi are from same root “Pars”.
I hope you find it useful.

**Comment by bmispelon** [comment]
Hi,

Thanks for educating us, I love learning about stuff like this :)

The Persian/Farsi language is added to crowdin so you can contribute there directly: https://crowdin.com/project/django-girls-tutorial/fa

Happy translating! :earth_africa: :capital_abcd:
