### ISSUE TITLE
Crowdin, duplicated folders

### ISSUE THREAD

**Issue by lancelote** [DjangoGirls/tutorial#356]
After the last build update there is a new `en` folder with the same directory structure as in the root. What is the purpose?

Also, we have `how_the_internet_works` and `how_internet_works` folders now. One is needless, I believe.

**Comment by kerstin** [comment]
I don't know anything about Crowdin, but ```how_internet_works``` was the original name of that chapter, which was later corrected to ```how_the_internet_works``` if that's of any help.

**Comment by bmispelon** [comment]
Hmm, it could be that I messed up something when re-uploading to crowdin.

Not sure how to fix that :(

**Comment by lancelote** [comment]
Any progress? = )
Want to finish Russian translation.

**Comment by tricoder42** [comment]
Sorry, I'm busy at the moment :flushed: Will look at it during weekend, ok?

**Comment by lancelote** [comment]
Sure, thank you @tricoder42 !

**Comment by aniav** [comment]
Crowdin allows to rename a folder. I have removed `how_the_internet_works` and renamed `how_internet_works` into `how_the_internet_works`. I checked for translations being removed but it seems crowdin was showing the newer folder as empty so nothing should have been lost :)
