### ISSUE TITLE
Virtualenv needs to be activated when running commands on pythonanywhere

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#360]
In [chapter 14](http://tutorial.djangogirls.org/en/html/README.html#pull-your-new-code-down-to-pythonanywhere-and-reload-your-web-app), the instructions don't mention that you need to activate your virtualenv before running `./manage.py collectstatic`.

**Comment by aniav** [comment]
I see this is fixed! :balloon:
