### ISSUE TITLE
Translating the book to Tamil

### ISSUE THREAD

**Issue by durairajaa** [DjangoGirls/tutorial#363]
Just opening the issue to create tamil version of the book 

Tamil is not listed on crowdin

**Comment by tricoder42** [comment]
@durairajaa I've just added Tamil language. Please register at crowdin and I'll assign you as a translator.

**Comment by tricoder42** [comment]
Also, because you are the first person who wants to translate tutorial into new language, I would assign you as a "Language manager". Could you write me your name and email at tomas.ehrlich@gmail.com so I can add you to our list at https://github.com/DjangoGirls/translation-guide/pull/3/files?

**Comment by durairajaa** [comment]
The required details are as below


Name: DURAIRAJAA

email: durairajaa1992@gmail.com

**Comment by tricoder42** [comment]
Language added @ Crowdin.
