### ISSUE TITLE
Requesting a Translation for Bangla(Bangladesh)

### ISSUE THREAD

**Issue by tahmidrafi** [DjangoGirls/tutorial#364]
Requesting a Translation for Bangla(Bangladesh)

**Comment by rapoulson** [comment]
Hi @tahmidrafi :wave:! I've just added Bengali on Crowdin. Please register with Crowdin and I'll add you as a translator. As you'll be the first translator for this language, you'll also be our "language manager". Please send me your name and email at rebecca.poulson@gmail.com and I'll add you to the list you see here https://github.com/DjangoGirls/translation-guide/pull/3/files
Thanks! :smile:

**Comment by tahmidrafi** [comment]
Great! I've sent you an email with my name. :smile:

**Comment by aniav** [comment]
Can this issue be closed? I believe you can close issues when the language is created on Crowdin :)

**Comment by tricoder42** [comment]
Ok, sounds reasonable :bouquet: :)
