### ISSUE TITLE
Gitter chat room guidelines

### ISSUE THREAD

**Issue by zanderle** [DjangoGirls/tutorial#368]
I've been noticing that lately a lot of questions go by unanswered in Gitter. I think by adding some structure/guidelines to the chat room, we could improve this greatly. Not rules, since we don't want to make it difficult to ask questions, just some guidelines for people who are looking for help. Things like "make sure you state your question clearly", "tell us, if you've tried something and it hasn't work" and so on. 

This way, it would be much easier to answer all the questions, and people would receive much better help.

**Comment by asendecka** [comment]
Hi Žan,

Thank you for contacting us! We've noticed that Gitter is not that
active anymore, too :(.

Your ideas are great and we will talk about them during our next
hangout :). I think the main problem is to find a good place for these
"advices/tips" for people who asks questions on Gitter.

Have a lovely day!

Thank you!
Ola Sendecka

2015-05-30 19:54 GMT+01:00 Žan Anderle <notifications@github.com>:

**Comment by zanderle** [comment]
Great! :)

Yeah, maybe Gitter should look into adding a feature like that…

PS loved your talk and illustrations yesterday! :)

**Comment by ekohl** [comment]
Because of its age I'm leaning to closing this issue. Thoughts?
