### ISSUE TITLE
Double underscores are difficult to see

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#371]
Learners often don't realise when they have to type a double underscore, e.g. around \__str__ on the models section, and type a single underscore instead - it's easy for a coach to point out what is wrong, but could be a source of frustration for somebody working alone. Perhaps the letter-spacing could be adjusted, or a different font used so that there is a space between the underscores?

**Comment by olasitarska** [comment]
Good point. I'm not sure how we can change css on Gitbook, but we could also just add a note to clear that out :)

**Comment by williln** [comment]
@olasitarska @helenst Looks like this comment was added? https://github.com/DjangoGirls/tutorial/tree/master/en/django_models  

Can this issue be closed?

**Comment by asendecka** [comment]
Yes! Thank you @helenst & @williln! :rocket: :star: :sparkler:
