### ISSUE TITLE
Placeholder text confusion

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#372]
Where username placeholders are used, e.g. in Python Anywhere setup, learners get confused and type their username inside the angle brackets - perhaps this could be clarified.

**Comment by kerstin** [comment]
Could you possibly link the file where the confusion first occurs? Would be great, thanks!

**Comment by helenst** [comment]
Sure - I think it is all actually in the deploy section: https://github.com/DjangoGirls/tutorial/blob/master/en/deploy/README.md - there are a few occurrences in there.

**Comment by helenst** [comment]
I'll have a look at this.
