### ISSUE TITLE
Put the tutorial through Hemingwayapp

### ISSUE THREAD

**Issue by phalt** [DjangoGirls/tutorial#375]
[Hemingwayapp](https://hemingwayapp.com) is like a linter for English grammar. We should pass the tutorial through it to see if we can improve readability :grin: 

Completed chapters:
- [x] Intro to the internet
- [x] Command line
- [x] Python installation
- [x] Python introduction
- [x] Django admin
- [x] Django installation
- [x] Django models
- [x] Deploy
- [x] Django URLs
- [x] Django views
- [x] Intro to HTML
- [x] Django ORM
- [x] Dynamic data in templates
- [x] CSS
- [ ] Template extending
- [ ] Extend your application
- [ ] Django forms
- [ ] What's next?

**Comment by phalt** [comment]
@videocard and l will be working on this today at the sprint!

**Comment by kerstin** [comment]
Ohh, that sounds cool! The link didn't load for me, looks like the domain can't handle https. http://www.hemingwayapp.com/ worked.

**Comment by phalt** [comment]
@aniav myself and @videocard managed to get through half the chapters, but we couldn't finish the rest :(

**Comment by aniav** [comment]
You have already done a lot! It's good that you have written it here, so someone else will be able to get through the other chapters :spaghetti: :sunny: :cactus:

**Comment by phalt** [comment]
Continuing with this today - hopefully I can get the last few chapters done :grin:

**Comment by wmoline** [comment]
Django ORM section done and merged.
Dynamic data in templates done and waiting for review :smiley_cat:

**Comment by phalt** [comment]
Wahoo! Thanks @wmoline

**Comment by wmoline** [comment]
Dynamic data in templates and CSS done and merged.

**Comment by phalt** [comment]
@wmoline you have the power! Feel free to tick them off as you go :)

**Comment by bittner** [comment]
Should a reference to using the Hemingwayapp be put into the README, maybe?

Can the Hemingwayapp create a report of the hot-spots that primarily need attention? I couldn't find this confirmed on its website. If there were a tool like that any such checks could be added to an automatic build process (similar to Landscape.io for Python code).

**Comment by ekohl** [comment]
Any update on this?

**Comment by fltfx** [comment]
Closing due  to no further action
