### ISSUE TITLE
Pre-workshop tasks

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#376]
The coaching guide suggests getting learners to complete a set of install and reading tasks before the workshop. I think it would be nice to have this as a list in the tutorial so that coaches can point their learners at a clear list of instructions for getting started, and links to all the right places.

Also, these tasks are scattered throughout the first few chapters (and in some cases, later on in the deploy section) - perhaps they could be brought together into a series of pre-workshop steps before the main material. I don't know if this is too workshop-centric (i.e. is it still good for people working through on their own?) but perhaps it is nice to get all the install and setup done first anyway.

**Comment by olasitarska** [comment]
Yeap, I agree. Maybe we could do it somehow using Gitbook 2.0 templating? http://help.gitbook.com/format/conrefs.html

**Comment by helenst** [comment]
So I am not sure what is best here. Could either:

1. Move all this material to the start and assume that pre-setup is best for everybody

2. Keep the install sections where they are and set up some includes so that there is a "pre-workshop tasks" page which includes all the setup tasks, but they are also included in their original places, (we can have a note that says skip this section if you already did the pre-workshop tasks) - It is possible but I don't know if I'm over complicating it!

**Comment by helenst** [comment]
Here's some text I sent out to my learners before the workshop which might be useful content to start with - it's based on http://coach.djangogirls.org/intro/index.html

In the workshop you will be building a blog, and there are a few setup
tasks in the tutorial which would be good to work through beforehand
so that you are ready to start coding on the day. These are:

* Install Python -
http://tutorial.djangogirls.org/en/python_installation/README.html

* Set up virtualenv and install Django -
http://tutorial.djangogirls.org/en/django_installation/README.html

* Install a code editor -
http://tutorial.djangogirls.org/en/code_editor/README.html

* Install Git -
http://tutorial.djangogirls.org/en/deploy/README.html#installing-git -
Just work through that section, stop when you get to "Starting our git
repository" - you'll do that on the day.

* Go to https://github.com and sign up for a new, free user account.

* Go to https://www.pythonanywhere.com/ and sign up for a free
beginner account. This is where you'll be uploading your blog code to.
When choosing your username, bear in mind that the blog's URL will
take the form yourusername.pythonanywhere.com, so either choose your
own nickname, or a name for what your blog is all about.

There are also a couple of chapters it would be good to read:

* Chapter 1 "How the internet works" -
http://tutorial.djangogirls.org/en/how_the_internet_works/README.html

* Chapter 2  "Introduction to the command line" -
http://tutorial.djangogirls.org/en/intro_to_command_line/README.html

* Chapter 6 "What is Django?" -
http://tutorial.djangogirls.org/en/django/README.html

**Comment by williln** [comment]
I think this can be closed now? https://github.com/DjangoGirls/tutorial/tree/master/en/installation

**Comment by olasitarska** [comment]
Thanks @williln!
