### ISSUE TITLE
It's easy to miss the dot

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#377]
When you create the Django project, there is a dot at the end of the command which is easy to miss (I did when I ran through the tutorial and so did one of my learners!) and then you end up with everything in the wrong places. Perhaps more attention could be drawn to it :-)

**Comment by kerstin** [comment]
Would be cool if you could link this, too. (: (First occurrence of the problematic part.)

**Comment by helenst** [comment]
It is in here: https://github.com/DjangoGirls/tutorial/blob/master/en/django_start_project/README.md about a third of the way down - the startproject command.

**Comment by aniav** [comment]
Hmm, we have already put a note about the dot there. Do you have any idea how we could make it even more visible? :)

**Comment by helenst** [comment]
Ah :-) I may have missed that due to skim-reading a little too much, I'm surprised my student missed that too.

I think it probably shouldn't be in the same block as the note about virtualenv - you start reading, see that it's about having the virtualenv enabled... "yup, I've done that" and skip the rest of the block.

I think it should be separate, and closer to the command itself, maybe part of "In the console you should run..." sentence (maybe more important than pointing out about not typing the prompt - especially if that problem can be addressed more globally - missing the dot will subtly mess things up for you later on rather than just giving you bash errors).

**Comment by aniav** [comment]
Ok. Separating this from the block about virtualenv might help. Yesss! :)

**Comment by mcbhenwood** [comment]
Hi, I'm looking for easy issues to pick off to begin with. This kind of docs issue is ideal. What's the protocol for claiming issues in this repo?

**Comment by kerstin** [comment]
Hm, I read something about people assigning themselves, but I don't see how, so maybe only the owners can do that...

**Comment by olasitarska** [comment]
@mcbhenwood unfortunately, github doesn't allow non-committers to assign them to issues, bummer. I guess the comment here is enough, I'll also add an "in progress" label.

**Comment by mcbhenwood** [comment]
Thanks @olasitarska, I'll pick this up tomorrow morning when the sprints start again.

**Comment by aniav** [comment]
I believe this is now fixed. Thank you! :)
