### ISSUE TITLE
Syntax highlighting in non-english versions

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#379]
Syntax highlighting is missing in some of the non-english tutorials (e.g. python blocks are not marked up as such)

**Comment by kerstin** [comment]
I'm bothering you about links again! :P

I'm unsure about changes to the other languages though – I don't know if there's a bidirectional link between Crowdin and GitHub. Would be great if someone could let us know if it's ok to simply edit the files via git or if that will break something. (:

**Comment by helenst** [comment]
Hi! :) I can give a couple of examples 

e.g.
https://github.com/DjangoGirls/tutorial/tree/master/es/django_models
https://github.com/DjangoGirls/tutorial/tree/master/fr/django_views

but as far as I can tell it seems to be pretty much throughout the non-english tutorials.

**Comment by kerstin** [comment]
AH! Sorry, in my mind I was confusing the issue with code blocks/snippets being displayed as such.

I believe this has to do with how the code blocks are formatted. Will have a closer look (later; busy right now).

**Comment by ekohl** [comment]
Is this still an issue?
