### ISSUE TITLE
Inconsistent formatting for Keyboard keys and commands.

### ISSUE THREAD

**Issue by Videocard** [DjangoGirls/tutorial#381]
There is inconsistent formatting for keyboard keys and commands. For example, on [this page](http://tutorial.djangogirls.org/en/intro_to_command_line/README.html) the 'tab' key is formatted like this:

`tab`

But on [this page](http://tutorial.djangogirls.org/en/django_admin/README.html) the 'enter' key is written both as:

enter 

and

'Enter'

I think this should follow one common style, personally I think the code highlighted format seen on the first page looks better.

**Comment by aniav** [comment]
Yess! :+1:

**Comment by yamila-moreno** [comment]
Hi! I would like to help here. I would like to check the expected changes:
- all occurrences of tab key should be displayed like `tab`
- all occurrences of enter key should be displayed like `enter`
- all occurrences mean "in each language".

If it's ok, I could start with the changes. Cheers!

**Comment by aniav** [comment]
It definitelly is okay @yamila-moreno :)

**Comment by yamila-moreno** [comment]
Great, I'm on it :D

**Comment by yamila-moreno** [comment]
PR: https://github.com/DjangoGirls/tutorial/pull/406 :D
