### ISSUE TITLE
Incomplete/unclear sentence

### ISSUE THREAD

**Issue by Videocard** [DjangoGirls/tutorial#382]
In file python_installation/README.md line 19

See [this commit](https://github.com/DjangoGirls/tutorial/commit/a4670a521f086db53104eb2ea520669aa5c197fb)

:smile:

**Comment by mcbhenwood** [comment]
Looking at this now. I don't think it's incomplete, I think it is just badly worded. Will issue a PR shortly.

**Comment by mcbhenwood** [comment]
https://github.com/DjangoGirls/tutorial/pull/390

**Comment by aniav** [comment]
:+1: :whale:
