### ISSUE TITLE
Spanish language HTML needs fixing

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/tutorial#389]
The HTML in the Spanish version has whitespaces after the `<` and before the `>` signs in all many files. This needs fixing. Example: http://tutorial.djangogirls.org/es/django_templates/README.html

**Comment by yamila-moreno** [comment]
Hi! I'm starting working with this. (but I think I cannot assgin to myself).

**Comment by aniav** [comment]
Yeeah, I've checked that, and non-commiters can't assign themseves :(

**Comment by yamila-moreno** [comment]
Ok, don't worry, I'm working on it already :+1:
