### ISSUE TITLE
Link on tutorial index page does not redirect properly 404 error

### ISSUE THREAD

**Issue by willingc** [DjangoGirls/tutorial#399]
A 404 error on contributing link on this page: http://tutorial.djangogirls.org/en/index.html

![screen shot 2015-06-05 at 1 34 04 pm](https://cloud.githubusercontent.com/assets/2680980/8014954/ceccace6-0b89-11e5-9276-c3aa5ba45db2.png)

I would fix but I'm not sure with the recent move of Contributing docs what is the correct destination.

I :heart: DjangoGirls :)

**Comment by aniav** [comment]
That has been fixed in 6b89369. Thank you very much for reporting this! :sparkling_heart:
