### ISSUE TITLE
Indonesian translate for django girls

### ISSUE THREAD

**Issue by falgifaisal** [DjangoGirls/tutorial#407]
Hi, i'm Falgi Faisal one of your follower for django tutorial. I found your tutorial is nice and easy to learn for beginner like me. So, can this be translated to Indonesian language ?

Sorry if my english is bad. And thanks for attention

**Comment by aniav** [comment]
@rapoulson @tricoder42 I tried to assign you both to this but github allows only for one assignee, but you know what to do :dancer: :dash: :dart:

**Comment by tricoder42** [comment]
@falgifaisal Hi! :smiley:  I've just added Indonesian language to [Crowdin](https://crowdin.com). If you want to help translate it, just register there and I'll send you an invite :incoming_envelope:.

Thank you! :smile: :rocket: :tada: :guitar:

**Comment by falgifaisal** [comment]
Hello. I've registerered in crowdin but i don't get the invitation. So what
does it mean with "closed #407" ?

Thank you :D
Pada 29 Jun 2015 19:19, "Anna Warzecha" <notifications@github.com> menulis:

**Comment by tricoder42** [comment]
That means, that I made mistake, forgot about you and left this ticket open for too long :cry: Sorry.

I've just sent you the invitation. Have received it?

**Comment by falgifaisal** [comment]
Yes just checked it. Thanks :)

2015-06-30 12.24 GMT+07.00, Tomáš Ehrlich <notifications@github.com>:
