### ISSUE TITLE
Django Girls Tutorial should be translated into Hindi.

### ISSUE THREAD

**Issue by RatanShreshtha** [DjangoGirls/tutorial#412]
Django Girls Tutorial should be translated into Hindi.

**Comment by olasitarska** [comment]
Are you volunteering to translate it? :)

**Comment by RatanShreshtha** [comment]
Yes

**Comment by olasitarska** [comment]
That's awesome! We will create a translation on Crowdin asap :) 

@rebkwok @tricoder42

**Comment by RatanShreshtha** [comment]
i don't know how to do that ?

**Comment by tricoder42** [comment]
I'll do that. Just register on [Crowdin](https://crowdin.com) and I'll invite you as a translator :smiley: 

Thank you! :rocket: You're awesome :smile:

**Comment by RatanShreshtha** [comment]
I have registered.

**Comment by tricoder42** [comment]
Good, I've sent you an invitation :envelope_with_arrow:. Have you received it?

**Comment by tricoder42** [comment]
@RatanShreshtha Also, this is the direct link to Hindi translation of tutorial https://crowdin.com/project/django-girls-tutorial/hi

**Comment by tricoder42** [comment]
@RatanShreshtha Alright, I see everything works fine :+1: Feel free to ask if you need something and good luck! :tada: :fireworks:
