### ISSUE TITLE
Translate via Git

### ISSUE THREAD

**Issue by za** [DjangoGirls/tutorial#415]
Hello, 

I am interested to translate to Indonesia language (ID). Can I do it via git? I copy the `en` dir to `id` dir and start translating there.

**Comment by rapoulson** [comment]
Hi za! We manage all of our translations via [Crowdin](https://crowdin.com/project/django-girls-tutorial). This allows you to collaborate with the other people working on the Indonesian translation. Let me know what email address you'd like the invitation sent to and I'll send one your way!

Thanks! :smile:

**Comment by za** [comment]
@rapoulson OK, this is my email address: `za at python.or.id`
