### ISSUE TITLE
Incorrect commit message

### ISSUE THREAD

**Issue by medullaskyline** [DjangoGirls/tutorial#419]
In the django_templates section, the (commit message) [https://github.com/DjangoGirls/tutorial/blob/master/en/django_templates/README.md#one-more-thing] `added views to create/edit blog post` should be something like `modified templates to display posts from database`.

**Comment by williln** [comment]
Thanks @medullaskyline! I updated this in [422](https://github.com/DjangoGirls/tutorial/pull/422); hopefully it will get merged :+1:

**Comment by asendecka** [comment]
Thank you @medullaskyline for spotting it and @williln for pull request :D. You are amazing! :mega: :strawberry: :rainbow:
