### ISSUE TITLE
Translation for Bahasa Malaysia

### ISSUE THREAD

**Issue by ati83** [DjangoGirls/tutorial#423]
Hi,

I would like to help in translating the Django Girls Tutorial for Bahasa Malaysia. Would appreciate your help to add it to the language list in crowdin. 
Thanks!

**Comment by tricoder42** [comment]
Hi @ati83 ,
thank you for your help! :tada: I need your email to send you invitation to crowdin (or crowdin username if you are already registered). 

Also, I couldn't find "Bahasa Malaysia" language at Crowdin. There are Malay, Malayam and English Malaysia. I guess it's Malay, right?

Thank you very much! :sun_with_face:

**Comment by ati83** [comment]
Hi @tricoder42 

Yes, it's Malay :) I have sent an email to you. Thanks!

**Comment by tricoder42** [comment]
Email sent. Welcome aboard! :boat:
