### ISSUE TITLE
Romanian language tutorial

### ISSUE THREAD

**Issue by ndomnicu** [DjangoGirls/tutorial#437]
This language is used officially by both Romania and Republic of Moldova.
I'm currently working on the translation to Romanian. Can you please guide me how to submit my translation for voting once I finish?
Thank you in advance.

**Comment by rapoulson** [comment]
Hi @ndomnicu :wave: Thanks for working on the Romanian translation! We use a service called Crowdin to manage our translations. This makes it easy for you to collaborate with other translators. I've added Romanian as a target language, and if you can give me your email address, (either as a reply on this thread, or in an email to translations@djangogirls.org) I'll set you up with access to Crowdin. Thanks again! We're very excited to have you on board! :ship:

**Comment by ndomnicu** [comment]
Thank you!
My email is ndomnicu@gmail.com

**Comment by ndomnicu** [comment]
I have received the invitation, thank you :)
By the way, some friends will also like to join the translation. What is
the procedure for that?
Thank you in advance.

**Comment by tricoder42** [comment]
Awesome :+1: 

Just register at Crowding and tell us your emails... We need to invite you to DjangoGirls team, that's all.

Welcome and thank you :rose: :tada: :sparkles:

**Comment by ndomnicu** [comment]
Thank you!
For now, it's just culevalex@gmail.com
For the future e-mails of the people who want to join, should I also
contact you?

**Comment by tricoder42** [comment]
Anyone from Django Girls, but the best is to contact me (tomas.ehrlich@gmail.com) or @rapoulson.

Invitation sent :incoming_envelope: Thanks!

**Comment by ndomnicu** [comment]
Thank you!
