### ISSUE TITLE
Wrong "let's start at the beginning" link

### ISSUE THREAD

**Issue by lancelote** [DjangoGirls/tutorial#445]
The "[let's start at the beginning...](http://tutorial.djangogirls.org/how_the_internet_works/index.html)" link at the [tutorial gitbook page](https://www.gitbook.com/book/djangogirls/djangogirls-tutorial/details) is wrong (404)

### Actual
http://tutorial.djangogirls.org/how_the_internet_works/index.html

### Expected
http://tutorial.djangogirls.org/en/how_the_internet_works/index.html

**Comment by kojoidrissa** [comment]
When I find this section in the Github repo (both [my fork](https://github.com/kojoidrissa/tutorial/blob/master/en/README.md) and the [main repo](https://github.com/DjangoGirls/tutorial/tree/master/en)), the link is correct.  But on the [Gitbook tutorial page](https://www.gitbook.com/book/djangogirls/djangogirls-tutorial/details), the link is wrong.

So, I'm left with two questions regarding why I can't resolve this.
1.  Is it that I don't have access to the "Gitbook source"? Sorry, I'm not very familiar with Gitbook internals.
2.  Is something happening as Gitbook turns the repo source INTO a book that gets published online?

**Comment by aniav** [comment]
The links generated by Gitbook are valid only when reached from http://tutorial.djangogirls.org. They will be wrong when reached from github and when reached from gitbook.com. I believe we can't do anything about that because the links are relative and generated by the gitbook builder.

**Comment by kojoidrissa** [comment]
Anna,

Thanks for the explanation.
