### ISSUE TITLE
Linux Virtual Environment issue

### ISSUE THREAD

**Issue by yakonoops** [DjangoGirls/tutorial#455]
Installation beginning chapter.
Venv does not exist error on (unknown) light linux installation.

Followed instructions here:
https://github.com/pypa/virtualenv/issues/506

and then use virtualenv instead of venv in tutorial.

(note I see now there is a troubleshooting part in section 8, these directions might have worked too, but I did not have user try them at the time. and the error was different)

**Comment by JaimeLynSchatz** [comment]
also related to #469  and #489.

Do we want to update the tutorial with this? We could have a subsection on local vs. hosted/production machines and include instructions to:

1. set up the virtual environment on the Linux virtual machine (some very helpful instructions are here, as well: https://help.pythonanywhere.com/pages/VirtualEnvForNewerDjango/ )
2. create posts for the production blog 

The tutorial mentions this distinction and it's implied in the section on the .gitignore file - we're ignoring the db that holds the posts, but the topic could use little more detail (hopefully without becoming overwhelming, of course.)

It could also be an opportunity to dive a little deeper (or at least take another pass) at reviewing the idea behind the relationship between a programmer's local machine, their hosted git repository and the production website.

If you want a PR, hit me up :smile_cat:

**Comment by aniav** [comment]
@JaimeLynSchatz I know it's been quite some time since your comment here but go ahead and create a PR for the topic mentioned here. Ideally for one for each issue so we will be able to discuss the solution :)

**Comment by aniav** [comment]
The tutorial has changed quite a bit since this issue was created. We now have instructions for different operating systems and different distros. I will close that for now as it hopefully was resolved in the process :)
