### ISSUE TITLE
Django Girl Tutorial to Traditional Chinese from English

### ISSUE THREAD

**Issue by awei1108** [DjangoGirls/tutorial#458]
hi,
Due to I don't see the Traditional Chinese on the language list, I may suggest list this one on https://crowdin.com/project/django-girls-tutorial.
I would like to be volunteer to translate the tutorial to Traditional Chinese version since I have learned a lot from this guide. I want to share this for more people who wanna to learn about web framework.

**Comment by aniav** [comment]
@tricoder42 @rapoulson I think this is for you :)

**Comment by rapoulson** [comment]
Whoohoo! :confetti_ball: Sorry I missed this one! Traditional Chinese has been added to our target languages @awei1108 If you need to be set up with credentials (sounds like you might already have access?) or have any questions, please email us at translations@djangogirls.org. Happy to have you on board! :smile_cat:
