### ISSUE TITLE
Translation to Arabic language 

### ISSUE THREAD

**Issue by ayaseen** [DjangoGirls/tutorial#461]
Hello, 

My name Amjad Yaseen,  and I would love to contribute to this tutorial as a translator to Arabic language. 

This will help alot of Arab Python lover.

My contact :
amjad.a.yaseen@gmail.com

Thanks

**Comment by rapoulson** [comment]
:wave: Hi Amjad! Thanks for volunteering! I've added Arabic as a target language and sent you an invitation to Crowdin, our translations service. If you need any help getting started, feel free to send us an email at translations@djangogirls.org. Happy translating! :confetti_ball:
