### ISSUE TITLE
Add /static to .gitignore

### ISSUE THREAD

**Issue by treyhunner** [DjangoGirls/tutorial#471]
One of the students ran `python manage.py collectstatic` on their local computer (they were confused about where to run it originally).  The student then ran `python manage.py collectstatic` on PythonAnywhere.

When continuing through the tutorial they did a `git add -A .` which added `/static` (generated from the `collectstatic`) to git.  After pushing and then pulling on the server, git then complained that `static` already existed but was untracked by git.

I think the solution to this would be to add the following line to `.gitignore`:

    /static

**Comment by olasitarska** [comment]
:+1:
