### ISSUE TITLE
Windows 10 unsafe script error in installation chapter.

### ISSUE THREAD

**Issue by phalt** [DjangoGirls/tutorial#477]
When Windows 10 users try to runs scripts (the first occurrence is usually Virtualenv's activate script), they sometimes get an "unsafe script warning". This is due to the Windows 10 security features. 

We should make mention of the solution in the tutorial. It is given in the error but only after scrolling through some complex Microsoft documentation. Assigning myself to this one, at a workshop so I can't do it right now :)

**Comment by LeahAT** [comment]
Link: https://technet.microsoft.com/library/hh847748.aspx

To change execution policy: Set-ExecutionPolicy -ExecutionPolicy <PolicyName>

Default is "Restricted" - to make it work can use "Unrestricted".

**Comment by aniav** [comment]
The fix for this issue was added in bb5225fe24f9f942dd064ea0157b525ed0f5234f. 🎅
