### ISSUE TITLE
Install git on OSX using the OS itself (XCode tools)

### ISSUE THREAD

**Issue by quinox** [DjangoGirls/tutorial#480]
Installing `git` via git-scm.com doesn't work on OSX Yosemite (10.10.5) without a right-click "bypass security" type of installation:

![screen shot 2015-09-19 at 20 07 17](https://cloud.githubusercontent.com/assets/739770/9977482/38f29508-5f0a-11e5-8707-91023586425b.png)

There's  much easier way of installing it anyway, simply type `git` in the console and there will be a popup if you want to install to install git, after choosing "install" and waiting a bit you'll have a functional `git` command:

![terminal](http://www.amsys.co.uk/wp-content/uploads/software-update-autopkg.png)
![popup](http://www.amsys.co.uk/wp-content/uploads/git-command.png)

(As a side note, using Safari with PythonAnywhere is a bad idea since it fails to render the bash consoles properly, eating output and leaving users confused.)

**Comment by domenkozar** [comment]
Yeah, I've had the same experience with git+osx. Maybe we should encourage to use homebrew or Nix?

**Comment by sogen** [comment]
the Github app also can install command-line tools

**Comment by aniav** [comment]
It seems the same thing is being discussed in #540. I will close that issue as somewhat duplicate. Thank you! ⚡️
