### ISSUE TITLE
I want to translate djangogirls document into thai langquage

### ISSUE THREAD

**Issue by naowal** [DjangoGirls/tutorial#483]
Hello,I'm naowal
         I want to translate djangogirls document into thai langquage. my email address is way.serongang@gmail.com. please send me detail and how to work.

Regard
Naowal

**Comment by rapoulson** [comment]
:wave: Hi Naowal! Thai has been added as a target language on Crowdin and I've sent you a translator invite from Crowdin. Thanks for your help! :smile:

**Comment by naowal** [comment]
I'm start now. ^^
