### ISSUE TITLE
Triangular relationship among student's machine, github and pythonanywhere confusing

### ISSUE THREAD

**Issue by xyzisinus** [DjangoGirls/tutorial#489]
Although I explained to the students why github is in the picture and told them there were two consoles (local and remote), the students were still confused at times where to type the command.  To solve this problem I propose that ALL work is done on pythonanywhere ONLY.  This will cut the work on the student’s computer and github out of the picture.  The command console on the student’s computer is a thorny spot, even without the triangular relationship mentioned above, because three platforms (Linux, Windows and Mac OS) have to be covered.  When working on pythonanywhere, the standard bash shell is provided.   With this change alone, the size of the tutorial should shrink to half of its current size.  That will give the students more time to digest the material and allow the tutorial to expand into actual programing instead of rote copying.

If the curriculum unfortunately stays its current course, I will recommend that
1. Explain upfront with a diagram why github is needed and why the student has to move her work to pythonanywhere (so her friends can see her work).  Again here you'll find it's hard to justify why the student has to work locally on her computer after all because pythonanywhere's vm is perfectly usable!
2. The commands typed into the local console and pythonganywhere’s console should be distinguished with different colors instead of the current uniform gray.

**Comment by olasitarska** [comment]
I think it's gives students a powerful feeling if you can say to them at the end: "today you used tools I use everyday in my job, there is nothing that will surprise you now", and we very much wanna stick to this, even if it means we need to explain more things :) 

I agree with suggested changes to distinguish commands, and explain Github-local-PythonAnywhere combo more.

**Comment by aniav** [comment]
Point 2 is done - each code block has now its own description of where should it be typed or where should a student see it.

Point 1 is still to be done.

**Comment by ekohl** [comment]
4ebb18b9a05dba3ecb372b6c3eb40ec03fb36317 added a note about this so I'm closing this now.
