### ISSUE TITLE
Tutorial Does Not Cover How to Keep Python 2 

### ISSUE THREAD

**Issue by sylphiae** [DjangoGirls/tutorial#498]
I think it would be useful for those of us who want to keep Python 2 to also have a section in the "Python Installation" section that covers Python 3 setup. I first tried going through the tutorial on Windows and had a hard time configuring my environment variables. I'm using linux now since it's a lot easier. Python 3 may be the future, but many classes still teach Python 2 and it's useful to be able to know how to switch between the two.

**Comment by aniav** [comment]
@sylphiae I agree this might be useful but this tutorial usually is run by people who don't have any knowledge about Python and it would just bring more confusion about the versions. I don't feel we should put such information in the main tutorial, maybe in the extensions as the methods to keep python 2 in various operating systems will be different :)
