### ISSUE TITLE
New syntax introduced and unexpained

### ISSUE THREAD

**Issue by knyghty** [DjangoGirls/tutorial#500]
Someone came into #django today asking what the difference between `{% endblock %}` and `{% endblock content %}` is, as the latter is introduced in the Template Extending section, but isn't explained at all (as far as I can see).

To avoid confusion, I'd suggest either removing it or explaining why it's used here but not elsewhere.

Log: https://botbot.me/freenode/django/2015-10-27/?msg=52833480&page=10

**Comment by olasitarska** [comment]
:+1: for removing it! :)

**Comment by olasitarska** [comment]
Thanks for reporting @knyghty! :tulip:
