### ISSUE TITLE
Translation and possible Improvements

### ISSUE THREAD

**Issue by rizzo36** [DjangoGirls/tutorial#501]
Hi folks,

i just wanted to say thank you for creating such a wonderful tutorial. It really made a lot of things clearer and much easier to understand and I still use it as a reference of information.  I finished the main tutorial and the extension and wanted to mention a couple of things I think could be improved (if that’s not too bold)
Concerning the extension:
-   Step 4 is installing postgresql as a DB but you never say why. What are its ad - and disadvantages and why switch now from what we had and not continue using it?
-   At the end of step 3 I would add a reminder of what you have to type in to upload it to pythonanywhere including the usual push to git and pull from pythonanywhere and especially the “makemigration blog” and “migrate blog” commands as we did that in the main tutorial all the time
-   Step 3 “ comment model” under “moderating your comments” it says "And of course fix imports." Maybe you should name the file and what to write as import. I am not sure which file it was right now but can find out if you need to know.
  General:
-   In the main tutorial you start by setting up a virtual environment. I always ask myself what happens if there is a newer Django version and I want to update to that. How do I do that? Is there a risk of losing my data in the process etc..  
-      I finished the german translation over the last couple weeks. 99% of the text can stay like it is but there are some inconsistencies due to several ppl translating it. Sometimes terms like "view" or "form" get translated and sometimes not. I prefer keeping technical terms in english as one will always read about them when he/she is looking for information on the inet. It would be great though if someone could just read the finalized text once for minor mistakes. Then it`s ready for publish.

Hope that helps you clear some things up for ppl like me. 

Rizzo

**Comment by kerstin** [comment]
'Sometimes terms like "view" or "form" get translated and sometimes not. I prefer keeping technical terms in english as one will always read about them when he/she is looking for information on the inet.'

I haven't read your translation nor do I know what's usually used in German materials, but I think I would stick with how the terms are usually called in German tutorials/intros/documentation etc. (: (Though maybe that's what you meant anyway?)
