### ISSUE TITLE
"Your first pull request" extension tutorial

### ISSUE THREAD

**Issue by patjouk** [DjangoGirls/tutorial#511]
The aim of this tutorial extension will be to help attendees who want to fix typo they found in the tutorial. By doing this, they will learn out to make a pull request but also make some doc writing ;)
assigned to @thatdocslady :bouquet:

**Comment by thatdocslady** [comment]
Apparently I don't have commit rights, I've been working on my own fork and submitting PRs until now. @bmispelon, is there any way to give me enough karma to be able to have issues assigned to me but without giving me the power to break the internets? :)

**Comment by olasitarska** [comment]
@thatdocslady assigned!

**Comment by patjouk** [comment]
I don't have the time to work on it. I'm closing this issue for now.
