### ISSUE TITLE
Slovene

### ISSUE THREAD

**Issue by MikuS13** [DjangoGirls/tutorial#515]
Hi,

I would like to translate tutorial in Slovenian language. Can I do that ? If yes, how do I start ? Can I make changes directly on your Github repository in new language map or locally ?

Best regards

Samo

**Comment by rizzo36** [comment]
Hey MikuS13
here is the link for all languages
https://crowdin.com/project/django-girls-tutorial

**Comment by MikuS13** [comment]
Thanks. I somehow managed to ignore this link when browsing DjangoGirls website :)
