### ISSUE TITLE
Incorrect language variable in Crowdin

### ISSUE THREAD

**Issue by patjouk** [DjangoGirls/tutorial#531]
To be sure that two languages don't conflict on Crowdin, we should change `%two_letters_code%` in [Crowdin configuration](https://github.com/DjangoGirls/tutorial/blob/master/crowdin.yaml) to `%locale%`. More detail on Crowdin configuration file [here](https://crowdin.com/page/cli-tool).

**Comment by magul** [comment]
Done in https://github.com/DjangoGirls/tutorial/commit/79256cfd9595c66e43988440204168c427acc48f
