### ISSUE TITLE
homebrew for installation on os x

### ISSUE THREAD

**Issue by ejulcsi** [DjangoGirls/tutorial#540]
What do you think about installing with Homebrew in case of OS X? Wouldn't it be good to add it to the tutorial? It can make things easier but also can be hard to understand and implement for beginners..

**Comment by kerstin** [comment]
I don't know if tptb would want it to go into the main tutorial, but I guess it would make sense to add instructions somewhere for people possibly already using Homebrew (who, at the same time, aren't experts at using it).

I had installers (Ruby/Rails ones, iirc) mess with my system before so I've been using Homebrew for years and was intent on continuing to use it for the DG workshop also, so I couldn't do the installation part for the workshop in parallel with the others and mostly figured it out on my own.

**Comment by patjouk** [comment]
That looks like a cool idea. Can someone test it with a beginner? If it's working, can you also make a PR? Thanks! :sparkles:

**Comment by das-g** [comment]
Which of the [required software](https://tutorial.djangogirls.org/en/installation/#installation) can be installed with homebrew and which software would benefit from that way of installation and how (i.e. what would be better?) and which would better not be installed with homebrew, even if possible?

**Comment by fltfx** [comment]
hi! commenting almost a decade later about this topic. I actually added information about installing homebrew and using it to install git in #1848 . This resolves the original issue.
