### ISSUE TITLE
Upgrade to Python 3.5

### ISSUE THREAD

**Issue by bmispelon** [DjangoGirls/tutorial#564]
We should update the tutorial to use Python 3.5.

I don't believe it requires changing any code, just the download instructions.

This should be done once PythonAnywhere supports Python 3.5.

**Comment by ctorres-nearsoft** [comment]
Indeed, Python 3.5 didn't have any substancial changes affecting this tutorial.

**Comment by craigsdennis** [comment]
Just verified that [PythonAnywhere still doesn't support 3.5](https://www.pythonanywhere.com/forums/topic/2907/)

**Comment by zsiciarz** [comment]
FYI: they support 3.5 [since April 2016](http://blog.pythonanywhere.com/132/).

**Comment by olasitarska** [comment]
Awesome :)

**Comment by aniav** [comment]
Introduced in 8491971 🎉

**Comment by zsiciarz** [comment]
Relevant here - I've bumped Python version in a few more places. https://github.com/DjangoGirls/tutorial/pull/801
