### ISSUE TITLE
Step 9 startproject confusion

### ISSUE THREAD

**Issue by MCrutch** [DjangoGirls/tutorial#572]
This part here causes some confusion:

> `django-admin.py` is a script that will create the directories and files for you. You should now have a directory structure which looks like this:

While django-admin.py isn't preceded by (venv) it still seems like it should be typed into the command prompt (which, of course, produces some perplexing output). Additionally, there is no way to confirm that you've created the directory structure successfully. Perhaps adding "The" to the beginning of the sentence, and/or giving instructions on how to confirm that the project was created correctly.

**Comment by aniav** [comment]
@MCrutch thank you for you input on that matter. I think this is now more clear due to some changes made in the meantime. The usage of django-admin is described more precisely. I am closing the issue :)
