### ISSUE TITLE
Upgrade to Django 1.9

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/tutorial#597]
Any volunteers eager to run through tutorial on Django 1.9? :)

**Comment by kojoidrissa** [comment]
Ola,

I can give it a run this weekend. Not sure if I'll be able to get to it
sooner.

**Comment by avezou** [comment]
Same here. I can do it this weekend.

**Comment by olasitarska** [comment]
Awesome, go for it :)

**Comment by cgl** [comment]
Do you need a run on Mac Os as well?

**Comment by kojoidrissa** [comment]
Çağıl,

My primary machine is a Mac, so that's the platform I was going to use. But
I think I've also got a Windows 8.1/10 machine here somewhere I could try.

Which OS are you going to use? We might as well try to get THAT covered
too. :-)

**Comment by avezou** [comment]
I will most likely be using Ubuntu. I do have a Windows 7 VM, but I don't I'll be going that route.

**Comment by kojoidrissa** [comment]
@cgl I'll be using a Mac too. But I might try it on Windows as well. I need to do SOMETHING with my Windows box. :-P

**Comment by cgl** [comment]
@kojoidrissa I have OS X El Capitan 10.11.2

**Comment by kojoidrissa** [comment]
@olasitarska should we go through the tutorial w/ Django 1.9 and Python 3.5? Or is Python 3.4 fine?

**Comment by olasitarska** [comment]
Both are fine :)
