### ISSUE TITLE
Sidebar is invisible on internet explorer

### ISSUE THREAD

**Issue by DRMacIver** [DjangoGirls/tutorial#638]
We encountered this at django girls Windhoek. A lot of attendees struggled with the tutorial because they only had internet explorer and thus could not navigate.

This may only affect old versions. I'll try to find out the affected range.

The major problem with it is that it's not at all obvious that this browser choice doesn't work so people just get confused and don't realise it's not their fault. A link to download Chrome when running on an older IE may be acceptable given how much else needs installing

**Comment by JaimeLynSchatz** [comment]
@DRMacIver I can see the sidebar in IE 11 and above. IE 10 and below apparently hide it.

Do you want to work on this or do you want someone else to pick it up? (I'm in between learning projects and can pick this up if you need.)

**Comment by olasitarska** [comment]
Hi @DRMacIver and @JaimeLynSchatz -- this is [Gitbook](https://www.gitbook.com/)'s issue, not ours. Gitbook is the platform that we use for publishing this tutorial.

Thanks for reporting it!
