### ISSUE TITLE
CSS margins on mobile devices too large to see content

### ISSUE THREAD

**Issue by nickpennyuk** [DjangoGirls/tutorial#643]
.book .book-body .page-wrapper .page-inner section.normal {
    display: block;
    word-wrap: break-word;
    overflow: hidden;
    color: #333;
    line-height: 1.7;
    text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
    -moz-text-size-adjust: 100%;
}

The overflow is the culprit and changing this to overflow: none; fixes it.

![untitled-1](https://cloud.githubusercontent.com/assets/10087480/12726069/7c09143a-c90d-11e5-8db1-a621caec5619.png)

**Comment by olasitarska** [comment]
Hi @nickpennyuk! Our tutorial is published with Gitbook, so you can submit that fix to them :) 

Thanks!
