### ISSUE TITLE
template directory

### ISSUE THREAD

**Issue by AakashRaina** [DjangoGirls/tutorial#645]
nothing is written regarding the settings for template directory in settings.py

**Comment by olasitarska** [comment]
It should *just work* with default django settings. Could you elaborate on your problem?

**Comment by AakashRaina** [comment]
I was going through the tutorial and when I made the "post_listing.html" file under the specified directory,it gave an error showing "template does not exist".

**Comment by olasitarska** [comment]
I see. In the tutorial we recommend creating templates in specific directory, hence those instructions weren't necessary.

**Comment by GabiTurner** [comment]
Hello, my Mac is not rendering the html post_listing correct.. it shows all the tags and elements when I click on the url... any suggestions?

**Comment by ekohl** [comment]
> Hello, my Mac is not rendering the html post_listing correct.. it shows all the tags and elements when I click on the url... any suggestions?

It's probably best to open a new issue for this. It sounds like you're opening the HTML file directly instead of through Django.
