### ISSUE TITLE
Django - broken links - and what the hell is Django?

### ISSUE THREAD

**Issue by Peremptor** [DjangoGirls/tutorial#660]
On the site
http://tutorial.djangogirls.org/en/django_installation/index.html#
You say this:
"Part of this section is based on tutorials by Geek Girls Carrots (http://django.carrots.pl/)."
But the homepage seems to be freshly installed with nginx, no tutorials.
I think it is because those carrot girls are now going professional:
http://geekgirlscarrots.org/

I found this to be the official page of Django:
https://www.djangoproject.com/

And after all, I know PHP, I have a slight idea of Apache, nginx & Co. but where the hell is Django placed between them? You really should add a picture for such dumbs like me.
So I don't understand
- why you can manage packages (and which packages) with it
- what Python has to do with it (it's not just a programming language, is it?)
- why you would need a virtual environment
- and what exactly a virtual environment in this case is (I think it has nothing to do with Virtualbox and the like?)

I hope to see a bit more explaining in the future :)

**Comment by olasitarska** [comment]
Thanks for reporting broken links -- I created #668 issue to address that.

When it comes to your questions, I think this is something that goes beyond the scope of this tutorial, as we're tailoring it for complete beginners without any previous programming experience.

Thanks for help!
