### ISSUE TITLE
`include` not imported by default—leads to confusing errors

### ISSUE THREAD

**Issue by nimasmi** [DjangoGirls/tutorial#679]
I'm not sure where the behaviour changed, but the default state of `urls.py` after `startproject` is now

```
from django.conf.urls import url
```
The tutorial seems to assume that it is already
```
from django.conf.urls import include, url
```
and therefore makes no suggestions to amend this line.

I would suggest merely the above edit, except that conversations overheard at the session yesterday suggest to me that the recommended way of doing this has changed in 1.9. I've read through, https://docs.djangoproject.com/en/1.9/topics/http/urls/#including-other-urlconfs, and I'm happy with the above still, but raising an issue rather than submitting a PR, as I'm also happy to admit I'm wrong.

**Comment by helenst** [comment]
You are right :) See #686 - default urls.py has changed, I've put in a PR to fix this.

**Comment by helenst** [comment]
Closing this off as it's covered by another ticket.
