### ISSUE TITLE
GItHub Issue and Pull Request Templates

### ISSUE THREAD

**Issue by phalt** [DjangoGirls/tutorial#691]
We should draft up some templates for writing issues and pull requests against the tutorial.

I think it would be really useful for quickly categorising the types of issues (typos, translations, corrections) and also to help new users learn how to ask the correct people.

Opening this ticket so we can discuss content in the templates.

See: https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by aniav** [comment]
That would be awesome! Do you think we should collaborate on these templates or just use the simple proposed ones from github? :)

**Comment by aniav** [comment]
Done! 🎉
