### ISSUE TITLE
Update directory tree for blog to show "apps.py" on Step 10: Django models

### ISSUE THREAD

**Issue by ProProgrammer** [DjangoGirls/tutorial#712]
Running django on a Windows machine. For me, after I run `python manage.py startapp blog`. The blog directory has an additional file `apps.py` the default contents for which are:
```
from django.apps import AppConfig


class BlogConfig(AppConfig):
    name = 'blog'
```

We need to update the directory structure on [Step 10: Django models](http://tutorial.djangogirls.org/en/django_models/index.html) after the paragraph:

> You will notice that a new blog directory is created and it contains a number of files now. Our directories and files in our project should look like this:

**Comment by helenst** [comment]
:+1: I think this is a Django 1.9 thing

**Comment by helenst** [comment]
This could be a good first pull request for somebody.

The file `apps.py` needs adding to the tree in the "Creating an application" section.

https://github.com/DjangoGirls/tutorial/blob/master/en/django_models/README.md
