### ISSUE TITLE
Please (re-)connect Tutorial extension to Tutorial (post_detail.html)

### ISSUE THREAD

**Issue by BobAalsma** [DjangoGirls/tutorial#713]
The final state of blog/templates/blog/post_detail.html (http://tutorial.djangogirls.org/en/django_forms/index.html#edit-form) is:

`
    <div class="post">

        {% if post.published_date %}

            <div class="date">

                {{ post.published_date }}

            </div>

        {% endif %}
`

But in the extension (https://github.com/DjangoGirls/tutorial-extensions/blob/master/homework/README.md#add-publish-button ) the _expected_ final state is

```
{% if post.published_date %}
    {{ post.published_date }}
{% endif %}
```

Adding the else-clause does not seem straightforward at this point.

**Comment by aniav** [comment]
@BobAalsma I have updated the tutorial-extensions according to your comment! Thank you! :)
