### ISSUE TITLE
Introducing comments earlier on

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/tutorial#715]
Should comments be introduced in "Introduction to Python"? I know there is a lot there already but I don't think a lot of explanation is needed.

They are briefly introduced in the Views chapter when they are first encountered in the default Django files but perhaps earlier would be better. Especially since the Django 1.9 changes we are now introducing docstrings in the URLs chapter, so before comments - it seems more natural to learn about comments first.

**Comment by tBaxter** [comment]
Perhaps rather than simply introducing comments, a brief side excursion on the importance of documentation in general would be more helpful.
