### ISSUE TITLE
Azerbaijan

### ISSUE THREAD

**Issue by KamilBabayev** [DjangoGirls/tutorial#721]
Hi,
I hope you are doing well.

I am from Azerbaijan, Baku. I am learning Django currently. I am good with Python and Django.At the same time  I want to translate this tutorial to my own language. How can I start process ?

**Comment by helenst** [comment]
Hi @KamilBabayev 

Welcome! :sparkling_heart: It's awesome that you want to start a new translation. Since I don't think there's anything currently for your language, probably the best thing would be to email translations@djangogirls.org and somebody can help you get that set up!
