### ISSUE TITLE
Markdown is broken on "Extending your application"

### ISSUE THREAD

**Issue by humitos** [DjangoGirls/tutorial#723]
Take a look at the differences:
- English: http://tutorial.djangogirls.org/en/extend_your_application/index.html#create-a-url-to-a-posts-detail
- Spanish: http://tutorial.djangogirls.org/es/extend_your_application/index.html#url-http1270018000post1

**Comment by aniav** [comment]
This seems to have been fixed at some point since the issue was created. I am closing it now, feel free to reopen if you think the problem remains. Thanks! :dancer:
