### ISSUE TITLE
Domain section does not exist anymore

### ISSUE THREAD

**Issue by humitos** [DjangoGirls/tutorial#724]
Spanish version has a Domain section:
- http://tutorial.djangogirls.org/es/domain/index.html#

that is not more in the original English version:
- http://tutorial.djangogirls.org/en/django_forms/index.html

and I think it's ok, because we don't want to pay for a domain and it just confuses the attendees.

**Comment by helenst** [comment]
Agree - it should be removed from the translation. Would you like to submit a pull request for that? :smile:

**Comment by ProProgrammer** [comment]
@helenst Hey what changes would it require?
From what I understand
# I need to remove domain directory from the git project structure
# Remove `domain` entry from the sidebar (which file has all the contents that the tutorial sidebar uses to display list of chapters)

Please let me know if there are other changes required too.

**Comment by helenst** [comment]
@ProProgrammer The sidebar gets its list of chapters from `es/SUMMARY.md`. I think that's it. There's still a folder for it on Crowdin, but I'm not sure if that matters.
