### ISSUE TITLE
Replace uses of "easy", "simple", and "fast"

### ISSUE THREAD

**Issue by phalt** [DjangoGirls/tutorial#729]
At DjangoCon Europ 2016, [@oboechick_](https://twitter.com/oboechick_) did a lightning talk on steps to make beginner tutorials easy. The steps are summarised in this blog post: 

https://www.wordfugue.com/how-make-beginner-workshops-more-beginner-friendly/

I think we could analyse the steps and see if we can improve the tutorial! This should be a friendly task for beginners.

**Comment by asendecka** [comment]
I totalny agree! It is an amazing point.

**Comment by ChristinaG86** [comment]
Hi, I'm going to work on this for 24 Pull Requests :)

**Comment by aniav** [comment]
Done!
