### ISSUE TITLE
the tutorial in Danish

### ISSUE THREAD

**Issue by basiccreation** [DjangoGirls/tutorial#736]
I can translate it into Danish if that has any interest.

**Comment by ProProgrammer** [comment]
@basiccreation hey thats cool. Here's link to [DjangoGirls Translation Guide](https://github.com/DjangoGirls/translation-guide) repo, you may find this of help.

**Comment by basiccreation** [comment]
just looking at the different tutorials and it looks like the russian one
was uploaded into the UK one

**Comment by basiccreation** [comment]
Hi Deep,

I've started translating and I'm wondering if I'm supposed to translate the
whole thing before I upload it for I should commit as I go along.

thanks,
Pia

PS I think I answered my own question regarding the UK, I think it doesn't
mean United Kingdom but Ukraine :)

**Comment by patjouk** [comment]
Hi @basiccreation :)

You'll need to translate and proofread everything before deploying your translation on Github. More info here in the translation guide: http://translate.djangogirls.org/when_its_ready.html

**Comment by aniav** [comment]
I think we can close this for now. Everyone has all the required information 👍
