### ISSUE TITLE
Duplication of installation chapters?

### ISSUE THREAD

**Issue by phalt** [DjangoGirls/tutorial#744]
It appears we have duplicated the installation chapters by trying to move them to the beginning:

![image](http://i.imgur.com/dEovUZr.png)

Is this an intentional change?

**Comment by ProProgrammer** [comment]
The content in **1. Installation** is already present in **4. Python Installation**, **5. Code Editor** and **8. Django Installation**
I think we are good to remove Installation chapter and only introduce keep installation chapters in phases for each topic (Python, Code Editors and Django)

**Comment by ProProgrammer** [comment]
Also, **1. Installation chapter**'s Install Git and Create PythonAnywhere account sections are present in **12. Deploy** chapter

**Comment by phalt** [comment]
@ProProgrammer had a discussion with @helenst about it this morning.

It's good to keep the installation chapters throughout the tutorial, as it let's a developer who are jumping into sections know what she needs to install in order to do the chapter. It doesn't hurt to have it there!

**Comment by aniav** [comment]
I think we should highlight better why the installation chapter is there. I had at least two coaches confused about that thing too. There is an information at the beginning why the chapter is there but I believe it is not clear enough.
