### ISSUE TITLE
Why i got ValueError at /post/1 ?

### ISSUE THREAD

**Issue by thinhduckhoi** [DjangoGirls/tutorial#755]
Hi guys,
After finishing creating the Blog following DjangoGirl tutorial, i got my own blog. 
Everything was fine until today, i didn't understand why but i wasn't be able to create a new post anymore. (Create by click to the button on the main page, not from django admin interface)
No error came out so i really don't know what happened.
Hope to get help from everyone!

**Comment by helenst** [comment]
Hi @thinhduckhoi :tulip: Sorry for the late reply... I am not sure what is wrong here, but it would be worth asking in the [Gitter channel](https://gitter.im/DjangoGirls/tutorial) where there are usually people hanging out to help you through the tutorial - the issues section here is really for tracking changes that need to be made to the tutorial.
