### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by LotosikRa** [DjangoGirls/tutorial#769]
When I completing steps from [there](http://tutorial.djangogirls.org/ru/django_start_project/) I get some error message:
![ice_screenshot_20160508-071523](https://cloud.githubusercontent.com/assets/18006909/15096033/9a1d80fe-14ef-11e6-8816-4dd19b6b68f4.png)
but I allready install django:
![ice_screenshot_20160508-071450](https://cloud.githubusercontent.com/assets/18006909/15096034/a92429b8-14ef-11e6-8aa4-47ad5ff90393.png)
What I need to do to fix it?

**Comment by helenst** [comment]
Hi @LotosikRa Sorry for the late reply... I am not sure what is wrong here, it looks like maybe something is wrong with your virtualenv. It might be worth recreating it and trying again.

You can also ask on the [Gitter channel](https://gitter.im/DjangoGirls/tutorial) where there are usually people hanging out to help you through the tutorial - the issues section here is really for tracking changes that need to be made to the tutorial. :cherry_blossom:
