### ISSUE TITLE
Adding a custom CSS file requires restarting Django development server

### ISSUE THREAD

**Issue by gsong** [DjangoGirls/tutorial#781]
During our tutorial session, adding the custom blog CSS file required us to restart `./manage.py run server` in order for Django to pick up the new static file.

**Comment by haberd** [comment]
I restarted and still no luck. Try running "python manage.py collectstatic" and then restart the server.

**Comment by gsong** [comment]
You shouldn't need to `collectstatic` for development environments, that's meant for production deployment.

**Comment by haberd** [comment]
I had to reload the page while ignoring cached content: 'ctrl' + 'shift' + 'r' in Chrome

**Comment by yoavram** [comment]
👍
