### ISSUE TITLE
Are we should or not add info about same setup problems on non-Ubuntu distributives?

### ISSUE THREAD

**Issue by MaxymVlasov** [DjangoGirls/tutorial#784]
For example, in [django instalation](https://github.com/DjangoGirls/tutorial/blob/master/en/django_installation/instructions.md)
>NOTE: Initiating the virtual environment on Ubuntu 14.04 like this currently gives the following error:

>`Error: Command '['/home/eddie/Slask/tmp/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1`

Give same error for Debian 8 x64

**Comment by aniav** [comment]
I think in this specific case we can add the information. It will always be easier for both the mentors and the attendees :)
