### ISSUE TITLE
Introduction to command line: 'rmdir' vs 'del' for Windows users

### ISSUE THREAD

**Issue by ineptcat** [DjangoGirls/tutorial#788]
In the summary of useful commands the command `del` is listed for Windows users despite not being introduced previously. Should this be changed to `rmdir` for consistency's sake? 

The following text also says "delete a directory/file" which may be the cause of this confusion. Perhaps put it in two rows:

`rmdir` (or `del`) | `rm` | delete a file
`rmdir /S` | `rm -r` | delete a directory

as above tutorial users are told to use `rmdir /S` or `rm -r` without explanation of the flag.

**Comment by aniav** [comment]
Thank you for you input, I have intruduced the proposed changes in f366d43 😊

**Comment by johntiger1** [comment]
Does anyone know why `del` cannot remove directories?
