### ISSUE TITLE
Inconsistent use of British vs. American English

### ISSUE THREAD

**Issue by logological** [DjangoGirls/tutorial#793]
The English version of the tutorial uses a strange mix of British and American spellings ("learned" in some places and "learnt" in others, "recognize" in some places and "recognise" in others, etc.).  I'd gladly volunteer to fix this but first I need to know what dialect the tutorial is *supposed* to be written in.

**Comment by aniav** [comment]
I am a big fan of British English and will always vote on that.

@olasitarska and @asendecka, how about you? :)

**Comment by phalt** [comment]
Despite being British and preferring British English I think American English is more commonly used.

**Comment by olasitarska** [comment]
![screenshot 2016-06-21 18 46 35](https://cloud.githubusercontent.com/assets/527795/16240272/910ff7d0-37e0-11e6-9a4d-6897273160b2.png)

Data from Analytics ^

Let's go with American English?

**Comment by aniav** [comment]
👍

**Comment by logological** [comment]
So are you agreed on American?  Would you like me to fix the issue?

**Comment by aniav** [comment]
@logological you are free to do that :)

**Comment by olasitarska** [comment]
Yup, go for it!

**Comment by logological** [comment]
Fixed by Commit 1ac6ba2.
