### ISSUE TITLE
No *.msi file on downloads page (from Windows installation)

### ISSUE THREAD

**Issue by treyhunner** [DjangoGirls/tutorial#824]
> After downloading the *.msi file, you should run it (double-click on it) and follow the instructions there.

![selection_839](https://cloud.githubusercontent.com/assets/285352/17524784/cb561960-5e14-11e6-8d0f-aad67d39c46c.png)

Maybe we should instruct students to get the "Windows x86-64 executable installer" or the "Windows x86 executable installer" if the other one doesn't work?

**Comment by delenamalan** [comment]
Duplicate of #861 . See PR #872.

**Comment by patjouk** [comment]
Fixed by #872
