### ISSUE TITLE
intro to commandline: practice directory got renamed djangogirls again in some locations

### ISSUE THREAD

**Issue by githubsara** [DjangoGirls/tutorial#828]
### Chapter introduction to commandline
To avoid confusion between the real djangogirls directory where the application will run
and the practice directory created and destroyed again in the introduction to commandline chapter
@craigsdennis introduced the name of this second one to be 'practice' instead of 'djangogirls'.

During some recent changes made by @aniav it got changed again to 'djangogirls' in the code examples but not in the text. So now its even more confusing. lets make it 'practice' everywhere.

**Comment by helenst** [comment]
Thank you for spotting this! :sparkling_heart: We'd welcome a pull request to fix it
