### ISSUE TITLE
Add pointer arrows to Screen Shots

### ISSUE THREAD

**Issue by alanhamlett** [DjangoGirls/tutorial#849]
Some people get stuck looking at screen shots, for example http://tutorial.djangogirls.org/en/deploy/, and don't know what the screen shot is showing.

We could add arrows pointing to the important parts of the screen shot to improve this.

**Comment by patjouk** [comment]
Some highlights and pointers would definitely help! Feel free to do a PR about this :wink:

**Comment by mr-karan** [comment]
I'd like to take this up 😄
