### ISSUE TITLE
Error on initalizing virtaul environment on ubuntu 14.04

### ISSUE THREAD

**Issue by anshuldawar** [DjangoGirls/tutorial#855]
![screenshot from 2016-09-07 23 20 01](https://cloud.githubusercontent.com/assets/10780826/18322709/a8af93ba-7551-11e6-978a-95dacf2f1d67.png)

Virtual Environment is not working on the Ubuntu 14.04 python 3.4.3

**Comment by brendancain99** [comment]
Please try the following if you are still having this issue

`pip3 install virtualenv`

`virtualenv -p /usr/bin/python3 myvenv`

`source myvenv/bin/activate`

**Comment by anshuldawar** [comment]
i'm using PyCharm now
