### ISSUE TITLE
font size is too small in gitbook pdf 

### ISSUE THREAD

**Issue by sogen** [DjangoGirls/tutorial#857]
Hi, the generated PDF from gitbook has a small font size, how can it be bigger?

**Comment by sogen** [comment]
whoa, great

**Comment by patjouk** [comment]
Sadly, it doesn't seem to be fixed :(
I'll reopen this issue and take another look

**Comment by aniav** [comment]
I have increased fonts in settings, in the meantime they were increased once as well. I hope it's enough, closing this 🌷
