### ISSUE TITLE
CSS doesn't show up on first deploy to PythonAnywhere

### ISSUE THREAD

**Issue by gkhaburzaniya** [DjangoGirls/tutorial#860]
When I got to http://tutorial.djangogirls.org/en/deploy/#you-are-live and looked at the newly deployed website, the CSS was missing. I needed 2 additional steps to get it to work.
1. run `python manage.py collectstatic` from the bash pythonanywhere console
2. Add `/static/` as the URL and `/home/<username>/<projectname>/static` as the directory in the Web tab

**Comment by userimack** [comment]
Hi @gkhaburzaniya, we can add few more steps in that tutorial. I will be able to do this. Thank you.

**Comment by codehakase** [comment]
@gkhaburzaniya does it show up locally?

**Comment by gleidsonf** [comment]
I solved this problem removing '/static' from .gitignore, and running 'python manager.py collectstatic' after.

**Comment by ekohl** [comment]
We rewrote the deployment section and now uses a script which should take care of this. I'm closing the issue but feel free to reopen if it still persists.
