### ISSUE TITLE
Windows installation should explain which file to download

### ISSUE THREAD

**Issue by alexwlchan** [DjangoGirls/tutorial#861]
In the [section on Windows installation](http://tutorial.djangogirls.org/en/python_installation/), the reader is directed to https://www.python.org/downloads/release/python-351/. This has several download options for Windows users:

* Windows help file
* Windows x86-64 embeddable zip file
* Windows x86-64 executable installer
* Windows x86-64 web-based installer
* Windows x86 embeddable zip
* Windows x86 executable
* Windows x86 web-based installer

and it’s decidedly non-obvious which package they should use. It would be helpful to provide some guidance on which package to download. (This is a problem in both the tutorial and the Python website, but it’s easier for me to get the tutorial changed.)

Additionally, the text refers to a `*.msi` file – but that doesn’t seem to be one of the options here.

**Comment by delenamalan** [comment]
See PR #872
