### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by rn0rdin** [DjangoGirls/tutorial#918]
while following your guideline i faced no problem playing in localhost 
but when i reached the Deploy stage i faced a Problem which it seems that you forgot to mention 
that we should edit the settings.py and add the following line

ALLOWED_HOSTS = ('<user-name>.pythonanywhere.com', ) 

in order to make the app work online

i created two accounts and redone the tutorial trice to figure out what is the problem

**Comment by patjouk** [comment]
Thanks for reporting this problem.
Fixed by #901
