### ISSUE TITLE
Moving it to Django 1.10

### ISSUE THREAD

**Issue by supritashankar** [DjangoGirls/tutorial#932]
Hello Ladies,

Great job with the tutorials! 

I want to move this to Django 1.10. Would you guys want that? I want to get 👍  from you girls before I invest time in it.

Thanks!

**Comment by supritashankar** [comment]
cc @aniav @olasitarska

**Comment by helenst** [comment]
Hi @supritashankar thank you for proposing this. I'm in favour of it. I haven't used Django 1.10 so I'm not really aware of the changes it involves but  Django 1.9 will only be supported until April so it is good to be moving forward.

PS. please don't address us as "guys" - many of us are not :) I know it is often used as a supposedly gender neutral term, but it isn't really and it's something we try to avoid in the Django Girls community. Thanks! :sparkling_heart:

**Comment by supritashankar** [comment]
@helenst ok great! I am going to spend the next few days porting it over. 
Thank you for correcting me 😍 I have updated the comment.
