### ISSUE TITLE
Translations should explain LANGUAGE_CODE

### ISSUE THREAD

**Issue by aericson** [DjangoGirls/tutorial#936]
I recently helped out on a Django Girls event in Brazil. It was great! Congratz!

One thing I noticed it that the tutorial doesn't suggest changing the `LANGUAGE_CODE` of Django's installation.

I've noticed that many beginners had trouble with English and would really improve their experience if they were seeing messages in their native languages.

I would love helping with this but I'm not sure how we would address this. Should we make a note on the English version and translators would follow it?

**Comment by aniav** [comment]
This has already been introduced and added to the Start your first Django project section: https://tutorial.djangogirls.org/en/django_start_project/ :)
