### ISSUE TITLE
Clarify name of blog/urls.py - Django urls

### ISSUE THREAD

**Issue by kayharth** [DjangoGirls/tutorial#937]
Previously in the tutorial, file names were made separate from the folder they should live in. For a beginner, being told to create a new file named "blog/urls.py" is misleading. Indicate that "blog/" is another way of indicating the folder the file "urls.py" should live in. 
![screen shot 2016-12-03 at 4 33 40 pm](https://cloud.githubusercontent.com/assets/23407316/20862648/4b07944c-b976-11e6-9afc-e2ebc6ae6b0c.png)

**Comment by codehakase** [comment]
@kayharth what that part means is, in your `blog` directory, create a file `urls.py`

**Comment by helenst** [comment]
Hi @codehakase I think @kayharth was pointing out that this is potentially confusing to people working through the tutorial, not that they were necessarily confused themselves. :sun_with_face: I think clarifying the text would be a good idea.
