### ISSUE TITLE
Problems installing python3.5 on cloud 9

### ISSUE THREAD

**Issue by codehakase** [DjangoGirls/tutorial#954]
whilst installing python on cloud9, i get this error:
```
>>> /etc/sudoers: syntax error near line 15 <<<
sudo: parse error in /etc/sudoers near line 15
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

after running the `sudo apt install python3.5-venv` command

**Comment by helenst** [comment]
Hi @codehakase I think this is a cloud9 problem that is happening at the moment. See https://community.c9.io/t/etc-sudoers-syntax-error-near-line-15/12582/82 for other people having the same issue. Unfortunately it has not been fixed yet.

I'm going to close this as it is not an issue with the Django Girls tutorial. :unicorn: :rainbow:
