### ISSUE TITLE
"Homework: Secure Your Website">>Improving the layout: "Homework" at the end of the section

### ISSUE THREAD

**Issue by micaswyers** [DjangoGirls/tutorial#956]
I just had a good time working through the tutorial and some of the extension lessons (on my own). I noticed that in the "Improving the layout" section of the security section, there is an additional homework note reading 

> Homework: Edit the template blog/templates/blog/post_detail.html to only show the add and edit buttons to authenticated users.

However, because the add & edit buttons are part of the `base.html` template, I am unsure why editing the `post_detail.html` file would add any additional functionality. The beginning of the "Improving the layout" section already edits the `base.html` file to show/hide the add & edit buttons. If this "Homework" note is referring to the "edit" and "remove" buttons for an individual post, they are already covered by an `is_authenticated` check.

**Comment by helenst** [comment]
Hi @micaswyers It's good to hear you have enjoyed working on the tutorial and well done for getting all the way through to the extensions! :zap: We have an issue open for that already https://github.com/DjangoGirls/tutorial-extensions/issues/44 and there's even a fix waiting to go in - so I will close this one - but thank you for reporting it, we'll make sure that fix goes in as it's a little confusing as it currently stands. Thanks! :purple_heart:
