### ISSUE TITLE
Some more tasks for Installation Party

### ISSUE THREAD

**Issue by bauerv** [DjangoGirls/tutorial#969]
During the last workshop, we realized that a few more things could be frontloaded during the installation party to streamline the main workshop day:

* intro to command line (participants need it during the installation)
* creating the project on the command line
* testing GIT (especially Mac users, as most additionally need to install xcode command line tools to run git, this can take up to 15 minutes)
* setting up venv and installing Django on PythonAnywhere already during the installation

This would mean adding intro to command line and deploy to the installation party section.

Any thoughts on this?

**Comment by aniav** [comment]
Hey @bauerv I am not a fan of adding anything to the installation party section. There are a few reasons to this:
* it takes different amounts of time to different people to install the basic software
* it depends on the OS you are using if the installation goes well and how much time it takes
* every Django Girls event is different and the installation party can be shorter or longer depending on it
* each group will go at their own pace and if they want they can go on and start doing other things after the installation chapter if they want to.

I will close this issue for now but feel free to reopen and comment with more insight on the matter 🎉
