### ISSUE TITLE
Use {% endblock %} instead of {% endblock <blockname> %} everywhere

### ISSUE THREAD

**Issue by das-g** [DjangoGirls/tutorial#986]
### History

The `endblock` Django template tag takes an optional argument: The block name, which must match the corresponding block name passed to the `block` tag that started the block. See [Template inheritance documentation](https://docs.djangoproject.com/en/1.10/ref/templates/language/#template-inheritance):

> For extra readability, you can optionally give a name to your `{% endblock %}` tag. For example:
> 
> ```html+django
> {% block content %}
> ...
> {% endblock content %}
> ```
> 
> In larger templates, this technique helps you see which `{% block %}` tags are being closed.

This has been used inconsistently in the tutorial. https://github.com/DjangoGirls/tutorial/issues/500#issuecomment-151468004 decided to get rid of it, but corresponding commits e97da025409dee4a88f8169a5d1663481aad6a9d and eb02ca9f958168da46ccef98f59f0b6f0ba85596 only partially removed it.

If I understand https://github.com/DjangoGirls/tutorial/pull/534#issuecomment-156489924 and https://github.com/DjangoGirls/tutorial/pull/534#issuecomment-161599097 correctly, it was then decided to use the optional argument everywhere or at least consistently.

### Status quo

The current instructions are still inconsistent, though:
In https://tutorial.djangogirls.org/en/template_extending/#create-a-base-template, the [end of the empty block](https://github.com/DjangoGirls/tutorial/blame/36b2c48601dd2104da47d8c4a055e7432f12e4cb/en/template_extending/README.md#L70) in the new `base.html` lacks the block name argument. For the stripped-down `post_list.html`, the [instructions](https://github.com/DjangoGirls/tutorial/blame/36b2c48601dd2104da47d8c4a055e7432f12e4cb/en/template_extending/README.md#L105) tell to
> put everything between `{% block content %}` and `{% endblock content %}`

but the result of that is [presented](https://github.com/DjangoGirls/tutorial/blame/36b2c48601dd2104da47d8c4a055e7432f12e4cb/en/template_extending/README.md#L119) to be

> ```html+django
> {% block content %}
>     {% for post in posts %}
>         <div class="post">
>             <div class="date">
>                 {{ post.published_date }}
>             </div>
>             <h1><a href="">{{ post.title }}</a></h1>
>             <p>{{ post.text|linebreaksbr }}</p>
>         </div>
>     {% endfor %}
> {% endblock %}
> ```

Then, in the following https://tutorial.djangogirls.org/en/extend_your_application/#create-a-template-link-to-a-posts-detail, the argument [is suddenly there](https://github.com/DjangoGirls/tutorial/blame/36b2c48601dd2104da47d8c4a055e7432f12e4cb/en/extend_your_application/README.md#L28):

> So far it should look like this:
> 
> `blog/templates/blog/post_list.html`
> 
> ```html+django
> {% extends 'blog/base.html' %}
> 
> {% block content %}
>     {% for post in posts %}
>         <div class="post">
>             <div class="date">
>                 {{ post.published_date }}
>             </div>
>             <h1><a href="">{{ post.title }}</a></h1>
>             <p>{{ post.text|linebreaksbr }}</p>
>         </div>
>     {% endfor %}
> {% endblock content %}
> ```

### Options

I see 3 possible ways for how to make this consistent:
- pass the block name always (also for the empty block in `base.html`)
- pass the block name only for the block with content in `post_list.html`, but not for the empty block
- never pass the block name in the `{% endblock %}` tag

Instructions as well as the code snippets on both these chapters would have to be adapted, depending on which of these options we choose. Which one shall it be?

(Once that is decided, I can provide a pull request either for only `en` or for all languages.)

**Comment by aniav** [comment]
Hy @das-g. Sorry for not replying ealier. I think we can totally go with not passing the block name to `{% endblock %}`. I feel this is the easiest solution making the code more consistent for a newcomer (e.g. more cosistent with `{% endfor %}`) :)

**Comment by harshk10** [comment]
I Hae an error on running this code

{% extends 'base.html' %}
{% block content }
<body>
<h1> Hello world !!!!!!! </h1>
</body>    

{% endblock  %}


Invalid block tag on line 11: 'endblock'. Did you forget to register or load this tag

how to solve this i cant find please help me

**Comment by harshk10** [comment]
in above code the Hello world l!!!! is written inside  h1 tag .

**Comment by das-g** [comment]
@harshk10 If you work with the tutorial on your own and don't have a coach who will help you in case of any problem, we have a chat system for you: In [our chatroom on Gitter](https://gitter.im/DjangoGirls/tutorial), some coaches and previous attendees try to help others with the tutorial. Don't be afraid to ask your question there!

If you believe that your error message is due to an error in the tutorial, please [file a separate issue](https://github.com/DjangoGirls/tutorial/issues/new) about that.

**Comment by elgatoloco22** [comment]
> I Hae an error on running this code
> 
> ```
> {% extends 'base.html' %}
> {% block content }
> <body>
> <h1> Hello world !!!!!!! </h1>
> </body>    
> 
> {% endblock  %}
> ```
> 
> Invalid block tag on line 11: 'endblock'. Did you forget to register or load this tag
> 
> how to solve this i cant find please help me

late, but... you are missing one "%" after block content and the clossing "}"
