### ISSUE TITLE
Python 3.5.x is no longer available at Windows download section

### ISSUE THREAD

**Issue by humitos** [DjangoGirls/tutorial#992]
At https://github.com/DjangoGirls/tutorial/blob/master/en/python_installation/instructions.md, it says

> First check whether your computer is running a 32-bit version or a 64-bit version of Windows at https://support.microsoft.com/en-au/kb/827218. You can download Python for Windows from the website https://www.python.org/downloads/windows/. Click on the "Latest Python 3 Release - Python x.x.x" link

but going to https://www.python.org/downloads/windows/ is says _Latest Python 3 Release - Python 3.6.0_ so people ends installing 3.6.0 and the all tutorial says 3.5.x

**Comment by myhokiki** [comment]
then which version should I use??

**Comment by aniav** [comment]
@myhokiki If you have python 3.5 installed already you can totally use it with Django, no need to reinstall. If you don't have python installed you can install Python 3.6.

@humitos thank you for noting this! :)

**Comment by aniav** [comment]
Tutorial has been updated to use Python 3.6. I am closing this, thank you! 🎉
